### ISSUE TITLE
Book "part" display is broken

### ISSUE THREAD

**Issue by justinQQx** [plk/biblatex#1001]
In @Book, `part` doesn't display, leaving only the closing dot. Document class doesn't matter. Language doesn't matter.

Here's a MWE:
```
\begin{filecontents}{dummy.bib}
@Book{Fairbank2013,
	author    = {John King Fairbank and Merle Goldman},
	date      = {2013},
	title     = {History of China},
	pages     = {491-646},
	part      = {4 - The People's Republic of China},
}
\end{filecontents}

\documentclass{article}
\usepackage{biblatex}
\addbibresource{dummy.bib}

\begin{document}
	Text\cite{Fairbank2013}
	\printbibliography
\end{document}
```

**Comment by moewew** [comment]
`part`  can never occur without `volume`. That's why you get this undesirable output.

The documentation explains `part` as follows
> The number of a partial volume. This field applies to books only, not to journals. It
may be used when a logical volume consists of two or more physical ones. In this
case the number of the logical volume goes in the `volume` field and the number of
the part of that volume in the `part` field. See also `volume`.

Since you don't seem to subdivide a *logical* volume here, I don't think that is what you want.

For simplicity I'm referring to https://www.hup.harvard.edu/catalog.php?isbn=9780674018280, more specifically the ToC available here http://external.dandelon.com/download/attachments/dandelon/ids/CH001C7C0E9D6FA57BA06C12573230038E322.pdf

Usually with monograph one adds the complete book to the bibliography and gives more specific page references in citations
```latex
@book{fairbank,
  author    = {John King Fairbank and Merle Goldman},
  date      = {2006},
  title     = {China},
  subtitle  = {A New History},
  edition   = {\autocap{s}econd enlarged edition},
  publisher = {Belknap Press},
  location  = {Cambridge, Massachusetts},
}
```
Sometimes it is useful to cite only a specific chapter/section with `@inbook`
```latex
@inbook{fairbank,
  author       = {John King Fairbank and Merle Goldman},
  title        = {The Great Leap Forward, 1958--1960},
  chapter      = {19},
  pages        = {368-382},
  date         = {2006},
  booktitle    = {China},
  booksubtitle = {A New History},
  edition      = {\autocap{s}econd enlarged edition},
  publisher    = {Belknap Press},
  location     = {Cambridge, Massachusetts},
}
```

I not yet seen people refer to a larger collection of chapters (what's called a "part" here), but I guess you would still use `@inbook`, though you could not use `part` and would probably not want to use `chapter`
```latex
@inbook{fairbank,
  author       = {John King Fairbank and Merle Goldman},
  title        = {Part 4: The People's Republic of China},
  pages        = {343-456},
  date         = {2006},
  booktitle    = {China},
  booksubtitle = {A New History},
  edition      = {\autocap{s}econd enlarged edition},
  publisher    = {Belknap Press},
  location     = {Cambridge, Massachusetts},
}
```

**Comment by justinQQx** [comment]
What a great answer. I misunderstood the documentation. Thank you for providing detailed *and commented(!)* code.
