### ISSUE TITLE
Letters incorrectly added after year

### ISSUE THREAD

**Issue by keithbriggs** [plk/biblatex#1002]
I'm getting this in my bibliography:

> Jones, Malcolm (1989), ‘Folklore motifs in late medieval art 1: proverbial follies and impossibilities’, Folklore 100, pp. 201–217. 
> — (2002a), The secret Middle Ages, Thrupp: Sutton Publishing. .
> Jones, Mark J. (2002b), ‘The origin of Definite Article Reduction in northern English dialects: evidence from dialect allomorphy’, English Language and Linguistics 6.2, pp. 325–345. 

It looks like biblatex thinks the two authors are the same.   Each author only has one 2002 entry in my .bib file.  How do I fix this?

**Comment by perstar** [comment]
That is not what you get with standard "style=authoryear". Probably you have turned the unique names feature off with "uniquename=false". Then of course letters are needed since "(Jones 2002)" would be ambigious.

**Comment by keithbriggs** [comment]
Thanks, that must be the reason.   My tex file has 23221 lines and I'd forgotten that uniquename=false was hiding somewhere in there!

Keith

________________________________

**Comment by moewew** [comment]
@keithbriggs Please always include a short example document when you ask questions like this. It is quite frustrating to have to try and reproduce the settings you might have used to produce the output shown. Plus, it is straightforward for you to produce a short example document that reproduces the output, while it will take outsiders much longer (we have to re-type your `.bib` entries for starters). At the very least you could have shared the relevant `.bib` entries to avoid us having to copy them manually.

As already discussed the vanilla `authoryear` style will not produce this output because it disambiguates the names
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@article{jones.malcom:folklore,
  author  = {Jones, Malcolm},
  year    = {1989},
  title   = {Folklore motifs in late medieval art 1:
             proverbial follies and impossibilities},
  journal = {Folklore},
  volume  = {100},
  pages   = {201–217},
}
@book{jones.malcom:secret,
  author    = {Jones, Malcolm},
  year      = {2002},
  title     = {The secret Middle Ages},
  location  = {Thrupp},
  publisher = {Sutton Publishing},
}
@article{jones.mark,
  author = {Jones, Mark J.},
  year   = {2002},
  title  = {The origin of Definite Article Reduction in
            northern English dialects:
            evidence from dialect allomorphy},
  journal = {English Language and Linguistics},
  volume  = {6},
  number  = {2},   
  pages   = {325–345},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
\autocite{jones.malcom:folklore}

\autocite{jones.malcom:secret}

\autocite{jones.mark}

\printbibliography
\end{document}
```
>(M. Jones 1989)
>(M. Jones 2002)
>(M. J. Jones 2002)

But as @perstar rightly points out, if you turn off the name disambiguation with `uniquename=false,`,  `biblatex` has no choice but to add an `extradate` letter to make the citation labels unique.

>(Jones 1989)
>(Jones 2002a)
>(Jones 2002b)

we can't end up with two different "Jones 2002" entries.
