### ISSUE TITLE
[idea] index generation

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex#1006]
This is just a wild (and maybe odd) idea, and I understand if you will immediately close this.

Since `xindy` is [not developed any more for quite some time](https://tug.org/pipermail/tex-live/2020-May/045753.html) and has a number of severe limitations, and `makeindex` cannot do non-ASCII well, there is no really contemporary index generator available for LaTeX. I was just wondering since the most tricky part is locale-aware sorting of the index, and since biber does exactly this pretty well, how hard it would be to provide this feature on top of `biblatex`/`biber` (rather than rewriting `xindy` from scratch in, say, perl or python).

Probably the most tricky part would be to parse the index command with all its active characters. But apart from that, it strikes me that the task is not very different from generating a bibliography (only less complex).

But as said, I understand if you say: this exceeds our scope.

**Comment by jspitz** [comment]
> there is no really contemporary index generator available for LaTeX. 

Having written this, I was just pointed to https://www.ctan.org/pkg/xindex which is a contemporary rewrite of makeindex using lua. This might obsolete the idea.

**Comment by moewew** [comment]
In theory you could code an indexing solution in `biblatex`. Like the following proof of concept based on https://tex.stackexchange.com/q/438759/35864
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage{filecontents}
\begin{filecontents}{indexing.dbx}
\DeclareDatamodelEntrytypes{index}
\DeclareDatamodelFields[type=field,datatype=literal]{
  short,
  long,
}
\DeclareDatamodelEntryfields[index]{
  short,
  long,
}
\end{filecontents}

\usepackage[style=verbose, backend=biber, datamodel=indexing]{biblatex}

\ExecuteBibliographyOptions{citetracker=true}

\DeclareBibliographyDriver{index}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \printfield{short}%
  \setunit{\addcolon\space}%
  \printfield{long}%
  \setunit{\bibpagerefpunct}\newblock
  \usebibmacro{pageref}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{finentry}}


\renewbibmacro*{indexcite}{%
  \ifentrytype{index}
    {\ifciteseen
       {\printfield{short}}
       {\usebibmacro{firstindex}}}
    {\PackageWarning{biblatex-index}{\thefield{entrykey} is not an index entry}}}

\newbibmacro*{firstindex}{%
  \printfield{long}%
  \setunit{\addspace}%
  \printfield[parens]{short}}

\DeclareSourcemap{
  \maps[datatype=bibtex,overwrite=false]{
    \map{
      \pertype{index}
      \step[fieldsource=short]
      \step[fieldset=sortkey, origfieldval]
    }
  }
}

\DeclareCiteCommand{\blxindex}
  {}
  {\usebibmacro{indexcite}}
  {\multicitedelim}
  {}

\begin{filecontents}{\jobname.bib}
@index{cd,
  short = {CD},
  long  = {compact disc},
}
\end{filecontents}

\addbibresource{\jobname.bib}


\begin{document}
\blxindex{cd} and again \blxindex{cd}
\printbibliography[type=index, title={Index}]
\end{document}
```
Of course you would be using `biblatex` facilities, which means you need to put in some work to keep normal citations and bibliography separate from citations. (You could also not use this with normal BibTeX. In the example you also have to give the index entries in a `.bib` file, though that could be done differently with a `.bib` file created on the fly.) So I doubt anyone is ever going to seriously consider this approach.


A solution that only uses Biber for sorting and otherwise does not use `biblatex` interfaces appears possible, but probably not very desirable. It would need a new Biber interface layer that is essentially developed independent of `biblatex` to give access to sorting. Especially if you want this Biber solution to be a (near) drop-in replacement for `xindy` (so something that doesn't read a `.bcf` but instead various `.id...` files), it would need quite some work. People already complain that Biber is 'too slow' and adding more stuff it should do would likely not make it faster. You essentially 'only' need two features of the vast variety of things Biber can do

* Unicode sorting (I guess that is available in many programming languages, but of course you want to be sure it is robust)
* a TeX-macro-to-Unicode converter (\"a -> ä) etc. (that one is tricky to get right, but it could essentially be a hard-coded list like https://github.com/plk/biber/blob/dev/lib/Biber/LaTeX/recode_data.xml)

all the other things (BibTeX parsing in all its gory details, on-the-fly data manipulation with source maps, ...) are not required.

I would say that an independent program would be the better choice here. (If it is written in Perl it can certainly borrow from Biber.)

I would have expressed the hope that Lua might be able to do something for us here given that it is part of the TeX world, but with `xindex` you have already found something that shows that Lua might be an option. (I even heard hopes that one day Biber replacement might be coded in Lua.)

**Comment by jspitz** [comment]
Thanks for the detailed explanation. I see know that this was an odd idea, indeed,
