### ISSUE TITLE
why the hyperref package loaded in hook `\AtEndPreamble` not work？

### ISSUE THREAD

**Issue by hushidong** [plk/biblatex#1029]
why the hyperref package loaded in hook `\AtEndPreamble` not work？

Today I found a hyperlink problem.

according to the biblate.pdf the hyperref should be loaded after biblatex, so I placed hyperref last in preamble, it works fine.

but when I put the package in the hook `\AtEndPreamble`, it does not work, even given the hyperref=true when loading biblatex.

howerver I tested hyperref=manual option, when I gave the `\BiblatexManualHyperrefOn` after loading hyperref in the hook, it works fine.

that is why?

test case:

case 1 work fine:

```
\documentclass[twoside]{article}
    \usepackage{xcolor}
    \usepackage{etoolbox}
\usepackage[backend=biber,style=authoryear]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{lamport1986document,
    title={Document Preparation System},
    author={Lamport, Leslie},
    year={1986},
    publisher={Addison-Wesley Reading, MA}
}
\end{filecontents}
    \addbibresource{\jobname.bib}
    %

\usepackage[colorlinks]{hyperref}

    \begin{document}
    \section*{test hyperlinks}

\textcite{lamport1986document}

    \printbibliography

    \end{document} 
```

case 2 not work :

```
\documentclass[twoside]{article}
    \usepackage{xcolor}
    \usepackage{etoolbox}
\usepackage[backend=biber,style=authoryear,hyperref=true]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{lamport1986document,
    title={Document Preparation System},
    author={Lamport, Leslie},
    year={1986},
    publisher={Addison-Wesley Reading, MA}
}
\end{filecontents}
    \addbibresource{\jobname.bib}
    %

    %\usepackage[colorlinks]{hyperref}

\AtEndPreamble{%
    \usepackage[colorlinks]{hyperref}% load at last
}

    \begin{document}
    \section*{test hyperlinks}

\textcite{lamport1986document}

    \printbibliography

    \end{document} 
```

case 3 work fine:

```
\documentclass[twoside]{article}
    \usepackage{xcolor}
    \usepackage{etoolbox}
\usepackage[backend=biber,style=authoryear,hyperref=manual]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{lamport1986document,
    title={Document Preparation System},
    author={Lamport, Leslie},
    year={1986},
    publisher={Addison-Wesley Reading, MA}
}
\end{filecontents}
    \addbibresource{\jobname.bib}
    %

    %\usepackage[colorlinks]{hyperref}

\AtEndPreamble{%
    \usepackage[colorlinks]{hyperref}% load at last
    \BiblatexManualHyperrefOn
}

\AtEndDocument{%
    \BiblatexManualHyperrefOff
}


    \begin{document}
    \section*{test hyperlinks}

\textcite{lamport1986document}

    \printbibliography

    \end{document} 
```

**Comment by moewew** [comment]
`biblatex` does different things depending on whether or not `hyperref` is loaded. Since `hyperref` is usually loaded last, the most reliable way to find out whether or not `hyperref` is loaded (that I know of anyway) is to do the check in an `\AtBeginDocument`/`\AtEndPreamble` hook. The check is performed at the beginning of the long `\AtEndPreamble` hook starting from line 256 (ll. 259-272 are the interesting ones).

https://github.com/plk/biblatex/blob/089ce33f1e3cbde9433fda6e8ab4c82e96018b80/tex/latex/biblatex/biblatex.sty#L256-L489

If you use `\AtEndPreamble` to load `hyperref`, you need to ensure `hyperref` is actually loaded *before* this bit of code is executed. One way to do that would be to say `\AtEndPreamble` *before* loading `biblatex` (since `\AtEndPreamble` is just executed in the order it is populated).

```latex
\docuLoremmentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\AtEndPreamble{\usepackage[colorlinks]{hyperref}}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}
\printbibliography
\end{document}
```

If that is not possible in your setup, you have to use `hyperref=manual,` (see https://github.com/plk/biblatex/issues/585 for background, the option was specifically designed for cases like this where you want to load `hyperref` later than `biblatex` can check for, but then some responsibilities are shifted from `biblatex` to you) as in your *case 3*. Note, however, that you need not - and should not - call `\BiblatexManualHyperrefOff` in `\AtEndDocument` when you've already called `\BiblatexManualHyperrefOn` in `\AtEndPreamble`. It will raise a warning
```
Package biblatex Warning: You must call either '\BiblatexManualHyperrefOn'
(biblatex)                or '\BiblatexManualHyperrefOff' exactly once.
(biblatex)                Subsequent calls to either command will be ignored.
```
and will be ignored.
Indeed
```latex
\documentclass{article}
\usepackage{xcolor}
\usepackage{etoolbox}
\usepackage[backend=biber,style=authoryear,hyperref=manual]{biblatex}

\AtEndPreamble{%
  \usepackage[colorlinks]{hyperref}
  \BiblatexManualHyperrefOn
}

\addbibresource{biblatex-examples.bib}

\begin{document}
\section*{test hyperlinks}

\textcite{sigfridsson}

\printbibliography
\end{document} 
```
works fine without the superfluous `\BiblatexManualHyperrefOff`.

**Comment by hushidong** [comment]
ok，I understand that, thanks!

**Comment by moewew** [comment]
I think this can be closed, right? The question seems to have been answered.

If there is anything else (in particular if you can formulate a bug report or a feature request related to this issue), feel free to open a new issue.

**Comment by hushidong** [comment]
ok，question is answered, thanks again!

**Comment by u-fischer** [comment]
With the new hook management in in the next latex version (in october), that can currently be tested by using pdflatex-dev you could set up a rule to ensure that hyperref is loaded before the biblatex code:

~~~~
\AddToHook{env/document/begin}[mydoc/loadhyp]{%
    \usepackage[colorlinks]{hyperref}}

\DeclareHookRule{env/document/begin}{mydoc/loadhyp}{before}{biblatex}
~~~~

**Comment by hushidong** [comment]
ok，I get it ，thank you very much @u-fischer
