### ISSUE TITLE
\citeorder is not updated on second typesetting

### ISSUE THREAD

**Issue by EdwinChan** [plk/biblatex#1035]
I'm using biblatex 3.14 (2019/12/01) with biber 2.14 and LuaHBTeX 1.12.0 (TeX Live 2020).

Consider the following document:

```latex
\documentclass{article}
\usepackage{biblatex}
\begin{filecontents}{\jobname.bib}
@article{A,
  author="Albert Einstein",
  year=1915,
  pages="1--2"
},
@article{B,
  author="Albert Einstein",
  year=1915,
  pages="3--4"
}
\end{filecontents}
\addbibresource{\jobname.bib}
\DeclareSortingTemplate{c}{\sort{\citeorder}}
\ExecuteBibliographyOptions{sorting=c}
\begin{document}
\cite{B}\cite{A}
\printbibliography
\end{document}

```

Typesetting the document yields

> [1, 2]
> 
> References
> [1] Albert Einstein. In: (1915), pp. 1–2.
> [2] Albert Einstein. In: (1915), pp. 3–4.

If I change `\cite{A,B}` to `\cite{B,A}` and typeset again without deleting the temporary files, I obtain

> [2, 1]
> 
> References
> [1] Albert Einstein. In: (1915), pp. 1–2.
> [2] Albert Einstein. In: (1915), pp. 3–4.

which doesn't obey the `\citeorder`. But if I delete the `.aux` file before typesetting, I get the expected result

> [1, 2]
> 
> References
> [1] Albert Einstein. In: (1915), pp. 3–4.
> [2] Albert Einstein. In: (1915), pp. 1–2.

The situation is similar if the pair `\cite{A}\cite{B}` and `\cite{B}\cite{A}` are used instead.

**Comment by moewew** [comment]
Did you run Biber again after you changed the order of citations? If I do that, then I obtain the ouptut I expected. Since Biber does the sorting, it must be run again if you change anything in your document (or `.bib` file) that has influence on the sort order (which is the case here).

**Comment by EdwinChan** [comment]
For what it's worth, if I switch the order, then run `biber` and `latex`, I get the second output above. If instead I run `latex`, `biber`, and `latex` again (which is basically the same as deleting the `.aux` file and starting from scratch), I get the third output.

The sorting template I actually use also considers `author` and `year`. Does it make sense to err on the side of being too cautious and emit a reminder to rerun `biber` if the custom sorting template has `\citeorder` anywhere in it?

**Comment by moewew** [comment]
Oh, yes, sorry. If you switch the order you need to run at least LaTeX, Biber, LaTeX (and ideally LaTeX again to make sure all cross-references resolve correctly). That is because LaTeX needs to write the sort order to the `.bcf` file (the Biber control file), then Biber needs to run and sort the `.bib` file based on the sort order in the `.bcf`, then LaTeX needs to run again to read in the new bibliography data.

If you only run Biber after you change the sort order in the `.tex` file, Biber does not know about that change. That is only possible after the LaTeX run.

It is *not* required to delete the `.aux` file and recompile from scratch in this case. But you may be using a tool that reruns the whole LaTeX, Biber, LaTeX, LaTeX cycle if the `.aux` file is not present and then it may be convenient to delete the `.aux` as a convenient shortcut.

---

> Does it make sense to err on the side of being too cautious and emit a reminder to rerun `biber` if the custom sorting template has `\citeorder` anywhere in it?

I think it does, yes. I'm working on it.

**Comment by moewew** [comment]
A better warning should be issued with https://github.com/plk/biblatex/commit/485ceb0c88f4280b24ce72240a9dad6200b02b3f.

**Comment by moewew** [comment]
`biblatex` 3.15 has been released and is available in both MikTeX and TeX live.

The MWE from above  should now warn about rerunning Biber when the citation order is changed. Hope that makes things a little clearer and easier to use. If there is anything else we can do to make this smoother, please open a new issue.
