### ISSUE TITLE
MacOS 11 (Big Sur) support

### ISSUE THREAD

**Issue by nico-bachner** [plk/biblatex#1052]
Currently, when installing biblatex through tmlgr, I get the following error message:

<img width="565" alt="Screenshot 2020-09-17 at 13 14 36" src="https://user-images.githubusercontent.com/45149421/93463212-bec5f680-f8e7-11ea-8318-e624ea8d2f47.png">

Is this an issue with biblatex or with tmlgr itself?

**Comment by plk** [comment]
I wonder if this is using the non-legacy version - we also have a legacy OSX version (10.5-10.13): 

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/OSX_Intel/biber-darwinlegacy_x86_64.tar.gz/download

**Comment by moewew** [comment]
In any case *`biblatex`* is unlikely to be incompatible with your OS (in a meaningful way). `biblatex` is a LaTeX package and only does fairly standard LaTeX stuff. You only need a reasonably modern TeX engine (with e-TeX extensions) and a working LaTeX format (plus maybe `pdftexcmds`) to run a document using `biblatex`. If that is not available on your OS you have a much bigger problem, since pretty much any modern LaTeX document and package can't be used (so I'd be inclined to say that your OS would not only be incompatible with `biblatex`, it would be incompatible with modern (La)TeX).

The message shown in the screenshot looks like it comes directly from `tlmgr` (a TeX Live system component), so I'd guess the immediate problem is that `tlmgr` (and quite possibly other bits and pieces of your TeX Live/MacTeX version) is not compatible with your OS. That's probably something you'll want to mention at https://tug.org/mailman/listinfo/tex-live or possibly https://email.esm.psu.edu/mailman/listinfo/macosx-tex.

---

Since `biblatex` has its own companion program (Biber) that you'll quite probably want to use, there is the additional complication that Biber needs to be available on your OS. If it's not, that would be something to take up at https://github.com/plk/biber/issues, but that really only makes sense once you have an otherwise working TeX system set up.

**Comment by nico-bachner** [comment]
Ok thank you for the clarification
