### ISSUE TITLE
Biblatex 3.15a \MakeSentenceCase* issue with relatedtype bytranslator

### ISSUE THREAD

**Issue by dfussner** [plk/biblatex#1057]
When using the `bytranslator relatedtype` in a context where the
`titlecase` format is set to `\MakeSentenceCase*{#1}`, the title of the
main entry has its case changed correctly, but in the related entry
the case of the title is not changed. The expl3 and latex2e modules
behave identically.

Here's a MWE:

```
\documentclass[12pt]{article}
\usepackage{fontspec}
\usepackage{csquotes}
\usepackage[french,american]{babel}
\usepackage[style=verbose-inote,backend=biber]{biblatex}
\DeclareFieldFormat{titlecase}{\MakeSentenceCase*{#1}}
\begin{filecontents}[overwrite]{\jobname.bib}
@book{knuth:ct:a,
  author       = {Knuth, Donald E.},
  title        = {The Passing of an Illusion},
  date         = {1984},
  maintitle    = {Computers \& Typesetting},
  related      = {knuth:ct:t},
  relatedtype  = {bytranslator},
  volume       = {A},
  publisher    = {Addison-Wesley},
  location     = {Reading, Mass.}
}
@book{knuth:ct:t,
  author       = {Knuth, Donald E.},
  title        = {The Passing of an Illusion},
  date         = {1984},
  translator   = {Any Name},
  publisher    = {Addison-Wesley},
  location     = {Reading, Mass.}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\thispagestyle{empty}

\noindent\cite{knuth:ct:a}.

\printbibliography
\end{document}
```

And here's what it looks like on my machine:

![mwe15](https://user-images.githubusercontent.com/5174434/95491157-22948a00-0991-11eb-9996-eb32b14378f9.png)

The culprit seems to be the ungrouped `\mkrelatedstring` call when
printing the bibstring inside a `\setunit`. The call expands to
`\mainlang`, which expands to babel's `\setlanguage`, and
`\MakeSentenceCase*` seems to be in a linguistic limbo after that, even
though American should be the language both before and after the
`\setlanguage` call. If I group the `\bibstring` call with an extra set of
braces in the `related:bytranslator` macro it works fine, like so:

`\setunit*{\addspace{\bibstring[\mkrelatedstring]{astitle}}\space}%`

Using an `otherlanguage` environment inside the `\setunit` also works. If
the related entry's `langid` field is explicitly set to `american`, it
works, too.

Many thanks.

**Comment by moewew** [comment]
Thank you very much for reporting this.

I really don't understand why that happens at the moment.

Since `\mkrelatedstring` is defined as `\mainlang`, which in turn is `\selectlangauge{<main document language>}`, I'm wondering if we are seeing the effect mentioned in the `babel` docs
> WARNING If used inside braces there might be some non-local changes, as this would be roughly equivalent to:
> ```latex
>{\selectlanguage{<inner-language>} ...}\selectlanguage{<outer-language>}
>```
>If you want a change which is really local, you must enclose this code with an additional grouping level.

**Comment by dfussner** [comment]
@moewew Yes, it was that very text that made me wonder about grouping the `\mkrelatedstring` call, but I don't understand it, either. I probably should have tried it with `polyglossia` -- is it `babel` specific?

**Comment by dfussner** [comment]
@moewew In case it might be helpful, I did test with `polyglossia` briefly and it seems to work fine, suggesting that there is something specific about `babel's` way of grouping `\selectlanguage` that produces the issue (?).

**Comment by moewew** [comment]
Good to know. Thanks for testing that.

I did some more digging and found that it is a documented quirk of `babel` that the language name stored in `\languagename` has messy catcodes, so the test in

https://github.com/plk/biblatex/blob/316598708aa0847ba962e92d146529391db062ff/tex/latex/biblatex/blx-case-expl3.def#L225-L231

fails sometimes. Something else is off here, since I don't think we should get the language from `\languagename` here, so the grouping is still relevant, but this is also something we need to check out.

**Comment by moewew** [comment]
The examples
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage{xcolor}

\appto\extrasfrench{\color{red}FR}
\appto\extrasbritish{\color{blue}GB}

\appto\noextrasfrench{\color{yellow}NFR}
\appto\noextrasbritish{\color{green}NGB}

\begin{document}
ALorem \languagename

{\selectlanguage{french} ipsum \languagename}

BLorem \languagename

{\selectlanguage{british} dolor \languagename}

CLorem \languagename
\end{document}
```
and
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage{xcolor}

\appto\extrasfrench{\color{red}FR}
\appto\extrasbritish{\color{blue}GB}

\appto\noextrasfrench{\color{yellow}NFR}
\appto\noextrasbritish{\color{green}NGB}

\begin{document}
ALorem \languagename

{{\selectlanguage{french} ipsum \languagename}}

BLorem \languagename

{{\selectlanguage{british} dolor \languagename}}

CLorem \languagename
\end{document}
```
show that we indeed need two pairs of braces for `\selectlanguage`. That means that all uses of `\mkrelatedstring` need two pairs of braces.

I'm not quite sure how to best solve this on the `biblatex` side. Ideally I'd turn `\mkrelatedstring` (and with it `\mainlang`) from a switch into a 'text macro'. But (at least for `\mainlang`) this would be against documented behaviour and would require adjustment in quite a few custom styles (your `biblatex-chicago`, `biblatex-iso`, `biblatex-gb7714-2015`, `biblatex-gost`, `biblatex-oxref`, `biblatex-ext`).

**Comment by moewew** [comment]
https://github.com/plk/biblatex/commit/b08d5cdd38e99cd8fbe05133d8d4c8f969b6f358 addresses one weirdness uncovered by all this: `babel`'s `\languagename` has very odd catcodes. We sprinkle in some `\detokenize`s to avoid the issue.

In my tests this commit made your MWE produce the desired output, **but** the real issue (`\selectlanguage` needs two groups for fully local effect) is not resolved by this. (That still needs some thought, see my comment above.)

**Comment by moewew** [comment]
https://github.com/plk/biblatex/compare/dev...moewew:mainlang shows how I would like to tackle the underlying issue here.

If we stick with https://github.com/moewew/biblatex/commit/e67743ee392e41772bf39c15dce0c25cc2551b23, then a number of styles would have to be adjusted, because the syntax of the command changes from a switch to a real macro. We could think about deprecating `\mkrelatedstring` as well and picking a new name (the thing is that the new name would probably sound odd or artificial). Then we could fix the problem on our side (and could encourage style authors to do the same thing) while not simultaneously breaking all contributed styles.

@dfussner Since your style would be one of the most affected styles I'd love to hear your thoughts.

**Comment by moewew** [comment]
Given that so many styles would be affected, it is probably safer to deprecate `\mkrelatedstring` in favour of a new macro that works properly, but retain it with its original definition to avoid breaking all those styles. This is now implemented in https://github.com/moewew/biblatex/commit/033964119d8b2bed2623cddd15dcc5cfce8b80e1.

The full changes in the suggested branch are still at https://github.com/plk/biblatex/compare/dev...moewew:mainlang.

Comments are very welcome. As always I'm not too happy about my names, so if you have any suggestions for better names, I'd love to hear them.

**Comment by dfussner** [comment]
@moewew Many thanks for this. As far as I've tested it all works great. b08d5cd already fixes the output of my test cases, without any changes in my own code. Switching to `\mkrelatedstringtext` in that code works fine, and also eliminates the warning in my log files. I think the names of the replacement macros are good, well in keeping with the naming style in `biblatex` generally, and not difficult for us style authors to update. I'll continue testing this, but I think you can label it fixedindev now.

**Comment by moewew** [comment]
OK I merged the suggested changes into `dev` in https://github.com/plk/biblatex/commit/f5a096a6395e274b3af9d01d5fb4aecddeff138d. `\mkrelatedstring` is deprecated now and `\mkrelatedstringtext` should be used instead.

Note that `\mkrelatedstringtext{<text>}` takes the text as argument and is not a switch like `\mkrelatedstring`.

Uses of the form
```latex
\bibstring[\mkrelatedstring]
```
can simply be changed to
```latex
\bibstring[\mkrelatedstringtext]
``` 
but
```latex
\begingroup
\mkrelatedstring%
\lbx@initnamehook{#1}%
\endgroup
```
needs to be converted to
```latex
\mkrelatedstringtext{\lbx@initnamehook{#1}}%
```

If backwards compatibility is desired, one can define
```latex
\providecommand*{\mkrelatedstringtext}[1]{{{\mainlang #1}}}
```

---

I notified the developers of `biblatex-gb7714-2015` (https://github.com/hushidong/biblatex-gb7714-2015/issues/80), `biblatex-gost` (https://github.com/odomanov/biblatex-gost/issues/27), `biblatex-oxref` (https://github.com/alex-ball/biblatex-oxref/issues/12). @dfussner Since you already know about the change I haven't sent you an email, but if you'd like me to, so you can put this on your to-do list, I can certainly do that.

**Comment by dfussner** [comment]
@moewew No need for the email, your heads-up was enough. Thanks again for sorting this out.

**Comment by moewew** [comment]
`biblatex` v3.16 with the fix for this issue was released on 31 Dec 2020 and is available now in TeX live and MikTeX.

The MWE now gives the desired result. Fingers crossed that the changes don't mess contributed styles. Hopefully there was enough lead-up time for style developers. At least in theory the changes should be fully backwards compatible, so the only issue for end-users should be undesirable warnings.
