### ISSUE TITLE
loccit translation error in german.lbx

### ISSUE THREAD

**Issue by chengler** [plk/biblatex#1074]
german.lbx uses the same translation for opcite und loccit. But loccit (same author/book, same page) should be 

> ebd.

```
 opcit            = {{a.\,a.\,O\adddot}{a.\,a.\,O\adddot}},
 loccit           = {{ebd\adddot}{ebd\adddot}},
```

**Comment by moewew** [comment]
Thank you for reporting this issue.

I thought 'ebd.' is only used if the citation is the same as the previous citation. If that is correct., the "ebd." in
```latex
\documentclass[ngerman]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=verbose-trad1]{biblatex}

\DefineBibliographyStrings{german}{
  opcit   = {a.\,a.\,O\adddot},
  loccit  = {ebd\adddot},
}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite[380]{sigfridsson}
ipsum \autocite[12]{worman}
dolor \autocite[381]{sigfridsson}
sit \autocite[12]{worman}
amet \autocite[381]{sigfridsson}

\printbibliography
\end{document}
```
would be slightly unusual.

It is very possible that there are different conventions in different fields with regards to the finer details of "a.a.O."/"ebd."/loc. cit/op. cit., so I would be interested in seeing examples or style guides explaining this usage.

In any case I'm not sure whether we can change the translations here unless there is overwhelming evidence that the status quo is wrong. People might rely on the current behaviour (and if it is not objectively wrong or against what is documented) might understandably be unhappy about changes here. (Though I will admit that these translations are probably a niche market.) Compare also https://github.com/plk/biblatex/issues/774.

@jspitz do you have an opinion here as our resident German contributor?

**Comment by jspitz** [comment]
Yes, usually `ebd.` equals `ibid.`, whereas `a.a.O.` equals `loc. cit.` (but surely conventions are variable). See:
https://de.wikipedia.org/wiki/Ebenda

In my interpretation, both. `op. cit.` and `loc. cit.` should be localised as `a.a.O.` (though I do not use these abbreviations in my own work).

**Comment by chengler** [comment]
There are different conventions. Therefore `loccittracker`  has different possibilities. 
In default the output is always `op. cit.`localised as  ` a. a. O.` 
`loccittracker=constrict` differs  between `op. cit.` and` loc. cit.`  Then `loccit` has to be redefined to `ebd.`
So translating `loc. cit.` to `ebd.` does not cause problems in the field, but makes Biblatex better.

This is  the convention of my department 

`ebd.` equals `loc. cit.` equals `ibi­dem` it is  used for 

> same author, same book, same page(!)

`op. cit. page number `equals `a.a.O. page number` it is  used for 

> same author, same book, different page(!)

And it makes a lot of sense.` a. a. O.` means freely translated `at an other place`. This is different to `ibi­dem`.

btw. german wikipdia is a bit superficial in the beginning: `ebd.` is not `op. cit.` but `loc. cit`. (It is similar of course)
better is https://en.wikipedia.org/wiki/Op._cit. 
`Op. cit.` eq. `opus citatum` eq `the work cited`
`Loc. cit.`  eq.` loco citato` eq. `in the place cited`
Well, sometimes `ebd.` is used like `op. cit`. People do other harsh things. But LaTex is used for the fine differences, isn't it.

**Comment by chengler** [comment]
`loc. cit.` equals `ebd.` equals `ibid.` whereas
`op. cit.`  equals `a.a.O.`

**Comment by moewew** [comment]
I probably misunderstand, but the example I posted above shows that `biblatex`'s `verbose-trad1`  style uses *loc. cit.* and *op. cit.* (and also *ibid.*)
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=verbose-trad1]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite[380]{sigfridsson}
ipsum \autocite[12]{worman}
dolor \autocite[381]{sigfridsson}
sit \autocite[12]{worman}
amet \autocite[381]{sigfridsson}
consectur \autocite[381]{sigfridsson}
lorem \autocite[12]{worman}
ipsum \autocite[382]{sigfridsson}
dolor \autocite[383]{sigfridsson}

\printbibliography
\end{document}
```
(the style sets `loccittracker=context,`).

So if we were to change the translations of `opcit` and/or `loccit`, this example would look different. This may be a problem for people who rely on the current behaviour.

As the example shows, *op. cit.*, *loc. cit.* and *ibid.* can all appear in the same style with different meanings/semantics. I understand that the current German translations do not account for all subtleties of that distinction, but at the moment I'm not convinced that the current German translations are objectively wrong or misleading. I'm also not convinced that changing the translation of `loccit` to 'ebd.' would make things better for the average user: All uses of 'ebd.' I know of only ever refer to the last citation (i.e. the one before this one) and not to possibly (much) earlier citations of the same work.

(There is a broader point here: If there are different conventions, `biblatex` may sometimes have to choose one of those conventions as its default. Then there have to be very compelling arguments to justify a switch to a different convention later on: After all, people might rely on the old convention. That is especially true if it is easy enough to switch to a different convention via some settings/options/.....)

----

I'm a bit confused by your edit.

At least for `biblatex` 'ebd.' and 'ibid.' are the same ('ebd.' is the German translation of the bibstring `ibidem`, which uses the Latin 'ibid.' in English), they are usually controlled by `\ifciteibid`. 'op. cit.' is controlled by `\ifopcit` and 'loc. cit' is controlled by `\ifloccit` (at least in `verbose-trad1`). These three tests are not independent of each other (`\ifciteibid` implies `\ifopcit`, I think), but it is possible to get at least three different configurations out of them.

Again, it is very possible that there are different conventions (I can imagine German conventions where 'ibid.' and 'ebd.' mean different things, there are Italian conventions that differentiate between 'ibid.' and 'ivi', https://tex.stackexchange.com/q/560415/35864, https://tex.stackexchange.com/q/418701/35864), but unless there is good evidence that what `biblatex` does here currently is wrong, I don't want to change things just to align it with the requirements of a particular department. It is always possible that `biblatex`'s default give your exactly what you need, but that's why `biblatex` is customisable: It should make it easy for you to get the output you want.

**Comment by chengler** [comment]
To start with the edit: this was my mistake:  'ebd.' and 'ibid.' are the same.
Well, I really dislike the outcome 6 `Ibid., p. 381` and hope that I am never forced to use `style=verbose-trad1`. But a style is a style an there is no wrong in taste.
Even in the example I think `loc. cit.` would be better translated to `ebd.`. But it is to late now. It is certainly more importend to keep backward compatibility.

**Comment by moewew** [comment]
Alright. I'm closing this as 'won't fix' for now.

At the moment I'm not convinced that the status quo of the German translations of the terms discussed here is objectively wrong or that it goes against *all* common practices. There may be conflicting conventions here and to some degree it might be a matter of taste. For now I don't think this warrants a backwards incompatible change (which is certainly not impossible, but needs good arguments).
