### ISSUE TITLE
Bibhang depends on font in preamble

### ISSUE THREAD

**Issue by samcarter** [plk/biblatex#1079]
If a document uses  a `\parindent` of 0, the `\bibhang` is set to 1em, which makes it dependant on the font size used at the load time of biblatex, not the font used for the bibliography. Is this by design?

```
\documentclass{article}

\setlength{\parindent}{0pt}

\Huge % try with and without to see the effect

\usepackage[style=authortitle]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}

  test 
  \nocite{knuth:ct:a}
  \printbibliography

\end{document}
```

(related beamer issue: https://github.com/josephwright/beamer/issues/645)

**Comment by moewew** [comment]
I don't think this effect is intentional, but I'm also not sure if we can change things without breaking people's stuff.

The underlying problem is already discussed in https://github.com/plk/biblatex/issues/848, but we didn't really get to resolving the issue. I think I still have to code solving the issue lying around here, but I'm not sure if we should merge it.

**Comment by samcarter** [comment]
@moewew  Thanks a lot for the link to the duplicate!
