### ISSUE TITLE
warning "Package biblatex Warning: Bibliography string 'idemdat' untranslated" 

### ISSUE THREAD

**Issue by kromuchi** [plk/biblatex#1084]
I get the warning "Package biblatex Warning: Bibliography string 'idemdat' untranslated" for an inbook entry where author and editor are the same (hence the same hash is generated). Unfortunately I can't find anything in the documentation. I was hoping to define a string with \DefineBibliographyStrings{german}{idemdat = {ebendem}}, but this doesn't work.

Is this a bug or is there some documentation missing?

Package: biblatex 2020/08/23 v3.15a with miktex / biber64

**Comment by moewew** [comment]
Would it be possible to share an example document and a `.bib` entry where this problem occurs (an MWE: https://tex.meta.stackexchange.com/q/228/35864)?

All I can say now is that there is indeed no string named `idemdat` in the standard `biblatex` styles. (That's why it won't work to just translate the string in `\DefineBibliographyStrings`, because it doesn't exist, it would first have to be declared with `\NewBibliographyString`.)

The *idem* strings are called as

https://github.com/plk/biblatex/blob/9f5f39693bee35f9f714758f429490467460b34c/tex/latex/biblatex/cbx/verbose-trad1.cbx#L139-L141

So this phenomenon could be explained if you for some reason have
```
gender = {at},
```
in the offending entry. This would be unexpected and contrary to the advice in the documentation, which says that `gender` is a field, whose contents should be 
> [a] Pattern matching one of: `sf`, `sm`, `sn`, `pf`, `pm`, `pn`, `pp`
>
> The gender of the author or the gender of the editor, if there is no author. The following identifiers are supported: `sf` (feminine singular, a single female name), `sm` (masculine singular, a single male name), `sn` (neuter singular, a single neuter name), `pf` (feminine plural, a list of female names), `pm` (masculine plural, a list of male names), `pn` (neuter plural, a list of neuter names), `pp` (plural, a mixed gender list of names).
> This information is only required by special bibliography and citation styles and only in certain languages. For example, a citation style may replace recurrent author names with a term such as ‘idem’. If the Latin word is used, as is custom in English and French, there is no need to specify the gender. In German publications, however, such key terms are usually given in German and in this case they are gender-sensitive.

**Comment by kromuchi** [comment]
It took me a while to create a MWE, and I don't know if it's really "minimal", especially since it depends on a specific bbx and cbx file and I am not so familiar with these and hence can't decide what is relevant and what's not.

Here is my MWE using biber:
[MWE.tex.txt](https://github.com/plk/biblatex/files/5691780/MWE.tex.txt)

I just realized that removing `\DeclareLanguageMapping{ngerman}{german}` in the MWE and using

 ```
\NewBibliographyString{%
    ibidemp,%
}
\DefineBibliographyStrings{german}{%
	bibliography = {Literaturverzeichnis},
	backrefpage  = {Zitiert auf Seite},
	backrefpages = {Zitiert auf Seiten},
	ibidem           = {ebd\adddot},
	ibidemp          = {{a\adddot}{a\adddot}{O\adddot}},
	idemdat          = {dems\adddot},
}
```

solves the issue in this MWE, but understanding this is out of my scope :(

**Comment by moewew** [comment]
Hmm, from the code it is really not clear to me where `idemp` and `idemat` come from. They are neither present in standard `biblatex` nor in `biblatex-dw`, so they must be original to your style.

You've already identified the issue and I would say the line that is at fault is
```latex
\DeclareLanguageMapping{ngerman}{german}
```
The documentation has the following to say about `\DeclareLanguageMapping`
> Note that `\DeclareLanguageMapping` is not intended to handle language variants (e.g., American English vs. British English) or `babel`/ `polyglossia` language aliases (e.g., `USenglish` vs. `american`). [...] In contrast to that, the point of `\DeclareLanguageMapping` is handling stylistic variants like ‘humanities vs. natural sciences’ or ‘mla vs. apa’ etc. which will typically be built on top of existing `.lbx` files.

The problem with that line is that it tells `ngerman` to get its strings from `german`. When you later redefine the strings for `german`, those strings have already been loaded for `ngerman` and the changes to `german` are not applied/propagated to their copies in `ngerman`. That's why
```latex
\DeclareLanguageMapping{ngerman}{german}

\NewBibliographyString{%
  ibidemp,
  idemdat,
}

\DefineBibliographyStrings{ngerman}{%
	bibliography = {Literaturverzeichnis},
	backrefpage  = {Zitiert auf Seite},
	backrefpages = {Zitiert auf Seiten},
	ibidem           = {ebd\adddot},
	ibidemp          = {{a\adddot}{a\adddot}{O\adddot}},
	idemdat          = {dems\adddot},
}
```
would also work.

The correct solution I'd say is dropping `\DeclareLanguageMapping{ngerman}{german}` and using just
```latex
\NewBibliographyString{%
  ibidemp,
  idemdat,
}

\DefineBibliographyStrings{german}{%
	bibliography = {Literaturverzeichnis},
	backrefpage  = {Zitiert auf Seite},
	backrefpages = {Zitiert auf Seiten},
	ibidem           = {ebd\adddot},
	ibidemp          = {{a\adddot}{a\adddot}{O\adddot}},
	idemdat          = {dems\adddot},
}
```

**Comment by kromuchi** [comment]
FYI, the stringt `ibidemp` and `idemdat` are created by the package `biblatex-dw` (package of `authortitle-dw`)

**Comment by moewew** [comment]
Oh, yes, I had missed the second `d` in `idemdat`, sorry about that. But I still can't find `ibidemp` ...
