### ISSUE TITLE
type, nottype, subtype, notsubtype options for \printbiblist do not work if skipbib entry option is set

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#1086]
If a bib entry has `options = {skipbib}` then passing `type`, `nottype`, `subtype`, or `notsubtype` to `\printbiblist` does not work.

Consider the following MWE. Both the bibliography and the list of shorthands should be empty, but the list of shorthands is printed. If the bib entry does not contain `options = {skipbib}` then the list of shorthands is empty (but the bibliography is not empty of course).

```TeX
\documentclass{article}
\begin{filecontents}[overwrite]{\jobname.bib}
@book{test,
  shorthand = {AT},
  author = {Author},
  title = {Title},
  date = {2021},
  options = {skipbib}
}
\end{filecontents}
\usepackage{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\cite{test}
\printbibliography
\printbiblist[nottype=book]{shorthand}
\end{document}
```

**Comment by moewew** [comment]
The problem here seems to be that type filtering (both in the normal bibliography and in biblists) uses the list `blx@type@<refsection>@<type>`.

An entry is only added to that list if `skipbib=false,`

https://github.com/plk/biblatex/blob/ca032db14c25fcad84a75ce5f43ba59c39ac69f2/tex/latex/biblatex/biblatex.sty#L8287-L8302

@plk How independent are the bibliography (`\datalist[entry]`) and biblists (`\datalist[list]`) in terms of entries that might appear in the lists and actual data? Can an entry appear in `\datalist[list]` but not in `\datalist[entry]`?

Since I expect the all `\datalist[list]` entries to have a corresponding `\datalist[entry]` entry with essentially the same data, I'd probably go for something like the following that always only takes the entry data from the `\datalist[entry]`
```latex
\documentclass{article}
\usepackage{biblatex}

\makeatletter
\protected\def\blx@bbl@endentry{%
  \csuse\blx@bbl@data
  \ifcsundef{blx@pref@\the\c@refsection @\abx@field@entrykey}
    {}
    {\blx@addpageref{\abx@field@entrykey}}%
  \nottoggle{blx@setonly}
    {}
    {\global\toggletrue{blx@addset}%
     \toggletrue{blx@skipbib}%
     \toggletrue{blx@skipbiblist}%
     \toggletrue{blx@skiplab}}%
  \expandafter\ifstrequal\expandafter{\blx@dlist@type}{entry}
    {\listcsxadd{blx@type@\the\c@refsection @\abx@field@entrytype}{\abx@field@entrykey}%
     \ifdef\abx@field@entrysubtype
       {\listcsxadd{blx@subt@\the\c@refsection @\abx@field@entrysubtype}{\abx@field@entrykey}}
       {}%
     \nottoggle{blx@skipbib}
       {\listcsxadd{blx@dlist@entry@\the\c@refsection @\blx@dlist@name}{\abx@field@entrykey}%
        \listcsxadd{blx@dlist@centry@\the\c@refsection @\blx@dlist@name}{\abx@field@entrykey}}
       {}}%
    {}%
  \nottoggle{blx@skipbiblist}
    {\expandafter\ifstrequal\expandafter{\blx@dlist@type}{list}
      {\blx@bbl@labelfields
        \listcsxadd{blx@dlist@\blx@dlist@type @\the\c@refsection @\blx@dlist@name}{\abx@field@entrykey}}
      {}}%
    {}%
  \nottoggle{blx@skiplab}
    {\iftoggle{blx@labelnumber}
       {\blx@bbl@labelnumber}
       {}%
     \iftoggle{blx@labelalpha}
       {\blx@bbl@labelalpha}
       {}%
     \iftoggle{blx@labeltitle}
       {\blx@bbl@labeltitle}
       {}%
     \iftoggle{blx@labeltitleyear}
       {\blx@bbl@labeltitleyear}
       {}%
     \iftoggle{blx@labeldateparts}
       {\blx@bbl@labeldate}
       {}%
     \blx@bbl@labelname}
    {}%
  \blx@bbl@titles
  \blx@bbl@hooks
  \endgroup}
\makeatother

\begin{filecontents}{\jobname.bib}
@book{test,
  shorthand = {AT},
  author    = {Author},
  title     = {Title},
  date      = {2021},
  options   = {skipbib}
}
@book{testA,
  shorthand = {BT},
  author    = {Author},
  title     = {Title},
  date      = {2022},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{test,testA}
\printbibliography
\printbiblist[nottype=book,title=A]{shorthand}
\printbiblist[title=B]{shorthand}
\end{document}
```
But if in theory `\datalist[entry]` and `\datalist[list]` are independent, then we'd have to generate two different lists.

While going through this I realised that the `blx@type@<refsection>@<type>` are only per refsection and don't take refcontexts into account. Should they?

**Comment by plk** [comment]
Data in bibliographies (`entry` lists) and bibliography lists (`list` lists (!)) should be the same in the sense that every both sort of `datalist` have an item referring to every mentioned reference in the refcontext and so I think what you suggest should fix things - looks like a clear bug to me. Feel free to merge and we can see if the new github automated tests pick up any issues ...

refsections are data-centric, refcontexts are, so to speak, data presentation-centric and since `type` is a data property rather than a data presentation property like sorting, label format etc. I don't think we need to make the type tracking lists refcontext-specific as they would always contain the same things.

**Comment by moewew** [comment]
OK, pushed https://github.com/plk/biblatex/commit/813466f41a08ef1191d44c202a987655d1dd478f. @dcpurton Testing would be appreciated.

**Comment by dcpurton** [comment]
@moewew this works in my test file.

(This is from a rewritten version of `biblatex-sbl` not available online yet).

```TeX
\documentclass{article}
\input{regression-test}
\usepackage{fontspec}
\setmainfont{Brill}
\usepackage[style=sbl]{biblatex}
\addbibresource{biblatex-sbl.bib}
\pagestyle{empty}
\raggedright
\frenchspacing
\begin{document}
\START
\showoutput
\volcite{36}[(4.19)128c]{gregory:orationestheologicae}

\cite*[(4.19)]{gregory:orationestheologicae}

\volcite{18}[(2.4)52c]{methodius:symp}

\cite*[(2.4)]{methodius:symp}

\nocite{PL}
\printbibliography
\printbibheading[title=Abbreviations]
\printbiblist[heading=subbibliography, title=Primary Sources,
  type=ancienttext]{abbreviations}
\printbiblist[heading=subbibliography, title=Secondary Sources,
  nottype=ancienttext]{abbreviations}
\end{document}
```

![biblatex-sbl_6 4 6](https://user-images.githubusercontent.com/6268044/103612587-b1a34500-4f74-11eb-8b36-1418d460ba39.png)

**Comment by moewew** [comment]
Thanks!

**Comment by moewew** [comment]
`biblatex` 3.17 with the fix for this issue has been released and is available in both MikTeX and TeX live now.
