### ISSUE TITLE
Change \finalhyphendemerits in the bibliography?

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1092]
`\finalhyphendemerits` sets how bad a hyphen in the last but one line is. It has a rather large value by default. It can cause TeX to force an additional line to avoid the demerits. I don't think that this makes much sense in a bibliography with lots of short paragraphs and probably many hyphenations and would suggest to set it too zero there.

For an example where it kicked in see 
https://tex.stackexchange.com/a/577902/2388

**Comment by moewew** [comment]
That doesn't sound unreasonable, but I'm wondering how many users would be affected by a change here and how unhappy they would be about different line breaks...

The suggested change (https://github.com/moewew/biblatex/commit/9590a5a6e9b2e08d595d260f88e4b0f479af4363) affected four files in our test suite. So it doesn't appear too unlikely that people would see changes in their documents.

E.g. in `16-numeric-prefixed-1`

**before**
![Higher-Dimensional Algebra V: 2-//Groups.](https://user-images.githubusercontent.com/6755835/103907553-b21d1680-5101-11eb-89f8-5353899b1f42.png)
and
![grafik](https://user-images.githubusercontent.com/6755835/103907797-0627fb00-5102-11eb-8085-59b989cf3661.png)


**after**
![Higher-Dimensional Algebra V://2-Groups.](https://user-images.githubusercontent.com/6755835/103907575-b9dcbb00-5101-11eb-8545-ffbeec76049d.png)
and
![grafik](https://user-images.githubusercontent.com/6755835/103907778-fdcfc000-5101-11eb-898a-018d05a8e857.png)


I might just be subconsciously biased against the change because in these cases I think the "before" result looks nicer.

**Comment by u-fischer** [comment]
> I might just be subconsciously biased against the change because in these cases I think the "before" result looks nicer.

Well the value is so high by default because it is normally nicer  ;-)  (but in the second example I prefer the after version, I don't like hyphenations Be- and Re- after two chars very much, and in the first the input should use a non-breakable hyphen). 

Imho it is as with url breaks: the typesetting of the bibliography is so challenging that trying to be too nice can lead to bad side effects.

But yes, it would affect users. So perhaps an option and some documentation about the issue?

**Comment by moewew** [comment]
We could introduce a customisable `\bibfinalhyphendemerits`, but then it would probably not be much harder to just say
```latex
\preto\bibsetup{\finalhyphendemerits=0 }
```
in the documents than say
```latex
\defcounter{bibfinalhyphendemerits}{0}
```
Cf.
```latex
\documentclass[11pt]{article}

\usepackage[left=1.25in,right=1.25in]{geometry}
\usepackage{showframe}

\usepackage[backend=biber,
        style=chem-rsc,
        doi=true,
        articletitle=true,
        pageranges=true,
        biblabel=dot,
        url=true,
        chaptertitle=true
        ]{biblatex}


\DeclareFieldFormat{doi}{%
  \hfil\penalty50\hfilneg\space
  DOI\addcolon\addnbspace
  \ifhyperref
    {\href{https://doi.org/#1}{\nolinkurl{#1}}}
    {\nolinkurl{#1}}}

\preto\bibsetup{\finalhyphendemerits=0 }

\begin{filecontents}{\jobname.bib}
@Article{Janiak2010,
  author    = {Aakeroy, Christer B. and Champness, Neil R.  and Janiak, Christoph},
  title     = {Recent advances in crystal engineering},
  journal   = {CrystEngComm},
  year      = {2010},
  volume    = {12},
  pages     = {22--43},
  doi       = {10.1039/B919819A},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

`biblatex.def` already has a discussion about some penalties when it defines `\bibsetup`

https://github.com/plk/biblatex/blob/4c0a029acf7c226daacf381957c65df1178cca49/tex/latex/biblatex/biblatex.def#L210-L253

we could add something there.

**Comment by moewew** [comment]
As I say, I'm too scared to change the defaults, so the comments in https://github.com/plk/biblatex/commit/eeae027fdda9b5d278712159d75bdc83f7fa96f8 are the next best thing I can offer.
