### ISSUE TITLE
add option to print title in italics

### ISSUE THREAD

**Issue by dkwo** [plk/biblatex#1095]
Would it be possible to have a simple option to print references' titles in bibliography in italics, instead of within quotation marks?
Right now I'm using
```
\DeclareFieldFormat
  [article, inbook, incollection, inproceedings, patent, thesis, unpublished]
  {title}{\it #1 \isdot}
```
but a simple option at the `\usepackage` level would be better.

Incidentally, for unpublished papers (e.g. arXiv), I'd like to remove the 'In:' that is printed. I achieve that with `\renewbibmacro{in:}{}`, but again it would be simper to have an option as above.
Thanks.

**Comment by moewew** [comment]
It is probably better to use
```latex
\DeclareFieldFormat
  [article, inbook, incollection, inproceedings, patent, thesis, unpublished]
  {title}{\mkbibitalic{#1\isdot}}
```
or `\mkbibemph` instead of `\mkbibitalic`. `\it` has been deprecated for more than 25 years (https://www.texfaq.org/FAQ-2letterfontcmd).

`biblatex` has quite a number of options already. Adding options to influence the typesetting of titles (or other fields) would lead to a combinatoric explosion of options. (Incidentally, I'm not sure how we could properly implement all the things that `\DeclareFieldFormat` can do as an option.) Options are nice for basic things, but I think there comes a point where the level of customisation you want simply can't be properly expressed with options.

---

If you have an unpublished paper on the arXiv, use the type `@online`. Then you won't get to see any "in:". `@article` should be reserved for papers actually published in a bona fide journal. See also https://tex.stackexchange.com/q/415115/35864.

**Comment by dkwo** [comment]
I see, many thanks.
