### ISSUE TITLE
Capitalized non-dropping particles

### ISSUE THREAD

**Issue by larsgw** [plk/biblatex#1097]
Sorry if this is not the right place to ask about this. With natbib it is possible to have non-dropping particles (i.e. the "von" part/the prefix) that are capitalized by wrapping the capital letter in braces:

```bibtex
@book{label,
  author = "First {V}on Last"
}
```

In the `apalike` style the names printed with a comma producing:

> Von Last, F.

However, the same source file in biblatex (`style=apa`) produces:

> Last, F. V. (n.d.).

Is this an intended difference? If so, is there a way to ensure `Von` comes in front of `Last`?

**Comment by moewew** [comment]
Braces are a bit tricky, because they have so many different meanings for BibTeX, so I generally recommend you avoid them as much as possible.

With `biblatex` there are at least two ways to get a "von" to stick to a name.

If the "Von" is capitalised in the name, use the inverted input format
```
author = {Von Last, First},
```
to explicitly tell it that the last name is "Von Last".

If the "Von" is not usually capitalised but should still stick to the family name, use the option `useprefix`
```
author  = {First von Last},
options = {useprefix=true},
```
It can be set on global or per-entry level.

The first method also works for BibTeX
```latex
\documentclass[american]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=apa]{biblatex}

\begin{filecontents}{\jobname.bib}
@book{vlf,
  author    = {Von Last, First},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
}
@book{vlf:up,
  author    = {First von Last},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
  options   = {useprefix=true},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem \autocite{vlf}

ipsum \autocite{vlf:up}

\printbibliography
\end{document}
```

**Comment by larsgw** [comment]
> If the "Von" is capitalised in the name, use the inverted input format
> ```
> author = {Von Last, First},
> ```

Thank you, I don't know why I didn't realize that that would produce the same output. :man_facepalming:
