### ISSUE TITLE
Localization does not follow the currently selected language

### ISSUE THREAD

**Issue by Witiko** [plk/biblatex#1108]
[BibLaTeX documentation][1] says (emphasis mine):

>  By default biblatex automatically picks up *the active surrounding language* from the babel/polyglossia package (and fall back to English if babel/polyglossia is not available).

However, the following MWE (see also [Overleaf playground][2]) shows that biblatex follows the main language of babel (czech), not the active surrounding language (english) as evidenced by the Czech text "Dostupné z DOI" in the output:

``` tex
\documentclass{article}

\begin{filecontents}[noheader]{main.bib}
@article{tex:zpravodajchlebikova91eng,
  author = {Chlebíková, Jana},
  title = {Ako rozděliť (slovo) Československo},
  journal = {Zpravodaj CSTUG},
  volume = 1,
  number = 4,
  year = 1991,
  month = April,
  pages = 10-13,
  doi = {10.5300/1991-4/10},
}
\end{filecontents}

\usepackage[main=czech,english]{babel}
\usepackage[style=iso-numeric]{biblatex}
\addbibresource{main.bib}

\begin{document}

\selectlanguage{english}

\nocite{*}
\printbibliography

\end{document}
```

![BibLaTeX_ISO_690__Switching_languages__MWE_](https://user-images.githubusercontent.com/603082/110317910-162e5f00-800d-11eb-9530-e6782ba48df0.png)

This becomes an issue in document classes such as [csbulletin][3], where babel's main language is selected in the document class and the user can only switch the active language, not the main language. Closing this issue also closes https://github.com/michal-h21/biblatex-iso690/issues/90.

 [1]: https://mirror.kumi.systems/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf#page=49
 [2]: https://www.overleaf.com/read/hkshdtvzkyhs
 [3]: https://www.ctan.org/pkg/csbulletin

**Comment by moewew** [comment]
That is because `biblatex-iso690` explicitly uses `\mainlang` (now deprecated in favour of `\textmainlang`) to print some strings in the main document language.

I guess you are expecting those strings to be printed in the 'last user-selected' language, i.e. in the active language before `biblatex` started meddling with languages itself. This is conceptually a bit trickier, but there is a first attempt at https://github.com/plk/biblatex/commit/933003cfcecf2ce81b946481849f292461ee6484. Please give it a spin (for example in the following example with a hacked version of `biblatex-iso690` that now uses `\textouterlang` instead of `\textmainlang`/`\mainlang`)

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[main=czech,english,ngerman]{babel}
\usepackage[style=iso-numeric]{biblatex}

\makeatletter
\protected\def\blx@mainlangbibstring#1#2#3{%
  \blx@begunit
  \blx@hyphenreset
  \blx@bibstringsimple
  \lowercase{\edef\blx@tempa{#3}}%
  \ifcsundef{#2@\blx@tempa}
    {\blx@warn@nostring\blx@tempa
     \blx@endnounit}
    {\blx@imc@ifcapital
       {\textouterlang{#1{\MakeCapital{\csuse{#2@\blx@tempa}}}}}
       {\textouterlang{#1{\csuse{#2@\blx@tempa}}}}%
     \blx@endunit}}
\makeatother

\begin{filecontents}[force]{\jobname.bib}
@article{tex:zpravodajchlebikova91,
  author  = {Chlebíková, Jana},
  title   = {Ako rozděliť (slovo) Československo},
  journal = {Zpravodaj CSTUG},
  volume  = 1,
  number  = 4,
  year    = 1990,
  month   = {04},
  pages   = {10-13},
  doi     = {10.5300/1991-4/10},
  note    = {no laingid},
}
@article{tex:zpravodajchlebikova91cz,
  author  = {Chlebíková, Jana},
  title   = {Ako rozděliť (slovo) Československo},
  journal = {Zpravodaj CSTUG},
  volume  = 1,
  number  = 4,
  year    = 1991,
  month   = {04},
  pages   = {10-13},
  doi     = {10.5300/1991-4/10},
  langid  = {czech},
  note    = {Czech langid},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\nocite{*}

\begin{document}
\printbibliography

\selectlanguage{english}
\printbibliography

\selectlanguage{ngerman}
\printbibliography
\end{document}
```

![vol. 1, no. 4, pp. 10–13. Available from doi: 10.5300/1991-4/10.](https://user-images.githubusercontent.com/6755835/110435114-e5086a00-80b2-11eb-850a-531753f3f62a.png)

**Comment by Witiko** [comment]
@moewew Thanks for the speedy response!

> I guess you are expecting those strings to be printed in the 'last user-selected' language, i.e. in the active language before `biblatex` started meddling with languages itself.

That is what I would expect, since it seems sane and BibLaTeX documentation promises it.   
See also https://github.com/michal-h21/biblatex-iso690/issues/90.

> there is a first attempt at 933003c. Please give it a spin

I installed BibLaTeX to a temporary texmf tree:

``` bash
$ mkdir texmf
$ git clone https://github.com/plk/biblatex.git
$ pushd biblatex/
$ obuild/build.sh install dev ../texmf
$ popd
```

Then, I patched and installed biblatex-iso690. Here, I get an error when typesetting the biblatex-iso690 documentation:

``` bash
$ git clone https://github.com/michal-h21/biblatex-iso690.git
$ pushd biblatex-iso690/
$ sed -i 's/\\mainlang%/\\textouterlang%/' iso.bbx
$ TEXMFHOME="$(readlink -f ../texmf)" make build build_dir=../texmf
! Extra }, or forgotten \endgroup.
\textouterlang ...dafter {\blx@outer@language }#1}
                                                  }
l.423 \c{greenberg1998camel}

? q
OK, entering \batchmode
$ make build build_dir=../texmf
$ popd
```

Finally, I typeset your example document from https://github.com/plk/biblatex/issues/1108#issuecomment-793489005 and I received the expected result:

``` bash
$ TEXMFHOME=./texmf latexmk -pdf example.tex
```

![scrot](https://user-images.githubusercontent.com/603082/110461918-59053b00-80d0-11eb-9f70-0b70e0e7cf8e.png)

Are you planning to submit a patch to https://github.com/michal-h21/biblatex-iso690, closing https://github.com/michal-h21/biblatex-iso690/issues/90, or would you like me to?

**Comment by moewew** [comment]
> > I guess you are expecting those strings to be printed in the 'last user-selected' language, i.e. in the active language before `biblatex` started meddling with languages itself.
> 
> Yes, that is what I would expect, since it seems sane and the BibLaTeX documentation promises it.

I would interpret the quoted passage from the `biblatex` documentation not as a promise that this is always the case, but as a (rough) description of what 'normally' happens. In particular the passage starts off with 'by default', so if a style or other preamble setting wants to override this behaviour that is perfectly fine and might be a conscious decision to implement certain desiderata.

> Then, I patched and installed biblatex-iso690. Here, I get an error when typesetting the biblatex-iso690 documentation:
> 
> ```shell
> $ git clone https://github.com/michal-h21/biblatex-iso690.git
> $ pushd biblatex-iso690/
> $ sed -i 's/\\mainlang%/\\textouterlang%/' iso.bbx

I don't think you want to make this `sed` substitution. `\mainlang` is a switch and `\textouterlang` is a text command that takes an argument. This will very likely not work. That's why I had a redefinition of the bibmacro currently using `\mainlang` in the MWE above.

> Are you planning to submit a patch to https://github.com/michal-h21/biblatex-iso690, closing [michal-h21/biblatex-iso690#90](https://github.com/michal-h21/biblatex-iso690/issues/90), or would you like me to?

I do not plan to submit a patch to `biblatex-iso690` because I do not know what exactly the standard wants here.

**Comment by Witiko** [comment]
> I don't think you want to make this sed substitution. `\mainlang` is a switch and `\textouterlang` is a text command that takes an argument.

Yes, you are correct. I missed your redefinition in the example. Thankfully, my substitution did not take effect, because the only affected macro was the one you redefine (`\blx@mainlangbibstring`).

> I do not plan to submit a patch to biblatex-iso690 because I do not know what exactly the standard wants here.

As far as I understand, this has nothing to do with the standard, since the standard is not (and, practically speaking, can't be) concerned with babel and polyglossia. This change is about giving users an option to set the language of the document even when babel is loaded by the document class and therefore the users cannot alter what babel calls *the main language*.

**Comment by Witiko** [comment]
> For all I know it was a conscious decision (by someone familiar with ISO 690) to use `\mainlang` in `biblatex-iso690` to force the main document language for some strings (and `\mainlang` was always documented as forcing the main language, not necessarily the surrounding language), so it should also be a conscious decision by someone who knows the style to go from `\(text)mainlang` to `\textouterlang`. It may well be that `\mainlang` was only chosen at the time because it was available and because in many simple document setups there is no difference between the main document language as announced to `babel` and the actual main document language, but there may also have been more to it.

I have a copy of ISO 690:1987 and ISO 690-2:1997 available. The only explicit mentions of language are that the place of publication should be in the language of the original cited source rather than in the language of the document. Additionally, Czech ISO 690-2 requires that the date of revision also be in the language of the original cited source. Things may be different for the ISO 690:2010 standard, which @DavidLuptak and @michal-h21 have read, but I highly doubt that the standard mentions anything remotely related to the concepts of main and active surrounding languages in babel and polyglossia.

Therefore, I am inclined to believe your that the decision to use `\mainlang` was mainly because it was the only thing available at the time, not because it would be more in line with the standard than `\textouterlang` is. Perhaps @michal-h21 can corroborate.

> The change should probably also be tested more extensively than I did so far because there might be some more pitfalls I didn't think of (plus I don't really have a back catalogue of `biblatex-iso690` documents for testing).

I can test things on my end on CSTUG bulletin articles and bachelor's and master's theses of the Masaryk University, Brno. I believe the main test set of [michal-h21/biblatex-iso690][1] is the package documentation, but I would not be surprised if @michal-h21 had additional documents to test this change on.

 [1]: https://github.com/michal-h21/biblatex-iso690

**Comment by michal-h21** [comment]
@moewew I've tried your example and updated `biblatex.sty`. The language switching seems to work correctly, thanks.

@Witiko the norm talks about the language of document, which is the main document selected by Babel or Polyglossia in most cases. I think that the language that is active at the moment when `\printbibliography` is used is the main document language in 99 % of cases, so it shouldn't be problem to use your proposed solution. One hypothetical problem I see is when you use full citations in footnotes. You would get wrong strings if you use it in part of text with a secondary language.

**Comment by Witiko** [comment]
> One hypothetical problem I see is when you use full citations in footnotes. You would get wrong strings if you use it in part of text with a secondary language.

@michal-h21 Yes, that is hypothetically a problem, although it is arguably the expected behavior according to the BibLaTeX documentation, or at least, as @moewew put it, "a (rough) description of what 'normally' happens". I am thinking that perhaps we could use `\textmainlang` in `\footcite` and `\textouterlang` elsewhere?

**Comment by michal-h21** [comment]
@Witiko yes, perhaps we can detect footnotes and switch the language selection macro accordingly. Here is a modified version of code from @moewew that does that:

```
\makeatletter
\protected\def\blx@mainlangbibstring#1#2#3{%
  \blx@begunit
  \blx@hyphenreset
  \blx@bibstringsimple
  \lowercase{\edef\blx@tempa{#3}}%
  \iffootnote{\let\iso@mainlang\textmainlang}{\let\iso@mainlang\textouterlang}
  \ifcsundef{#2@\blx@tempa}
    {\blx@warn@nostring\blx@tempa
     \blx@endnounit}
    {\blx@imc@ifcapital
       {\iso@mainlang{#1{\MakeCapital{\csuse{#2@\blx@tempa}}}}}
       {\iso@mainlang{#1{\csuse{#2@\blx@tempa}}}}%
     \blx@endunit}}
\makeatother

```

**Comment by moewew** [comment]
Maybe we should move the discussion about the implementation details in `biblatex-iso690` back to https://github.com/michal-h21/biblatex-iso690/issues/90, since they are not relevant for `biblatex` at large.

Just my two cents, but on first glance I would find it *really* counter-intuitive to have different language switching behaviour in the footnote and elsewhere (and note that while the effect might only be visible in full citations, conceptually it plays everywhere: If you respond to the outer language you are not necessarily choosing the main document language as declared with `babel`/`polyglossia`). If its too risky to leave the old `\textmainlang` behaviour, maybe it would be better to offer an option to let the user decide between `\textmainlang` and `\textouterlang` with all the consequences.

Essentially you are asking one of two things of your users
* If you use `\textmainlang`, you need your users to declare the actual main document of their language to `babel`/`polyglossia`. I would say that this is overwhelmingly the case (or should be the case, anyway). Apart from truly multilingual documents (is there a *main* language in that case anyway?) I can only think of one legitimate case where the main document language as passed to `babel`/`polyglossia` and that is the case of journals/collections of articles that can be prepared (in their entirety) in one main language, but where individual articles might also be written in a different language (I understand this is the case with `csbulletin`).
* If you use `\textouterlang`, you are relying on your users to open and close foreign language environments correctly so that they do not affect the citations negatively with respect to the expected (document/citation) language. (For example that means that when I quote a French text in an English document I should use the citation command *outside* of the French language environment I use to typeset the quotation, so that my citation is in English and not in French.) Since standard-style `biblatex` behaviour would be to switch languages, users should probably be doing the right thing here already.
  Even then the question remains whether user should expect localised citations or main-language citations in a case where a user has a significant portion of text in the non-main language and cites there as well. I haven't read ISO 690, but it would surprise me if it made an explicit statement about such a case.

**Comment by Witiko** [comment]
Thank you for the summary. I agree and I am closing this issue, so that further discussion can take place in https://github.com/michal-h21/biblatex-iso690/issues/90.
