### ISSUE TITLE
Date - Support of other divisions of the year according to ISO 8601-2

### ISSUE THREAD

**Issue by bmrs** [plk/biblatex#1127]
The use of `season` numbers as defined by the [ISO 8601-2](https://www.loc.gov/standards/datetime/iso-tc154-wg5_n0039_iso_wd_8601-2_2016-02-16.pdf) in the `date/issue` field is very useful. However, this standard has also created extra-month values for other divisions of the year:
- 21-24 for Spring, Summer, Autumn and Winter, independent of “Hemisphere”
- 25-28 for Spring, Summer, Autumn and Winter in Northern Hemisphere
- 29-32 for Spring, Summer, Autumn and Winter in Southern Hemisphere
- 33-36 for Quarter 1, Quarter 2, Quarter 3, Quarter 4 (3 months each)
- 37-39 for Quadrimester 1, Quadrimester 2, Quadrimester 3 (4 months each)
- 40-41 for Semestral 1, Semestral-2 (6 months each)

It would very useful if these divisions were also available, mostly for quarterly published journals. Would there be a way to fix that?
Thanks a lot!

**Comment by moewew** [comment]
I just added an answer to https://tex.stackexchange.com/q/593727/35864.

I have no strong opinion on this, but I would like to point out that implementing this in `biblatex` is more than just accepting the input. It would also mean supporting it on the output side. It is already fairly painful to support output for months and seasons, but support for fixed-hemisphere seasons and quarters, quadrimesters and semesters would certainly not make the code simpler for I guess very very marginal use cases.

**Comment by bmrs** [comment]
Thanks for your quick answer, I couldn't know it was so painful! As several references in my thesis come from quarterly publications, it would have helped me a lot, but I am not developer…

**Comment by moewew** [comment]
Mhh, on a technical side it is not that difficult I'd expect (not sure about the Biber side, but on the `biblatex` side it would be doable), but the code would become harder to maintain and we'd have to make sure to support the output in all localisations as well, which can get a bit messy.

If you are talking about `@article` entries, you can use the `issue` field to specify the quarter (but other entry types don't have an `issue` field, https://tex.stackexchange.com/q/354759/35864).

**Comment by plk** [comment]
As @moewew says, there is a difference between `biber` accepting this format as input (not so difficult given that we have a fully customisable date parsing module) and coding backwards-compatible output formatting in standard styles. If you think the style question is doable @moewew, I can add support into `biber`.

**Comment by bmrs** [comment]
OK! I'll stick to the `issue` field for articles, they are my main concern…

**Comment by moewew** [comment]
We'd need a good interface on the `biblatex` side. Currently I'm not sure what it would look like, but if we can work out something that is not too heavy and doesn't make the code too messy, I'd be fine with adding this.

My first instinct would be to try and generalise `\mkbibseasondateshort` and `\mkbibseasondatelong`. But we really need to chink about this. Experience has shown that especially with localisation things have to be flexible, because languages have quite different conventions.

**Comment by plk** [comment]
I think we should rename `season` to `yeardivision` and then this field will be a generalisation with the existing season localisation strings remaining valid - we can just add new strings for the other divisions. This requires changes in `biber` and `biblatex` and also styles. I don't see a huge problem in backwards compat as `season` is not widely used as a field in other styles I think.

**Comment by moewew** [comment]
Yeah, generalising `season` looks like the most promising route. But a quick search reveals that there are several styles defining things involving `season`, so we have to be careful. Maybe retain `season` for backwards compatibility and define `yeardivision` separately?

Given that the year divisions are fairly regular (first quarter, second quarter, ...) it would seem more efficient not to define new strings for all divisions, but to build the strings from several components (though experience has shown that one should not rely to much on how things work in English).

**Comment by plk** [comment]
First pass at this is in DEV 3.17/2.17. I have tried to use the `\DeprecateFieldWithReplacement` but I'm not sure how this will work with such fields as `season` being split dateparts and not being printed normally. I have put in localisation strings/FIXME placeholders for all the new year divisions and deprecation/redirects for the macros with `season` in them. Basic testing works so far.

**Comment by moewew** [comment]
Since seasons are used as bibstrings the usual `\DeprecateFieldWithReplacement` didn't quite work. So I went back to a more primitive aliasing (without warning, unfortunately) in https://github.com/plk/biblatex/commit/99e867e46dbc5f9df103748666c8b2c0db9f2cdf.

A bit of CTRL-F showed that the following packages could be affected
* `archaeologie` (https://github.com/LukasCBossert/biblatex-archaeologie/issues) by @LukasCBossert
* `biblatex-apa` (https://github.com/plk/biblatex-apa)
* `biblatex-archaeology` (https://github.com/CarlOrff/biblatex-archaeology) by @CarlOrff
* `biblatex-bath` (https://github.com/alex-ball/bathbib/issues) by @alex-ball
* `biblatex-chicago` by @dfussner
* `biblatex-fiwi`
* `biblatex-iso690`
* `biblatex-oxref` (https://github.com/alex-ball/biblatex-oxref) by @alex-ball
* `windycity` (https://github.com/brianchase/windycity) by @brianchase

Very light testing suggests things should still work fine.

I guess in principle we could make things slightly more compact for things like `2020-33/2020-35`, but that is probably not worth it - I don't expect lots of people wanting to use this.

**Comment by plk** [comment]
I think things should still work for styles as they don't tend to redefine the `\mkbibdateshort/long` macros which are in the `.lbx` files mostly.

**Comment by LukasCBossert** [comment]
Wow, biblatex is getting more and more complex and capable of so many things. Thanks  @moewew for pointing out possible conflicts with the style [`archaeologie`](https://ctan.org/pkg/archaeologie). I will keep an eye open for future conflicts.

**Comment by dfussner** [comment]
Many thanks for the heads up, @moewew. I'll have a look to see whether it
has affected anything at my end.

**Comment by dfussner** [comment]
It looks like some modifications may be necessary in biblatex-chicago, but
I'm having compatibility issues with biblatex from git and the latest dev
binary of biber from Sourceforge for 32-bit GNU/Linux -- Sourceforge's
biber 2.17 doesn't like the .bcf version. An issue at my end?

**Comment by plk** [comment]
Ah, I haven't updated 2.17 for 32-bit linux - @moewew does that - any chance you might be able to build `biber` dev and upload to the dev folder on SF @moewew

**Comment by dfussner** [comment]
Thanks @plk and @moewew for looking into it. There's no rush here,
obviously.

**Comment by moewew** [comment]
Oh, yeah right. Sorry about that. I don't update the 32bit binaries as often (still build everything manually). Should be up now.

I had hoped we might be able to drop 32bit Linux support soon, but apparently there are still some people out there using it.

---

As @plk says, there is some backwards compatibility code, so most things will hopefully work without larger problems, but there will be warnings if the old names are used. So it is probably better if style authors switch to the new names.

**Comment by dfussner** [comment]
Thanks for the upload, @moewew. You're certainly right about the compat
code, so mostly things look fine even without changes on my end -- thanks
for that. A few corner cases are broken, so I'll switch to the new system
when I get the chance.
