### ISSUE TITLE
Some terms are not translated in `french.lbx`

### ISSUE THREAD

**Issue by duboism** [plk/biblatex#1140]
I have recently noticed that `french.lbx` doesn't translate `in` so:
```
@article{einstein,
    author =       "Albert Einstein",
    title =        "{Zur Elektrodynamik bewegter K{\"o}rper}. ({German})
    [{On} the electrodynamics of moving bodies]",
    journal =      "Annalen der Physik",
    volume =       "322",
    number =       "10",
    pages =        "891--921",
    year =         "1905",
    DOI =          "http://dx.doi.org/10.1002/andp.19053221004",
    keywords =     "physics"
}
```
would produce:
Albert Einstein. « Zur Elektrodynamik bewegter Körper. (German) [On the electrodynamics of moving bodies] ». **In** : Annalen der Physik 322.10 (1905), p. 891-921. doi : http://dx.doi.org/10.1002/andp.19053221004.

Correct me if I'm wrong but I think we should use `Dans` (or `Publié dans` is there is enough space). It used to be the case when I wrote My PhD thesis 10 yeas ago. Similarly, `inseries` is not translated. Maybe the usage differs in different countries.

**Comment by moewew** [comment]
Technically the term *is* translated, that is to say there is a translation for the term in `french.lbx`

https://github.com/plk/biblatex/blob/64578cf8c2e253ed3ddc7382732fc9c3a9e0be93/tex/latex/biblatex/lbx/french.lbx#L415

But the term is translated as "in" and not as "dans". If I understand correctly, our French language contributors consider the use of the Latin "in" acceptable in academic publishing. See for example discussions in https://github.com/plk/biblatex/pull/1022 and https://github.com/plk/biblatex/pull/552

If you want "dans", you can redefine the relevant `bibstring`
```latex
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\DefineBibliographyStrings{french}{in = {dans}}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,westfahl:space,gaonkar:in}

\printbibliography
\end{document}
```

If the is overwhelming new evidence that "in" is unacceptable, we could consider switching to "dans", but since that would affect a lot of documents in backwards incompatible ways, this is not a change we can go for willy-nilly.

**Comment by moewew** [comment]
No, the package was just a suggestion to resolve this issue elegantly. If there are different conventions, a simple solution is to have different `.lbx` files for these conventions (we can use inheritance to keep the contents of those restricted to the actual differences and thus as small as possible) and then pick the one you want. But I don't think anyone found this important enough that they actually wanted to step up and publish such a package on CTAN. Especially since this is relatively easy to fix in the preamble with a few `\DefineBibliographyStrings{french}` lines.
