### ISSUE TITLE
Accessing raw field values in first run

### ISSUE THREAD

**Issue by epilys** [plk/biblatex#1145]
Hello, I'm examining if it's possible to store all graphics paths in a bib file along with the citations for it. Currently, I store the path for each graphic in the file field.

It's possible to do `includegraphics` in a bibmacro that prints the file field with a custom field format, however: it seems it's not possible to pass arguments for the `includegraphics` (width, most importantly). (EDIT: I mean, it's not possible to pass arguments to a `cite` macro in order to forward the arguments to `includegraphics`)  I guess it's possible to store the widths as a field annotation however I prefer to do that in the TeX code where the figure is.

Ideally, I would like a way to access the raw field value in a way that is expanded immediately on every run, since `includegraphics` requires the file path argument to be expanded. Do you think such an approach is possible?

Thank you in advance!

**Comment by moewew** [comment]
Unfortunately, the data in `biblatex` is stored in an unexpandable way. So to get something in an expandable form you need to do some tricks. What's more the data is never available before the Biber run, because Biber extracts the data from the `.bib` file and makes it LaTeX-readable.

If you need the data to be available at all times, you might want to try [`usebib`](https://www.ctan.org/pkg/usebib), which reads the `.bib` file directly on the LaTeX side (but I wouldn't know about its expandability).

That said there would be ways to pass options to `\includegraphics` in a `\...cite...` command. Either by abusing the pre- or postnote (if they are not needed) or via a wrapper command and cheating (an example for the latter is the way I added the page reference to the link in https://tex.stackexchange.com/q/598179/35864 with `\mypage`).

**Comment by epilys** [comment]
Thanks, I didn't think about pre-,post-notes! :) 

I wonder if `biber` can be rewritten in `l3`...

**Comment by moewew** [comment]
> I wonder if `biber` can be rewritten in `l3`...

Even though LaTeX3 has enabled us to do lots of things that I thought were extremely painful in TeX, I'm not sure if it is ready to do fast Unicode-aware sorting for us. Long-term I'd be interested in a Lua-based approach given the place of Lua in the TeX ecosystem with LuaTeX.
