### ISSUE TITLE
Add new bib heading to overwrite \bibintoc

### ISSUE THREAD

**Issue by janniklasrose** [plk/biblatex#1171]
biblatex defines (via `\defbibheading`) the following headings
- `bibliography`
- `subbibliography`
- `biblist`

and the following alternatives to force the headings into the ToC
- `bibintoc`
- `subbibintoc`
- `biblistintoc`

pdflatex already respects `memoir`'s `\bibintoc` switch via `\ifmemoirbibintoc`, which is great:
https://github.com/plk/biblatex/blob/eac99d8e453b2d09f14757000526bf1da3454c4d/tex/latex/biblatex/biblatex.def#L2098-L2101

However, there is no mechanism to force a heading to **not** appear in the ToC. It is of course possible to temporarily invoke `\nobibintoc`, but this hard-codes the dependency on `memoir` in yet another place. I'm thinking of an appendix page with a `\printbibliography` of certain references, and this `.tex` file might get included in another document that does not use memoir; or a per-chapter bibliography that should not appear in the ToC.

I propose the following:
- `bibnointoc`,
- `subbibnointoc`,
- `biblistnointoc`,

which behave like `bibliography`, `subbibliography`, `biblist` but without the `\ifmemoirbibintoc` logic.

**Comment by janniklasrose** [comment]
I would be happy to attempt a PR for this, but would first like to gauge how the maintainers feel about such a change.

**Comment by moewew** [comment]
This sounds like a very niche requirement. For specialised things like this users can define their own headings with `\defbibheading`. I'd rather not overload the core with definitions that hardly anyone uses.

Not quite sure about your use case, but you could (locally?) redefine `\ifmemoirbibintoc` (`\renewcommand{\ifmemoirbibintoc}[2]{#2}`), which would not hard-code a `memoir` dependency, because it is always defined by `biblatex`.

**Comment by janniklasrose** [comment]
Fair enough. I like the suggestion of temporarily redefining `\ifmemoirbibintoc`. Thanks!
