### ISSUE TITLE
feature request: make addtocontents patch configurable

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1172]
biblatex patches `\addtocontents` to write out the current value of `refsection`.  

~~~~

\AtEndPreamble{%
  \patchcmd\addtocontents
    {\string\@writefile}
    {\string\@writefile{#1}{\defcounter{refsection}{\the\c@refsection}\relax}%
     \string\@writefile}
    {}
    {\blx@err@patch{\string\addtocontents}}}
~~~~

Could this be made configurable? It breaks one of my (rather complicated) setups in a special external file. While I could store and restore the refsection value before writing to the file, it would be much easier if I could switch locally a boolean that would suppress the writing altogether.

**Comment by moewew** [comment]
`biblatex` v3.17 will no longer patch `\addtocontents` like this. Following discussions in https://github.com/josephwright/siunitx/issues/408 I merged https://github.com/plk/biblatex/pull/1166 for https://github.com/plk/biblatex/issues/1116 to implement a different way to ensure the correct `refsection` settings are used.

Since the new approach is radically different and I'm not sure I didn't miss anything, testing and comments are greatly appreciated.

**Comment by u-fischer** [comment]
Hm. And how do I test? The sourceforge site seems not to have the new code, and the git sources/l3build seems not to install either.

**Comment by moewew** [comment]
Ah yes, we don't have a functioning `l3build` setup. You can use the Perl script in `obuild` as described in https://github.com/plk/biblatex#installation-from-github.

If that is not convenient get [biblatex-72a46fc-317dev.zip](https://github.com/plk/biblatex/files/7042029/biblatex-72a46fc-317dev.zip) and use it together with Biber 2.17 from SourceForge. That `.zip` contains the LaTeX runtime files from the `dev` branch with only one change: It has values for `\abx@date` and `\abx@version` that compile instead of

https://github.com/plk/biblatex/blob/72a46fc5204c2b53343eebf555e070d3bfd4bead/tex/latex/biblatex/biblatex.sty#L15-L16

**Comment by moewew** [comment]
The newest `dev` from https://sourceforge.net/projects/biblatex/files/development/ has the relevant commits now, so you should be able to test things as usual.

**Comment by moewew** [comment]
`biblatex` 3.17 no longer patches `\addtocontents` in this way. Hopefully the new code does not interfere with what you are doing. If that is the case, I suggest you open a new issue.
