### ISSUE TITLE
biblatex 3.17 dev: rerun message doesn't go away.

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1173]
The following document always shows a rerun message. The problem is that biblatex compare in \AtEndDocument 
`blx@cites@#1` with  `blx@lastcites@#1`, but if the refsection doesn't contain a cite, both commands are undefined and the test fails:

~~~~
\documentclass{article}% or something else
\usepackage[sorting=none]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}

\begin{refsection}
\cite{doody}
\end{refsection}

\begin{refsection}
no cites
\end{refsection}

\makeatletter
\ExplSyntaxOn
\tl_show:c{blx@allrefsections}
\tl_show:c{blx@cites@1}
\tl_show:c{blx@lastcites@1}
\tl_show:c{blx@cites@2}
\tl_show:c{blx@lastcites@2}
\ExplSyntaxOff
\ifcsstrequal{blx@cites@1}{blx@lastcites@1}{true}{false}
\ifcsstrequal{blx@cites@2}{blx@lastcites@2}{true}{false}
\end{document}
~~~~

**Comment by moewew** [comment]
Thank you very much for finding this. This should hopefully be fixed in https://github.com/plk/biblatex/commit/68a1228454644705d41785e2a4fa81037f875d9b. (Since `\ifcsstrequal` does some `\ifcsundef` tests itself, this increases the number of `\ifcsundef` tests run unnecessarily, but I didn't want to have to maintain a copy of `\ifcsstrequal` with a slightly changed logic just to save a few `\ifcsundef`s.)
