### ISSUE TITLE
Suggestion: more than one type filter 

### ISSUE THREAD

**Issue by rolfn** [plk/biblatex#1182]
If I needed a partial bibliography that only lists all articles and article-like publications, I would instinctively write, for example:

```
\printbibliography[type=article,type=inbook,title={Articles only}]
```

but with that I get the error

```
! Package biblatex Error: 'type' used multiple times.
```

Instead, I have to write awkwardly, for example:

```
\printbibliography[nottype=book,nottype=thesis,nottype=proceedings,title={Articles only}]
```

Why aren't several and-linked type filters possible?

**Comment by moewew** [comment]
All filtering options to `\printbibliography` are connected with a logical *and*, that means that an entry needs to satisfy *all* filter conditions to appear in the bibliography at the end.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}


\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \nocite{*}

\printbibliography[keyword=secondary, title={Secondary}]
\printbibliography[type=book, keyword=secondary, title={Secondary books}]
\end{document}
```
From that perspective it is clear that you can't have several `type` filters at once: An entry cannot have several different entry types, so a bibliography filtered by two types would always end up empty.

If you want to list entries of several different types, you want to connect filters with an *or*, because you want to list an entry if it has type one *or* type two. That can be done `\defbibfilter`, which allows you to define more complex filters. 

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\defbibfilter{artorincoll}{
  type=article or type=incollection
}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \nocite{*}

\printbibliography[filter=artorincoll, title=@articles and @incollections]

\printbibliography[type=article, title=@articles]

\printbibliography[type=incollection, title=@incollections]
\end{document}
```

I don't think it would be a good idea to allow several `type` directives which filter as *or*, because it goes against the 'natural' behaviour of other filtering options. Plus, I think it would be trickier to implement. If you need more complex filters, use `\defbibfilter`.

**Comment by rolfn** [comment]
Thank you for the explanation. I saw it completely wrong. Sorry for the noise..
