### ISSUE TITLE
how to compare the item in a list with a string? 

### ISSUE THREAD

**Issue by hushidong** [plk/biblatex#1192]
Compare a field value with a string we can use  `\iffieldequalstr` , but how can we compare the item in list with a string？
I use `\iflistequals` ,  `\thefirstlistitem`  etc. to do it, it seems not work, see the following example, the condition outputs  are all false.

Any good ideas?

```

\documentclass{article}
\usepackage{expl3}

\usepackage[backend=biber]{biblatex}

\ExplSyntaxOn
\DeclareBibliographyDriver{book}{
\usebibmacro{bibindex}%
\usebibmacro{begentry}%
\usebibmacro{author/editor+others/translator+others}%
\addcolon%
\usebibmacro{maintitle+title}%
\addcolon%
\printlist{language}%
\thelist{language}%
\str_if_eq:eeTF{\thefirstlistitem{language}}{english}{true}{false}
\str_if_eq:eeTF{\strfirstlistitem{language}}{english}{true}{false}
\edef\langa{\thefirstlistitem{language}}
\ifdefstring{\langa}{english}{true}{false}
\edef\langb{english}
\iflistequals{language}{\langb}{true}{false}
\usebibmacro{finentry}}
\ExplSyntaxOff


\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{brooks_TroublingConfessionsSpeaking_2000,
  title = {title},
  author = {Peter, A},
  date = {2000},
  publisher = {Press},
  language={english},
  location = {{Chicago}}
}

\end{filecontents}

\addbibresource{\jobname.bib}


\begin{document}

\nocite{*}
\printbibliography

\end{document}
```

**Comment by moewew** [comment]
In your example the `language` list is undefined because it has been cleared by the `clearlang` feature

> If this option is enabled, `biblatex` will automatically clear the language field
of all entries whose language matches the `babel`/`polyglossia` language of the
document (or the language specified explicitly with the `language` option) in order
to omit redundant language specifications. The language mappings required by this
feature are provided by the `\DeclareRedundantLanguages` command from
§ 4.9.1.

Disable this feature and we get the slightly more expected
```latex
\documentclass{article}
\usepackage{expl3}

\usepackage[backend=biber, clearlang=false]{biblatex}

\ExplSyntaxOn
\DeclareBibliographyDriver{book}{
\usebibmacro{bibindex}%
\usebibmacro{begentry}%
\usebibmacro{author/editor+others/translator+others}%
\addcolon%
\usebibmacro{maintitle+title}%
\addcolon%
\printlist{language}%
\thelist{language}%
\thefirstlistitem{language}
\par
A~\str_if_eq:eeTF{\thefirstlistitem{language}}{english}{true}{false}\par
B~\str_if_eq:eeTF{\strfirstlistitem{language}}{english}{true}{false}\par
\edef\langa{\thefirstlistitem{language}}
C~\ifdefstring{\langa}{english}{true}{false}\par
\edef\langb{english}
D~\iflistequals{language}{\langb}{true}{false}\par
\usebibmacro{finentry}}
\ExplSyntaxOff

\begin{filecontents}{\jobname.bib}
@book{brooks_TroublingConfessionsSpeaking_2000,
  title = {title},
  author = {Peter, A},
  date = {2000},
  publisher = {Press},
  language={english},
  location = {{Chicago}}
}

\end{filecontents}

\addbibresource{\jobname.bib}


\begin{document}

\nocite{*}
\printbibliography

\end{document}
```
> A true
> B true
> C true
> D false

![screenshot of output above](https://user-images.githubusercontent.com/6755835/136673390-a4bec0f5-7ce8-440b-9b68-6790f809133d.png)


The test D fails because `<macro>` in `\iflistequals{<literal list>}{<macro>}{<true>}{<false>}` needs to be equal to the internal specification of the list, which is not simply a `english` for a list containing one item that reads `english`.

**Comment by hushidong** [comment]
ok, thanks, I get it. The `\printlist{language}` did not out put anything in my MWE, but I was not aware the language list was cleared and forgot the clearlang option.

I will close this issue, thank you again!
