### ISSUE TITLE
Cite command that can be used in \section commands and/or in the second argument to \texorpdfstring?

### ISSUE THREAD

**Issue by ProcyonTheEvil** [plk/biblatex#1198]
Hello and thank you for your awesome work on biblatex.

Is there a cite command that can be used in \section commands and/or in the second argument to \texorpdfstring? I would like to write something like
`\subsection{The model introduced by \textcite{bibkey}.}`
but this just adds "The model introduced by bibkey." to the PDF table of contents/bookmarks and produces warnings like
"Package hyperref Warning: Token not allowed in a PDF string (Unicode):(hyperref) removing \textcite on input line 685." in the output. [This stackexchange question and answer](https://tex.stackexchange.com/questions/384754/citations-and-hyperref) says that the biblatex cite command cannot be expanded when hyperref produces the PDF bookmarks. So my question is: Is there a cite command that allows this:
`\subsection{The model introduced by \texorpdfstring{\textcite{bibkey}}{\textcitepdf{bibkey}}.}`
and correctly produces the PDF bookmark "The model introduced by Alice and Bob (2005)." ?

**Comment by moewew** [comment]
As far as I know the command would have to be truly expandable in order to work in bookmarks. Unfortunately, the cite commands are far from expandable and the current framework doesn't even allow for expandable data retrieval. So I think this is not going to happen without a major rewrite of the entire system. That would be nice to have for other reasons as well (e.g. https://tex.stackexchange.com/q/331026/35864), but I don't see it happening anytime soon.

Some workarounds with helper macros are available, but it is pretty painful to piece together a whole formatted citation that way (https://tex.stackexchange.com/a/73690/35864, https://tex.stackexchange.com/q/60552/35864)
