### ISSUE TITLE
Incorrect capitalization if title ends with question mark

### ISSUE THREAD

**Issue by billven8197** [plk/biblatex#1228]
If a bibliograhy item has a question mark ("?") as final character of its title, the _style=ieee_ will incorrectly get a capitalized month if all blocks between the title and month are empty, as shown below.

- If the title contains a ? but not as its final character, the issue does not appear. 
- The issue only exists in certain laguages, depending on local capitaliztion of dates. (swedish, norsk and italian etc are affected)
- The issue persists between compilers (XeLaTeX, pdfLaTeX, LaTeX) for version TeX Live 2021, but is not showing for TeX Live 2020 or lower.
- Uncommenting _edition_ below will remove issue as an intermediate block now is filled. 

```
\begin{filecontents}{references.bib} 
@book{citeNoQ,
  author = {Abraham Lincoln},
%  edition=2,
  title = {This is NOT a question},
  year = 2022,
  month = 05,
}

@book{citeQ,
  author = {Abraham Lincoln},
%  edition=2,
  title = {This IS a question?},
  year = 2022,
  month = 05,
}
\end{filecontents} 

\documentclass[]{article}
\listfiles
\usepackage[swedish]{babel}
\usepackage[style=ieee]{biblatex}
\addbibresource{references.bib}

\begin{document}
No question mark in end of title of citation \cite{citeNoQ}.

A question mark in the end of title of citation \cite{citeQ}.
\printbibliography
\end{document}
```
![image](https://user-images.githubusercontent.com/22450920/169535633-e18ab684-7c83-4ffa-b111-98044700d929.png)

**Comment by moewew** [comment]
Are you sure that older version of `biblatex` behaved differently here? I don't have historic versions on my PC, but I just ran the example on Overleaf and got the same result for TeX Live 2021, 2020, 2019 and 2015.

Here is a workaround that appears to do the right thing for `biblatex-ieee`, but that might be a bit risky in general.
```latex
\documentclass[]{article}
\listfiles
\usepackage[swedish]{babel}
\usepackage[style=ieee]{biblatex}

\begin{filecontents}{\jobname.bib} 
@book{citeNoQ,
  author = {Abraham Lincoln},
  title  = {This is NOT a question},
  year   = 2022,
  month  = 05,
}
@book{citeQ,
  author = {Abraham Lincoln},
  title  = {This IS a question?\nopunct},
  year   = 2022,
  month  = 05,
}
\end{filecontents} 
\addbibresource{\jobname.bib}

\begin{document}
No question mark in end of title of citation \cite{citeNoQ}.

A question mark in the end of title of citation \cite{citeQ}.
\printbibliography
\end{document}
```

I'm not sure, though, if there is something core `biblatex` can do here. The problem is caused by `biblatex`'s punctuation/capitalisation tracker feature. After a `?`, `!` and (sentence-ending) `.`  `biblatex` capitalises words. The `?` therefore triggers capitalisation. The `.` after the title in \[1\] is not a sentence-ending period, but in fact an abbreviation dot (`biblatex-ieee` is unusual in that regard and uses `\setunit{\adddot\addspace}%`, which I don't think I've seen anywhere else), so there is no capitalisation after that.

You can tell `biblatex` not to capitalise after `?`, `!` and `.` with
```latex
\documentclass[]{article}
\listfiles
\usepackage[swedish]{babel}
\usepackage[style=ieee]{biblatex}

\DefineBibliographyExtras{swedish}{%
  \DeclareCapitalPunctuation{}%
}

\begin{filecontents}{\jobname.bib} 
@book{citeNoQ,
  author = {Abraham Lincoln},
  title  = {This is NOT a question},
  year   = 2022,
  month  = 05,
}
@book{citeQ,
  author = {Abraham Lincoln},
  title  = {This IS a question?},
  year   = 2022,
  month  = 05,
}
\end{filecontents} 
\addbibresource{\jobname.bib}

\begin{document}
No question mark in end of title of citation \cite{citeNoQ}.

A question mark in the end of title of citation \cite{citeQ}.
\printbibliography
\end{document}
```
but that effectively disables all automatic capitalisation.

**Comment by billven8197** [comment]
I see! I did my testing in Overleaf as well for older versions, but must have either misread or encountered some caching.

Either way this seems more as a bibatex-ieee style problem (or rather a feature), and since it's the style that just is a bit unusual I close this issue.
