### ISSUE TITLE
[Feature Request] Change \fullcite maxbibnames without redefining the command

### ISSUE THREAD

**Issue by mcp292** [plk/biblatex#1243]
For long author lists `\fullcite` abbreviates to "Author, First et al.". I would like to be able to specify how many authors to list, on the fly as in `\fullcite[maxbibnames=2]{citation}`.

**Comment by moewew** [comment]
`\fullcite` obeys `mincitenames` and `maxcitenames` by default (because it is a citation command). You can set these values (either directly or via `minnames`/`maxnames` so that the `...bib...` and `...cite...` values are the same), but that may influence other citation commands as well. See
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear, maxcitenames=2, maxbibnames=999]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,aksin}


\fullcite{aksin}

\printbibliography
\end{document}
```

There are already ways to make `\fullcite` take its values from the `...bib...` options and not the `...cite...` options. See https://tex.stackexchange.com/q/126226/35864.

Conceptually I don't want to create a new global/load-time option that only governs `\fullcite` as that can get messy very quickly (also because Biber uniqueness settings depend on that value). But we have https://github.com/plk/biblatex/issues/1209 open, which may resolve this issue more satisfactorily if implemented.

**Comment by mcp292** [comment]
Thank you for the response. If I understand correctly, the short answer is there is no simply way to adjust this per command. 

Based on my understanding it seems the options are to change the values globally, or redefine the function in some way.

The simplest options available seem to be documented in [this answer](https://tex.stackexchange.com/a/267089/214194).

**Comment by moewew** [comment]
> If I understand correctly, the short answer is there is no option to adjust this per call.

Pretty much, yes. Generally, the options can only be used in the preamble and only "globally" (there are per-type and per-entry options, but these apply "all the time" as well and not just in restricted circumstances like for a specific `\...cite...` command). Options can generally not be changed within a certain `\...cite...` command, but often a workaround is available because one can just use the internal implementation of that option directly. This is exactly what can be done here. Ultimately, the `(min|max)(cite|bib)names` option just set the `(min|max)names` counter.

I'd like to close this issue since we have https://github.com/plk/biblatex/issues/1209 open for the general idea of using options more "locally". For this specific use case workarounds are available.
