### ISSUE TITLE
\refcontext and \refsection

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex#1249]
I am not completely sure whether this is a bug or a documentation issue. In any case I get results I'd not expect when using `\newrefcontext` with `\refsection`. Consider:

```tex
\documentclass{article}
\usepackage[sorting=nyt]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
	\newrefsection[biblatex-examples]
	\nocite{*}
	\printbibliography[type=online]
	\endrefsection
	\newrefcontext[sorting=ydnt]
	\newrefsection[biblatex-examples]
% works, but only within this refsection
%	\newrefcontext[sorting=ynt]
	\nocite{*}
	\printbibliography[type=book]
	\newrefsection[biblatex-examples]
	\nocite{*}
	\printbibliography[type=article]
\end{document}
```

According to the documentation, "the context section started by the last `\newrefcontext` command in the document will extend to the very end of the document" (as opposed to `\localrefcontext`). But in fact, the `\newrefcontext` here does not have any effect on the following refsections. If used within the refsection, it works, but only inside this refsection.

I'd actually expect the context change to be global (as documented).

**Comment by moewew** [comment]
I haven't had a close look at the implementation of refcontexts, but I don't find it particularly unexpected that refcontexts are subordinate to refsections. After all refsections are basically completely separate bibliographies. So I would say that the documentation is slightly inaccurate here (and possibly in some other places as well [at least I often forget about refsection effects, when I think about biblatex behaviour], when we talk about global effect).

The final arbiter here should be @plk though, since he implemented refcontexts and knows how they are supposed to behave.

**Comment by plk** [comment]
refsections are basically the global units by design and so everything has to be local to a refsection, including refcontexts. I've corrected that bit in the docs.

**Comment by jspitz** [comment]
Thanks for clarification.

Would it be possible to add a feature that changes reference features (particularly `sorting`) for all refsections that follow? As it is now, I understand that refsections take up the sorting as set via the global `sorting` option (in that sense, they are not completely "separate").

Again, my use case here is `biblatex-publist`, where some users want to have both their publications and their talks in one document, both subdivided by sections (via refsection), but both sorted differently.

**Comment by plk** [comment]
Just trying to get a sense of the use case. Does this need some automation or could you not just declare a named refcontext (with `\DeclareRefContext`) and begin this after every refsection (potentially in a hook?)

**Comment by jspitz** [comment]
Basically, `biblatex-publist` comes with two different modes: (1.) omit the "publist" author and only name co-authors (as in "2022 (with Jane Doe)...") and (2.) highlight (e.g., embolden) the "publist" author in the author list. By default, the former uses a `ydt` sorting template (defined by the package), as it does not make sense to sort by name in this case, the latter uses `ydnt` (but users can also request their own templates via a dedicated option).

Now some users told me they would like to use highlight for their publications, and omit for their talks. In the next version, switching these modes on the fly will be possible via `\ProcessPublistOptions{plauthorhandling=omit}`, which can be done, in this use case, just before the first refsection of the talks (there might be different refsections assembling "keynotes", "invited talks", "other talks").

So of the `plauthorhandling` option is switched in the document body, it sets a switch to change the author handling (which works fine), but then also set the expected sorting for this mode. This sorting should be effective untll further notice (i.e., unless the handling is changed again).

As `\newrefcontext` alone does not work, what could work is something such as `\AtFollowingRefcontexts{\newrefcontext[sorting=<scheme>]}`. This hook would be effective for all refcontexts that follow the setting, so something between `\AtBeginRefcontext` and `\AtNextRefcontext`.

**Comment by plk** [comment]
Is this still an issue we need to deal with?

**Comment by plk** [comment]
Please try `biblatex` 3.20 from SF "development" folder. No need to update `biber`. I've added `\AtFollowingRefsections`. This is basically the same as `\AtBeginRefsection` but since it can be used outside of the preamble, it will only affect refsections after its use. It is run just before `\AtNextRefsection` so that code specific to the next refsection can potentially override it.

**Comment by jspitz** [comment]
Thanks, that's perfect!
