### ISSUE TITLE
Print autor names respecting maxcitenames in bibliography styling

### ISSUE THREAD

**Issue by ed-stein** [plk/biblatex#1269]
I need to create a bibliography style based on authoryear, which precedes the entry with its original citation label. I know that I can set the additional style somewhat like this.

```latex
\renewbibmacro*{begentry}{%
  \printnames{labelname} \usebibmacro{date+extradate}\\
}
```

But this will give me a different line, if maxcitenames and maxbibnames are set to different values. By example, if I have `maxcitenames` set to 2 and `maxbibnames` set to 99, I will get "Dehmel et al 2020" for citing and "Dehmel / Kenning / Wagner 2020" in the first line of the bib entry (respecting that I'm using '/' as the author delimiter). I want both to be the same, without changing `maxcitenames`, as the second line of the bib entry would be affected by this and no longer show all and full author names. Is there a field or bib macro that I can use to access the original label?

**Comment by moewew** [comment]
The citation label that is shown by `authoryear` is generated on demand by the cite macros according to entry data (and uniqueness info etc. calculated by Biber). The resulting citation label that is printed is not stored anywhere (for this style).

That means that you need to locally recreate the citation setting in order to obtain the correct label in the bibliography. There is a few things to take care of (besides `(min|max)names`). You can have a look at https://github.com/moewew/biblatex-ext/blob/e547883bb1e11a207a8407e6fa3c5b77548911fa/ext-standard.bbx#L88-L101 to see what `biblatex-ext` does. Or you could just use `biblatex-ext` directly so that you don't have to worry about these things.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[
  backend=biber,
  style=ext-authoryear,
  maxbibnames=999,
  introcite=plain,
]{biblatex}

\renewcommand*{\introcitepunct}{\\}

\DeclareNameAlias{sortname}{given-family}

\setlength{\bibitemsep}{\itemsep}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,aksin,worman,geer,companion,herrmann}

\printbibliography
\end{document}
```
