### ISSUE TITLE
With TeXLive 2023 I face two perl scripts biber and biber-ms with same vendor path

### ISSUE THREAD

**Issue by bitstreamout** [plk/biblatex#1270]
which is
```
/lib/perl5/vendor_perl/5.36.0/Biber.pm
/lib/perl5/vendor_perl/5.36.0/Biber/
```
and those files are conflicting.   I'd like to avoid to hack e.g. `biber-ms` by adding a
line like
```
use lib '/lib/perl5/vendor_perl/5.36.0/biber-ms/`;
```
an other solution seems not working.  Therefore why we have two versions
of biber and why seems 2.18 not to support multiscript (otherwise biber-ms would
be superfluous)

**Comment by bitstreamout** [comment]
Btw: the test suite of `biblatex-biber-ms.tar.gz` with its source tree `biblatex-biber-4.0` is missing `t/tdata/multiscript.bltxml`

**Comment by moewew** [comment]
This is a Biber issue, which should be reported at https://github.com/plk/biber/issues (please re-report it there, so issues don't get lost).

You may also want to report which OS you use and how you installed Biber (I'm assuming you used `tlmgr install biber` or chose a scheme that includes Biber, because you mention TeX Live, but in theory a manual install is also possible).

**Comment by bitstreamout** [comment]
Nope I compile the source from scratch for openSUSE as TeXLive maintainer.  Aka no `tlmgr` allowed, only clean `rpm` otherwise the installation is broken

**Comment by bitstreamout** [comment]
The Debian might face the same problem with apt and/or dpkg
