### ISSUE TITLE
Option "pluralothers"

### ISSUE THREAD

**Issue by hvoss49** [plk/biblatex#1298]
From the change file of the documentation I read that `pluralothers` is used by the style `apa`. However, I cannot see any difference with setting `pluralothers=false` in the following example. `app.bbx` itself set it to ´true´.

```
\documentclass{article}
\usepackage{csquotes}
\usepackage[american]{babel}
\usepackage[style=apa,
	%pluralothers=false%%.   no difference
]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
foo.~\cite{aksin}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
You wouldn't see a difference with only one citation like that - `pluralothers` only has an effect when an `et al` truncation would result in only one name "in" the truncation and the option would force it to then be visible as there would have to be at least two names "in" the truncation.

**Comment by plk** [comment]
See the following example:

```
\begin{filecontents}[overwrite]{\jobname.bib}
  @BOOK{test1,
    AUTHOR = {Arthur Anderson and Brian Brown and Cuthbert Cranshaw and  Edward Ellison},
    TITLE  = {A title 1},
    DATE   = {2020}
  }
  @BOOK{test2,
    AUTHOR = {Arthur Anderson and Brian Brown and Daniel Danforth and  Edward Ellison},
    TITLE  = {A title 2},
    DATE   = {2020}
  }
\end{filecontents}
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[style=apa]{biblatex}
%\usepackage[style=apa,pluralothers=false]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\noindent\cite{test1}\\
\cite{test2}
\printbibliography
\end{document}
```

For APA, it's complex because APA demands the use of the `uniquelist=minyear` option as it only cares about name list disambiguation for entries with the same year and since it also has `maxcitenames=2` and `mincitenames=1`, you only notice the effect from the 3rd name onwards and only when `uniquelist` disambiguation forces dynamic expansion of the name list, when the 3rd or later name is different and when there are other names following the point of difference.

**Comment by hvoss49** [comment]
Thanks and now understood ...
