### ISSUE TITLE
Filtering by type

### ISSUE THREAD

**Issue by shmuelmetz** [plk/biblatex#1307]
The **\printbibliography** command has a **type=** keyword for filtering on entry type. It would be helpful if there were an additional keyword for selecting on the type field, or if the syntax of **type=** were expanded to allow specifying both entry type and type. I don't know whether there is a use case for specifying subtype as well.

**Comment by moewew** [comment]
You can filter for arbitrary fields and arbitrary field values using bibchecks (see `\defbibcheck` and friends in the documentation, you can find a simple example at https://tex.stackexchange.com/q/333682/35864).

I'd have though that the `type`  field is not used all that often and that if it is used it is fairly fine-grained so that filtering on the `type`  field is not that common. It is by far not as common as filtering by *entry type*, which is what the `type` option (perhaps slightly surprisingly) to `\printbibliography` does.

**Comment by shmuelmetz** [comment]
In my case I'm citing Unicode web pages, some of which are FAQs and some of which are standards. From my reading of biblatex, standards should have an entry type of **report** and a type of **standard**. I'm using a keyword of FAQ to separate out the FAQ. I'm also citing RFCs from the IETF, also with an entry type of **report** and a type of **standard**.  I want a separate bibliography for RFCs and standards. Selecting entries with type=standards and without the FAQ keyword would have given me exactly the entries I wanted. I'll try your workaround.
As a side note, the description of type equal should make it explicit that the entry type is not the value of the type keyword in the entry and perhaps even suggest \iffieldequals as a workaround.

**Comment by moewew** [comment]
`biblatex` also has the entry type `@standard` for standards, which by default uses the same driver as `@misc`,  but of course can be configured to come out differently.

As I said, I would expect the `type` field of a `@report` entry to be more specific than just `standard` so that filtering on that field would be less likely/useful. For common filter task by entry type, `entrysubtype` and `keyword`s, `biblatex` has pre-defined options. For all other fields, you can use `\defbibcheck`, which in that case is not a workaround, but the intended interface.

The `biblatex` documentation never uses entry type to refer to the `type` field of an entry. *Entry type* always refers to the ... well ... entry type of an entry (the documentation assumes familiarity with the basic syntax of `.bib` files). So I think mentioning the `type` field more explicitly might confuse more than it helps.

**Comment by shmuelmetz** [comment]
Well, the documentation for type says "The type of a manual, patent, report, or thesis".
'
'.

**Comment by moewew** [comment]
There is a difference though between the `type` field and the *entry type*. As confusing as that may be that's what we're stuck with. I'll consider suggestions to make the documentation clearer, but I think this is a pretty niche issue and I fear that everything *I* could come up with to clarify the situation would actually make things less clear and more confusing.
