### ISSUE TITLE
Document and versus or for multiple instances of filtering keywords in \printbibliography

### ISSUE THREAD

**Issue by shmuelmetz** [plk/biblatex#1308]
Document in 3.8.2 The Bibliography  whether \printbibliography uses AND logic or OR logic when, e.g., keyword=, notkeyword=, occurs multiple times. E.g, does keyword=foo,keyword=bar select entries that have either foo or bar in keywords, or only entries that have both.

**Comment by moewew** [comment]
Let me know what you think about https://github.com/plk/biblatex/commit/b68f40b12167bc101399019fb88c972a3b70b4ec.

**Comment by shmuelmetz** [comment]
How about "If several <filtering options> are used, including keywords used multiple times,"?

I assume that if I want everything with a foo keyword and also everything with a bar keyword then I need to use  \defbibfilter?

Thanks.

--
Shmuel (Seymour J.) Metz
http://mason.gmu.edu/~smetz3
עַם יִשְׂרָאֵל חַי



________________________________________

**Comment by moewew** [comment]
Hmm. Is it not clear enough like this that this also applies if the same filter is used multiple times? I try to keep the sentences short, because the documentation is already long enough and because my German mind would otherwise produce really long monster sentences. (I also don't want to pick out `keyword` here in particular.)

Yes, if you want OR, i.e. all entries that have at least `foo` or `bar`, you need to combine them in a `\defbibfilter`.

**Comment by shmuelmetz** [comment]
I didn't find it clear enough. If you're worried about sentence length, how about "If several <filtering options> are used, an entry will only be printed if it satisfies all filtering conditions. Keywords used multiple times are considered distinct filtering conditions."

**Comment by moewew** [comment]
Alright, let me know what you think about https://github.com/plk/biblatex/commit/3ff687943fdd816f93ff0f37e727783ae7b4d52b.

**Comment by shmuelmetz** [comment]
Excellent! Thanks.
