### ISSUE TITLE
reference section

### ISSUE THREAD

**Issue by hvoss49** [plk/biblatex#1322]
In the documentation I read (p53)

> [...]
> subsection+  Start a reference section at every \subsection and every higher level of sectioning, i.e. \part, \chapter (if available) and \section.
> 
> The starred versions of these commands will not start a new reference section.

What is the meaning of the last sentence, because you first wrote that it _will start_ a new reference section??

**Comment by moewew** [comment]
That sentence refers to things like `\section*` and `\chapter*` as opposed to `\section` and `\chapter`. The patching we used to use would only affect numbered sectioning commands, so the unnumbered starred commands would not be patched and would not start a new section. Now that we use different patching mechanisms for different classes I'm not sure if we can guarantee that. I don't have time to check that right now, though. (And if it turns out that the behaviour is different for different classes I might just be willing to accept that rather than to figure out how to make everything behave the same. The whole business was really painful last time.)

**Comment by moewew** [comment]
How about we keep this around until we can actually verify how things currently stand with the starred macros.

**Comment by hvoss49** [comment]
I suppose that I understood the meaning, if it was:

> The starred versions of these commands (`\section*` and others) will not start a new reference section.

But maybe it is only a problem of my own, that I thought:  commands->biblatex

**Comment by moewew** [comment]
Hmm. As I said, I would have liked to keep this open until I've had a chance to look at this more closely. Please don't close issues that we explicitly say should be left open even if your issues are resolved. That makes it much easier for us to keep track of the things we need to keep track of.

I've had a quick look now and the intended behaviour at the moment is that both starred and unstarred sectioning commands are patched. So I removed the sentence. I also found a bug in our `memoir` patch, which I hopefully fixed.
