### ISSUE TITLE
Wrong translation in Spanish

### ISSUE THREAD

**Issue by Ivan-Brigidano** [plk/biblatex#1349]
After using `BibLaTeX` in Spanish and IEEE style I've found one small typo. The `url` is translated as `dirección` when it should be `[En línea]. Disponible en`. According to the `BibLaTeX-IEEE` developer, that package doesn't do anything directly here. So I was wondering if that is a problem of `BibLaTeX` itself or not. The MWE:

```
\documentclass[spanish]{article}
\usepackage{babel}
\usepackage{csquotes} % To avoid warning and change quotes.

\usepackage[style = ieee]{biblatex}
\bibliography{references.bib}

\begin{document}
    If I had finished writing the sentence citing~\cite{goossens1993},
    \printbibliography
\end{document}
```

Where `references.bib` is the following file:

```
@online{goossens1993,
    author    = "Michel Goossens and Frank Mittelbach and Alexander Samarin",
    title     = "The LaTeX Companion",
    year      = "1993",
    publisher = "Addison-Wesley",
    address   = "Reading, Massachusetts",
    url       = "example.com"
}
```

I know there is a workaround to solve it. But I just wanted to point out the issue here.

```
\DefineBibliographyStrings{spanish}{
	url = {[En línea]\adddot\addspace Disponible en},
	andothers = {\textit{et al\adddot}} % This translation is far more usual than the original.
}
```

**Comment by moewew** [comment]
IEEE requirements aside for a moment: Is *dirección* the obviously wrong thing to put in front of the URL in Spanish?

The core `biblatex` `.lbx` files have to choose one translation when translating strings and of course that style may not always work for all styles, so it is not unexpected that you may have to change a couple of translations in order to conform with certain requirements. Case in point: `biblatex-ieee` changes the English version of a couple of strings as well

https://github.com/josephwright/biblatex-ieee/blob/7f67eea42f55ee0c27c8358dd7cd64bf47ad4a4c/ieee.bbx#L67-L79

even the `url` string.

But it would break backwards compatibility pretty badly if we were to change between several possible translations willy-nilly. So there has to be a good reason to do that.

Finally, the core `biblatex` translations for `url` never contain a string like "[online]", so I don't want to add that just for Spanish, because that would make this translation inconsistent with all other languages.

**Comment by Ivan-Brigidano** [comment]
> Is _dirección_ the obviously wrong thing to put in front of the URL in Spanish?

No, _dirección_ is a perfectly correct translation. Only that it doesn't comply with IEEE standards. But reading your explanation I guess that the easiest solution will be to continue using the workaround I mentioned previously. Thanks!

**Comment by moewew** [comment]
I don't think it would be unreasonable to change this on the `biblatex-ieee` side especially given that the style does change the English localisation string here and has a dedicated `.lbx` file for Hungarian (so there is precedent for localisation apart from English). But I can see that it might be difficult to implement translations of a style that is inherently linked to English-language publications.

In any case, I don't think we can change anything in the core without breaking backwards compatibility, so I'm going to close this.
