### ISSUE TITLE
Language of citation keys

### ISSUE THREAD

**Issue by pauloney** [plk/biblatex#1402]
Can anyone shed light on what is going on here?

In the first entry the citation keys are -- in the respective language of the entries: 
    Hoffman e Kunze (1979)
    Hoffman y Kunze (1973)

In the second they use the language of the entry.
     Hoffman y Kunze (1961)

In the third they use English -- which is NOT the language of the entry!
      Hoffman and Kunze (1961)

I would expect that they would follow the language of the entry, but I am not sure I even understand what is happening.

I did check the `portuguese.lbx` file and it does contain the correct:

      and              = {{e}{e}},

````
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{polyglossia}
\usepackage{csquotes}

\setmainlanguage{english}
\setotherlanguage{portuguese}
\setotherlanguage{spanish}

%% Bibliographical citations:
\usepackage[style=authoryear,
            sorting=nyt,
            language=auto,
            autolang=other,
            backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@BOOK{Hoffman:71,
    title = {Linear Algebra},
    author = {Hoffman, K. and Kunze, R. A.},
    publisher = {Prentice-Hall},
    series = {Prentice-Hall Mathematics Series},
    address = {Englewood Cliffs, NJ},
    note = {Also available in Portuguese in \textcite{Hoffman-por} and Spanish in \textcite{Hoffman-spa}},
    year = {1961},
    langid = {english},
}

@BOOK{Hoffman-spa,
    address = {México},
    author = {Hoffman, K. and Kunze, R. A.},
    note = {Original en inglés en \textcite{Hoffman:71}},
    publisher = {Prentice-Hall Hispanoamericana},
    title = {Algebra Lineal},
    year = {1973},
    langid = {spanish},
}

@BOOK{Hoffman-por,
    title = {Algebra Linear},
    author = {Hoffman, K. and Kunze, R. A.},
    translator = {Adalberto P. Bergamasco},
    note = {Original em inglês em \textcite{Hoffman:71}},
    publisher = {Livros Técnicos e Científicos Editora S.A.},
    address = {Rio de Janeiro},
    year = {1979},
    pages = {356},
    langid = {portuguese},
}

\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
Lorem ipsum dolor!
\printbibliography
\end{document}
````

**Comment by moewew** [comment]
With `biblatex` v3.20 I get
![Hoffman, K. and R. A. Kunze (1961). Linear Algebra. Prentice-Hall Mathematics Series. Also available in Portuguese in Hoffman e Kunze (1979) and Spanish in Hoffman y Kunze (1973). Englewood Cliffs, NJ: Prentice-Hall.
— (1973). Algebra Lineal. Original en inglés en Hoffman and Kunze (1961). México: Prentice-Hall Hispanoamericana.
— (1979). Algebra Linear. Trad. por Adalberto P. Bergamasco. Original em inglês em Hoffman and Kunze (1961). Rio de Janeiro: Livros Técnicos e Científicos Editora S.A., p. 356.](https://github.com/user-attachments/assets/2a04835d-0299-4e18-9330-ac2eb7eaedb4)
So it appears to me that each "and" uses the language of the *cited* entry in each case.

This is what I expected, because `auto` changes the language of both citations and the bibliography. That said, citations in the bibliography are always a bit tricky (see e.g. https://github.com/plk/biblatex/issues/988 and linked discussions/posts): They can mess up punctuation tracking, since the punctuation tracker is global and not local. So if anything is wrong, it could be that the answer is: Citations in the bibliography are weird.

**Comment by pauloney** [comment]
Well, I can live with the output of 3.20. It is at least uniform on what it
does. I can't upgrade at the moment, because of issue #1377,  but just
knowing that it will work is nice.
