### ISSUE TITLE
Citations in tabularx environment

### ISSUE THREAD

**Issue by plk** [plk/biblatex#242]
With this MWE:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[british]{babel}
\usepackage{csquotes}
\usepackage[%
  defernumbers=true,
]{biblatex}
\addbibresource{test3.bib}
\usepackage{tabularx}

\begin{document}

\section{A section}
Check this out~\cite{gob}.

\section{A section}
% With plain tabular, it works with sorting=none or no sorting option.
% \begin{tabular}{p{0.6\textwidth}p{0.3\textwidth}}
%   \textbf{The term \enquote{issue} is used to refer to:} & \textbf{Reference(s)} \\ \hline
%   An issue. & \cite{michael}
% \end{tabular}

% With tabularx, it does not work with sorting=none.
\begin{tabularx}{\textwidth}{l l}
  \textbf{The term \enquote{issue} is used to refer to:} & \textbf{Reference(s)} \\ \hline
  An issue. & \cite{michael}
\end{tabularx}

\nocite{tobias}
\printbibliography
\end{document}
```

After the first run, with tabularx, the .aux only contains:

```
\abx@aux@cite{gob}
\abx@aux@cite{tobias}
```

whereas with plain tabular, is contains, as it should:

```
\abx@aux@cite{gob}
\abx@aux@cite{micheal}
\abx@aux@cite{tobias}
```

**Comment by moewew** [comment]
This came up in https://tex.stackexchange.com/q/468475/35864 again. In case it becomes important, here is a short 'report' of my findings.

The minimal example
```
\documentclass{article}
\usepackage{tabularx}
\usepackage[style=numeric, sorting=none, defernumbers=true, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{geer}

\begin{table}[htbp]
  \begin{tabularx}{\textwidth}{X}
    \cite{sigfridsson}
  \end{tabularx}
\end{table}

\cite{worman}
\end{document}
```
produces only `[0]`s instead of nice citation numbers. The MWE will also always ask for a Biber rerun.

The Biber rerun is triggered by a discrepancy between `\blx@cites` and `\blx@lastcites` (the latter compiled from the cite requests `\abx@aux@cite` from the `.aux`). The `.aux` file and hence `\blx@lastcites` will not contain keys cited for the first time in the `tabularx`.

The problematic step seems to be when

https://github.com/plk/biblatex/blob/95fa29346c400ed454fc651b7683040e02e0868e/tex/latex/biblatex/biblatex.sty#L10049-L10065

is executed within a `tabularx`. The particularly interesting bit is
```
  \ifinlist{#1}\blx@cites
    {}
    {\listgadd{\blx@cites}{#1}%
     \blx@auxwrite\@mainaux{}{\string\abx@aux@cite{#1}}}%
```

If the particular entry has not been cited before it will be added to `\blx@cites`, furthermore `biblatex` will write `\abx@aux@cite` to the `.aux` file. It is my understanding that during the measurement run the global assignments are performed, but `\write`ing is suppressed (`\blx@auxwrite` performs the `\write`). On the subsequent typesetting run the `<true>` branch will be executed since the key is already in `\blx@cites`, so the `\write` is never performed.

**Comment by davidcarlisle** [comment]
`\listgadd` could be made non-global on trial runs by tabularx or by biblatex (eg if `\ifx\hfuzz\@tempdima` is true) but if a citation appears in two cells I guess really you need the global def, so another alternative would be for tx to globally reset the blx@cites list at the start of each run as it does with the \cl@@ckpt

**Comment by moewew** [comment]
If there is a hook in `tabularx` I would probably just redefine `\blx@citation@entry` to avoid the global assignment during trial runs.

I don't think it should be `tabularx`'s job to reset `\blx@cites` or similar go through similar ordeals for all kinds of commands that have issues with being run and typeset multiple times. I'm also a bit uncomfortable with stuff such as `\hfuzz`, so a documented hook seems the most attractive solution.

**Comment by moewew** [comment]
As it happens, there seems to be a way to solve this issue completely on the `biblatex` side without any interference with `tabularx`.

Since `\abx@aux@cite` is only written to the `.aux` to build up the list `\blx@lastcites` for the next run, the exact place where `\abx@aux@cite` is written to the `.aux` does not matter as long as it is in the order given by `\blx@cites`. So we could remove the `\blx@auxwrite\@mainaux{}{\string\abx@aux@cite{#1}}` from `\blx@citation@entry` and execute it in a loop made from `\blx@cites` in `\AtEndDocument` instead.

```
\documentclass{article}
\usepackage{tabularx}
\usepackage[style=numeric, sorting=none, defernumbers=true, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\makeatletter
\def\blx@citation@entry#1#2{%
  \blx@bibreq{#1}%
  \ifinlist{#1}\blx@cites
    {}
    {\listgadd{\blx@cites}{#1}}%
  \ifinlistcs{#1}{blx@segm@\the\c@refsection @\the\c@refsegment}
    {}
    {\listcsgadd{blx@segm@\the\c@refsection @\the\c@refsegment}{#1}}%
  \blx@auxwrite\@mainaux{}{\string\abx@aux@segm{\the\c@refsection}{\the\c@refsegment}{\detokenize{#1}}}%
  \blx@ifdata{#1}
    {}
    {\ifcsdef{blx@miss@\the\c@refsection}
       {\ifinlistcs{#1}{blx@miss@\the\c@refsection}
          {}
          {\blx@logreq@active{#2{#1}}}}
       {\blx@logreq@active{#2{#1}}}}}
       
\AtEndDocument{%
  \begingroup
  \def\do#1{\blx@auxwrite\@mainaux{}{\string\abx@aux@cite{#1}}}%
  \dolistloop\blx@cites
  \endgroup
}

\begin{document}
\cite{geer}

\begin{table}[htbp]
  \begin{tabularx}{\textwidth}{X}
    \cite{sigfridsson} \cite{geer,nussbaum}
  \end{tabularx}
\end{table}

\cite{worman,nussbaum}

\printbibliography
\end{document}
```
seems to suggest this solves the problem.

**Comment by davidcarlisle** [comment]
that looks reasonable, I should probably still add a hook, but I was planning a tools release today (as I broke xr) and I'd rather not rush a change to tabularx so I may leave it if you don't need it urgently.  We are planning a more general review of adding hooks and customisation possibilities in latex, so it would be better to review tabularx as part of that activity.

**Comment by moewew** [comment]
From the `biblatex` side there is no need to rush the hook. We will probably not release another update in the near future, unless something really pressing comes along. I will write up an answer for https://tex.stackexchange.com/q/468475/35864 with the workaround from above and then I should probably investigate the implications of making this the default.

**Comment by moewew** [comment]
Update since this came up again in https://tex.stackexchange.com/q/499514/35864.

https://github.com/plk/biblatex/pull/878 with a fix for this issue has been merged. The solution differs from what I originally proposed above in that it *always* writes `\abx@aux@cite` and friends to the `.aux` file and not only on the first citation (as tracked by a global variable). The advantage of this approach is that  `\abx@aux@cite` is issued in the right spot in the `.aux` and doesn't pile in at the end as suggested above. The disadvantage is that we now write and thus call the macro multiple times (but I guess we can live with that).
