### ISSUE TITLE
Mismatched quotation marks (italic/roman) in title within title using uspunctuation

### ISSUE THREAD

**Issue by langeslag** [plk/biblatex#266]
When using `\uspunctuation`, periods and commas fall on the inside of quotation marks:

> _This Book Title Contains "Another Title."_

However, both quotation marks in the above example are still part of the containing title, and hence I would think both should appear in italics; or at least one should have this option using the `punctfont` package option. What I'm getting if I generate this situation in `biblatex` using `\mkbibquote` is an italic opening quotation mark and a roman closing quotation mark in both the note and the bibliography. The comma or period, incidentally, is italic if I have the option `punctfont` switched on, or roman if switched off. I can't seem to turn the closing quotation mark italic by issuing `\setpunctfont\emph`, presumably because it takes the period or comma as its object.

Note that this issue is a little harder to notice in Computer Modern, whose italic punctuation differs more subtly from its roman counterpart. Hence my MWE uses Cardo:

    \documentclass{book}
    \usepackage{fontspec}
    \usepackage[style=american]{csquotes}
    \usepackage{polyglossia}
    \usepackage[style=authortitle-ibid,punctfont=true]{biblatex}
    
    \uspunctuation
    
    \setdefaultlanguage{english}
    \setmainfont[Ligatures=TeX]{Cardo}
    
    
    \begin{filecontents}{book.bib}
    @Book{nussbaum,
      sorttitle	  = {Aristotle's De Motu Animalium},
      author	  = {Nussbaum, Martha},
      title		  = {Aristotle's \mkbibquote{De Motu Animalium}},
      publisher	  = {Princeton University Press},
      location	  = {Princeton},
      date		  = {1978},
    }
    \end{filecontents}
    \addbibresource{book.bib}
    
    \begin{document}
    
    The note and bibliography below should have both quotation marks printed in italics\autocite[55]{nussbaum}.
    
    \printbibliography
    
    \end{document}

![screenshot from 2014-08-13 14 48 42](https://cloud.githubusercontent.com/assets/3074180/3905476/3bac973a-22e8-11e4-97ce-bafbded37090.png)

**Comment by plk** [comment]
Any ideas about this one?

**Comment by moewew** [comment]
In case somebody is still interested in investigating this issue, it might be worth noting that it has to do with `puncthook` and `blx@imc@setpunctfont`. In the situation of the MWE we essentially need the punctfont twice: once for the period and once for the quotation mark. The period is correctly set in italics because it has the font information in its puncthook, after that is used it is deleted, and so the quotation mark does not get to see that font information. 

The entire issue is very interesting and maybe the opening quotation mark should try and "remember" its font choice and force that on the corresponding closing mark.

**Comment by distressingly** [comment]
Still actively an issue and, in fact, occurs even if the following punctuation is just a space (in which case the final quotation mark loses its italics).

**Comment by moewew** [comment]
Ah yes. This should probably be open.

But I don't think I can promise any progress here any time soon. Last time I looked (admittedly ten years ago as it turns out) this appeared to be very tricky. The only way to resolve this that I could think of at the time would have involved saving and restoring the active font settings and I'm not even sure if that is realistically possible.
