### ISSUE TITLE
Feature request: normalizes page-range in postnote

### ISSUE THREAD

**Issue by dpfu** [plk/biblatex#293]
Biblatex should normalize the page-rage of the `postnote` the same way `biber` normalizes the page-range of the `page` field, e.g. it changes a hyphen (`-`) to an en-dash (`--`). So for consistency `\autocite[12-14]{foo}` should result in the same output as `\autocite[12--14]{foo}`.

One way to get this behavior is to mis-use `\mkcomprange` like this (see http://tex.stackexchange.com/questions/225308/page-range-output-hypen-as-en-dash-in-autocite/225338#225338):

```
\setcounter{mincompwidth}{100000}%something large
\DeclareFieldFormat{postnote}{\mkcomprange[{\mkpageprefix[pagination]}]{#1}}
```

So the code is already there, it only needs an interface. Any chance?

**Comment by plk** [comment]
This looks reasonable to me - @aboruvka, @josephwright - would either of you be able to look at this?

**Comment by josephwright** [comment]
@plk  Issue is can we be sure of picking up page numbers in the note: the text can be anything, at least in principle.

**Comment by plk** [comment]
This is indeed true and I suspect why it hasn't been attempted yet - disambiguating range dashes form any other sort of potential dashes in an arbitrary string is not a particularly fun TeX task.

**Comment by dpfu** [comment]
I use the hack mentioned above and haven't run into any problems yet. I'm no expert, but `\mkcomprange` seems the know which dashes are range dashes. It doesn't touch the note text otherwise. Incomplete ranges are normalized, so if you use something strange like this  `\autocite[8-]{foo}` you get "Foo (2001, 8–". You can find an working example here: https://www.overleaf.com/2173570ycknyg

**Comment by josephwright** [comment]
@dpfu Of course in this case it works, but I guess my worry is the general semantics of the optional argument. Can we be *certain* it only ever represents a page number (range)?

**Comment by nickbart1980** [comment]
We cannot really be certain. Just one example: "2-1" could be a page number, and "2-1–2-15" a page range; see http://www.nasa.gov/sites/default/files/files/appendix2.pdf.

**Comment by maieul** [comment]
I think it should be nice, if this feature provided.

**Comment by maieul** [comment]
in the case mentionne by @nickbart1980, we could provide normalization as optional, and disabled by default.

**Comment by u-fischer** [comment]
@josephwright: No we can't be sure that the optional argument represents a page number or range. But biblatex seems to be quite good at handling this already: 
"[883-890]"  gets  the range prefix in print: "pp. 883-890", 
"[883]"  gets the page prefix: "p. 883"
"[Kap. 883-890] " or "[§4b]" are printed as is. 
And the already mentioned \mkcomprange doesn't break over "non-page" input either.

**Comment by plk** [comment]
Shall we close this?

**Comment by maieul** [comment]
maybe integrated this feature as optional?

**Comment by plk** [comment]
@josephwright  - I think we should pick this up for consistency with how `biber` does things.

**Comment by moewew** [comment]
It was straightforward to extract the range normalisation code from `\mkcomprange`, so it is entirely possible to define a `\mknormrange` that replaces hyphens by `\bibrangedash` and commas and semicolons by `\bibrangesep`, but does not compress any page ranges.

This command could then be used as
```
\DeclareFieldFormat{postnote}{\mkpageprefix[pagination][\mknormrange]{#1}}
```

Since `\mkcomprange`/`\mknormrange` internally execute an `\ifpages` test, they are no worse (but also no better) equipped to deal with arbitrary input than `\mkpageprefix`. (`\mkpageprefix` thinks `2-1` is a page range even if it is a 'NASA page number'.)

@plk I think most users would want
```
\DeclareFieldFormat{postnote}{\mkpageprefix[pagination][\mknormrange]{#1}}
```
can we make it the default, or would that be too problematic wrt backwards compatibility?

I'm working on a few last details, but as soon as they are fixed, I will submit a pull request for you to have a look at. Comments as to whether `\mknormrange` is a good name are of course appreciated.

**Comment by moewew** [comment]
See the `mknormrange` branch: https://github.com/plk/biblatex/compare/dev...moewew:mknormrange

**Comment by plk** [comment]
You are the expert here ... are there backwards compat issues that you are worried about? It makes sense to me.

**Comment by moewew** [comment]
Yes, backwards compatibility could be an issue if we go with
```
\DeclareFieldFormat{postnote}{\mkpageprefix[pagination][\mknormrange]{#1}}
```
I am biased, because I like the normalisation feature and think this is how `biblatex` should handle things. So I'm inclined to think that the changes are going to be minor and actually beneficial to the average user, but I'm not sure if that can justify changing the field format of a widely used field.

**Comment by plk** [comment]
I have no problem with that as long as we put it in the CHANGES.md file as an incompatible change and perhaps put in the older definition for people who want to copy/paste it.

**Comment by dpfu** [comment]
As the OP I’m glad and thankful that this got finally implemented, imho it’s a sensible default. I just want to thank everyone for the continued great work, you’re awesome!

**Comment by moewew** [comment]
OK, then I think its is reasonable to make normalisation the default and document this as breaking change with hints on how to get the old behaviour back.

These changes will not make it to the 3.10 release, so we will have the incompatibility warning upfor a while (in the wiki) until it becomes relevant. Maybe this can help the few people that actually read release notes and have a problem with this change to take action or to complain.

Of course everybody subscribed to this discussion is invited to comment on the proposed changes, especially with regards to the incompatibility issues.

@dpfu Thank you for getting back to us even though this is quite an old issue by now. Sorry it took so long, but I could only now muster up the courage to tackle this issue, I actually thought it would be more complicated.

**Comment by moewew** [comment]
`biblatex` 3.11 now normalises page ranges in the postnote by default.

`biblatex` 3.11 and Biber 2.11 are on CTAN now. They arrived in MikTeX this morning. Because we didn't make the TeX live freeze, TeX live 2017 will not get the update and we will only be in TeX live 2018. TeX live pretest has the new versions
