### ISSUE TITLE
uniquename considers name affixes, not just last name

### ISSUE THREAD

**Issue by aboruvka** [plk/biblatex#306]
I have long assumed that uniquename disambiguates non-unique last names. However it seems the name affix is considered as well, even though this doesn't form part of the label name by default.

The following outputs "F. Smith S. (2015), J. Smith S. (2015), Brown (2015), and Brown (2015)".

```latex
\documentclass{article}
\usepackage[style=authoryear,uniquename]{biblatex}

\begin{filecontents}{\jobname.bib}
@book{smith1,
  author = {Smith, Senior, Frank},
  title = {Title},
  year = 2015
}
@book{smith2,
  author = {Smith, Senior, Joe},
  title = {Title},
  year = 2015
}
@book{brown1,
  author = {Brown, Senior, Bob},
  title = {Title},
  year = 2015
}
@book{brown2,
  author = {Brown, Junior, Tom},
  title = {Title},
  year = 2015
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\textcite{smith1,smith2,brown1,brown2}
\end{document}
```

**Comment by plk** [comment]
Hmm, would you think that the best thing is to include the suffix in the labelname or stop considering the suffix for uniquename?

**Comment by aboruvka** [comment]
From the way the documentation reads (and I think this is the right way to go), a unique last name (and last name prefix if `useprefix` is enabled) should give `uniquename=0`. All remaining name parts, including the affix, are then used in the label name only for disambiguation.

In the example I was expecting: "F. Smith S. (2015), J. Smith S. (2015), B. Brown S. (2015), and T. Brown J. (2015)" and if the package is instead loaded with `uniquename=mininit`: "F. Smith (2015), J. Smith (2015), B. Brown (2015), and T. Brown (2015)".

**Comment by plk** [comment]
I have committed a biber fix to stop using the suffix when generating disambiguation information for uniquename which correctly generates your first expected example. However, the one with `uniquename=minints` is tricky because it needs standard style changes I think. Biber's uniqueness routines dont' generate any information about whether to display the suffix (the never did - you found a the case where they implicity used the suffix to choose to display initials/names). The standard styles would need to be changed to stop printing the suffix when using `mininit` or `minfull`. It's not clear to me that this is necessary though since disambiguation doesn't include suffices and so the "minimal" disambiguation option settings shouldn't either?

**Comment by plk** [comment]
That's true - I haven't looked at citations yet.
