### ISSUE TITLE
Incompatibilities with texh4t

### ISSUE THREAD

**Issue by simifilm** [plk/biblatex#310]
I don't know whether this belongs here or should go to the `tex4ht` bug tracker, but there are currently serious issues when trying to use `biblatex` and `tex4ht`.

Take the following MWE:
````
\documentclass{article} 

\begin{filecontents}{test.bib} 
@book{Hiemenz, 
author={Hiemenz}, 
title={Polymer Chemistry} 
} 
\end{filecontents} 

\usepackage{hyperref} 

\usepackage[backend=biber, hyperref=auto, backref=true]{biblatex} 
\bibliography{test} 
\begin{document} 

Here comes a quotation \cite{Hiemenz}. 

\printbibliography 

\end{document}
 ````

When running the sequence `mk4ht oolatex tesfile – biber tesfile – mk4ht oolatex testfile`, no error is produced, but the resulting ODT file doesn't contain the resolved citation.

And this is only with the simplest MWE. With a more complex document I get all kind of strange errors, which are rather hard to debug. I guess my real question is whether the respective developers are aware of the problems.

**Comment by plk** [comment]
I wasn't aware that bibaltex  ever really worked properly with tex4ht ... did it?

**Comment by aboruvka** [comment]
It mostly did awhile back, but not since tex4ht's author (Eitan Gurari) passed away unexpectedly. Maintainers have since volunteered, but the issues with biblatex that have since cropped up are pretty involved - I wouldn't expect them to be fixed soon.

**Comment by simifilm** [comment]
So should I file a bug with the tex4ht bug tracker?

**Comment by aboruvka** [comment]
You could try. In the interim you could roll back to whatever version of biblatex/biber was around the last time Eitan updated tex4ht. From what I remember it worked fine as long as you weren't doing anything complicated with citation labels.

**Comment by moewew** [comment]
@simifilm While dealing with [this TeX.SX question](http://tex.stackexchange.com/q/234669/35864) I found that `biblatex` support for recent versions in `tex4ht` is possible and has in fact been implemented. The relevant files (that is `biblatex.4ht` mainly, I imagine) don't seem to have made their way into an official release though (at least not in MikTeX), you can find a fairly new file at http://texdoc.net/texmf-dist/tex/generic/tex4ht/biblatex.4ht.

Whether this is ready to be released so that all people can use it is something you could bring up with the `tex4ht` maintainers.

PS: It seems that most problems with the repository version of `tex4ht` are resolved by this
[Tex4ht, biblatex and biber: what is proper processing?](http://tex.stackexchange.com/q/27288/35864).

**Comment by simifilm** [comment]
Thanks, but AFAICS the new file doesn't make any difference.

**Comment by simifilm** [comment]
Could it be that the latest changes from dev have caused new incompatibilities?

**Comment by moewew** [comment]
Just checked it again, if I use `htlatex test`, `biber test`, `htlatex test` everything works like a charm (I could not use `mk4ht` because I didn't have a configuration file at hand.).

Did you also make sure that the new version of `biblatex.4ht` was actually loaded - the `.log` file reports the version, mine is `2015-02-04-14:23`.

**Comment by simifilm** [comment]
Yes, the correct version of `biblatex.4ht` is loaded. The `.bbl` file which contains the relevant information is also loaded, but `biblatex` still insists that the citation `Hiemenz` is undefined. Which version of `biblatex/biber` did you use? I use the latest changes from dev branch.

**Comment by moewew** [comment]
I use the current release version 2.9a with Biber 1.9. Of course I cannot be sure, but I wouldn't have thought that the changes since 2.9a to the dev branch will have caused such a loss in functionality.
When you say the `.bbl` file which contains the relevant information was loaded, did you make sure that it at that point contained all the relevant information - I'm not sure about `mk4ht`, maybe it deletes temporary files before proceeding; as I said above, with `htlatex` it works fine, did you try that?

**Comment by simifilm** [comment]
Last time I posted, I tried with `htlatex`. I just tried it on a second machine with the same result (which is also is on dev branch). You can get the log file here: https://www.dropbox.com/s/qr2zggd7ha4wbvh/teste.log?dl=0

**Comment by moewew** [comment]
Mhhhh, your `.log` file heavily suggest that something with the `.bbl` file went wrong, even though it exists it does not seem to contain the information needed to resolve the citations.
The warnings etc. we then see are then very similar to what one would expect if one didn't run Biber.

Check what's inside the `.bbl` file.

Other than that you could try and downgrade to release versions of `biblatex` and Biber and try again, those worked here.

**Comment by simifilm** [comment]
Here's the `.bbl` file: https://www.dropbox.com/s/97h74o21lswbvsu/teste.bbl?dl=0

**Comment by simifilm** [comment]
Ok, it's definitely the changes from dev branch. With `biblatex` 2.9a everything works as it should.

**Comment by moewew** [comment]
OK, maybe you want to find out what commit exactly caused the trouble, if you can spare the time.

**Comment by plk** [comment]
I strongly suspect that if tex4ht adapted to the biblatex's new .bbl format a while ago where labelname was explicitly resolved by biber, then the DEV version change where I removed this and now do the resolving in biblatex is to blame. Maybe you can check if tex4ht expects to find an explicit labelname field in the .bbl?

**Comment by moewew** [comment]
@simifilm  I'm slightly confused about the `.bbl` file you posted, it states `$ biblatex bbl format version 2.4 $`, but the dev version of Biber would make that read `2.5` instead, maybe you just ran into trouble because your `biblatex` and Biber versions are not compatible.

**Comment by simifilm** [comment]
The irritating format version is probably caused by the fact that the `.bbl` file changed in the meantime, since I've tried with `biblatex` 2.9a. Well, I guess we have located the problem. I'm not quite sure though what would be the best way to track down the specific change responsible for it.

The MWE of this bug report was only the beginning for me, so to speak. I have a quite long document which produces all kind of other `biblatex` errors when I try compile it with `tex4ht`. But since it relies on a version of `biblatex-fiwi` which is adapted to `biblatex` 3.0, hunting bugs becomes a bit difficult ATM.

**Comment by moewew** [comment]
I thought since you said you use the dev version, you might have pulled it from github, you could then just go back the commits and find out which caused the problem (skipping those that only meddled with localization and documentation). The commit plk mentioned is the one from 2014-12-21, so if you were to pull the 2012-12-14 version and verify that it works and then the 2014-12-23 version and verify that it does not work we could isolate the problem.

**Comment by simifilm** [comment]
I guess I'm too dumb for `git`, but I'm not really sure how I can revert to a specific point.

**Comment by plk** [comment]
If you are using the git version and running "Build install" etc. then you can just make sure you are on the DEV branch (git checkout dev) and then checkout the specific commit using the hash mentioned on github. For the 2014-12-21 commit, that's "git checkout 1484ced". You can then "Build install" and when you want to go back to the latest commit of dev, just do "git checkout dev". There is also a nice command "git bisect" which automates finding the commit which broke something (see, for example, http://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git).

**Comment by simifilm** [comment]
Just a short update: I was too stupid to exactly find the point where the relevant change was made, but the problem persists with biber 2.1/biblatex 3.0. 

There are two additional errors, when running `tex4ht` which I think are related to `biblatex`:

````
! Package biblatex Error: Patching 'ifthen' package failed.

! Package biblatex Error: Patching \MakeUppercase failed.
````

**Comment by simifilm** [comment]
I forgot this:

````
! Package biblatex Error: Patching \MakeLowercase failed.
````

**Comment by simifilm** [comment]
This is fixed on the tex4ht side, see here: https://puszcza.gnu.org.ua/bugs/?252
