### ISSUE TITLE
Context sensitive translations

### ISSUE THREAD

**Issue by ahomansikka** [plk/biblatex#328]
Are there any examples on how localization keys "book", "involumes" and "volumes" are used? Their correct translations to Finnish depends on context.

**Comment by plk** [comment]
@aboruvka - this is probably in your area ...

**Comment by aboruvka** [comment]
From biblatex.def:
```latex
\DeclareFieldFormat{volume}{\bibstring{volume}~#1}% volume of a book
\DeclareFieldFormat{volumes}{#1~\bibstring{volumes}}
```
AFAIK the default styles don't make use of the `book` or `involumes`. If they did, we'd probably have something like:
```latex
\DeclareFieldFormat{book}{\bibstring{book}~#1}
\DeclareFieldFormat{volumes}{\bibstring{involumes}~#1~\bibstring{volumes}}
```
so that `book` is akin to `volume`, but refers to part of collection of books instead of volumes, and `involumes` is the preposition in a phrase like "in 12 volumes".

**Comment by ahomansikka** [comment]
Are "involumes" and "volumes" supposed to be used only in phrase like "in 12 volumes"? Then Finnish translations are

involumes        = {{}{}},

volumes          = {{osassa}{osassa}},

So that "in 12 volumes" is translated as "12 osassa".

**Comment by aboruvka** [comment]
Generally, yes. The plural forms are used to describe the total number of volumes in a collection, so "12 volumes" or "in 12 volumes". However we can't always anticipate how style authors might use the strings.

**Comment by ahomansikka** [comment]
That's a problem in Finnish, because

"12 volumes" is "12 osaa" in Finnish, but "in 12 volumes" is "12 osassa". Finnish language does not use prepositions but case endings.

**Comment by aboruvka** [comment]
Prepositions aren't easy to handle in some languages, but there are ways around it - see `smartand` in spanish.lbx or `smartof` in french.lbx, for example. In your setting the `involumes` string could print nothing (as you have defined above), and in addition ensure that an alternative string for `volumes` is printed later on.

However since `involumes` isn't used in the standard styles, I would just leave this potential problem up to style authors. The translations you've given seem fine to me.
