### ISSUE TITLE
\AtEndBibliography / \AtEndShorthand ; \AtEndBiblist

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#335]
Should it be possible to add these three commands which will do the same thing as \AtBegin… commands, but at the end ?

**Comment by moewew** [comment]
While you are waiting for an official answer on this, you might want to have a look at `\blx@endbibliography` and `\blx@endbiblist` and find a nice place to insert your code there.

So it seems not entirely impossible to implement such a thing, I'm just not too sure in which group of `\blx@endbibliography` exactly one would hook the `\AtEndBibliography` into. (Probably - I'm wildly guessing here - either right before or after `\csuse{blx@endenv@\blx@theenv}`.)

Have a short proof of concept here

```
\newrobustcmd*{\AtEndBibliography}{\gappto\blx@hook@bibend}
\@onlypreamble\AtEndBibliography

\newrobustcmd*{\AtNextEndBibliography}{%
  \ifundef\blx@hook@bibend@next
    {\gdef\blx@hook@bibend@next{\global\undef\blx@hook@bibend@next}}
    {}%
  \gappto\blx@hook@bibend@next}

\def\blx@endbibliography{%
  \csuse{blx@hook@bibend}%
  \csuse{blx@hook@bibend@next}%
  \csuse{blx@endenv@\blx@theenv}%
  \blx@noitem
  \endgroup
  \blx@bibnote\blx@thepostnote
  \endgroup}
```


When I tried testing this I found what this command would do quite pointless, because everything I would do via `\AtBeginBibliography` would be consigned to a group in the bibliography environment anyway. (And so would be the `\AtEndBibliography` code, but maybe we need to move the code to the end. - see the alternative definition below) So I couldn't for the life of me think of an application, hence this is untested and might toast your kitten if you try it.

```
\def\blx@endbibliography{%
  \csuse{blx@endenv@\blx@theenv}%
  \blx@noitem
  \endgroup
  \blx@bibnote\blx@thepostnote
  \endgroup
  \csuse{blx@hook@bibend}%
  \csuse{blx@hook@bibend@next}%
}
```

**Comment by maieul** [comment]
formely, I have done solve my problem with \newcommand{\mybibliography}[1][1]{\printbibliography[#1]what i want at end}. I have just opened it for a general implementation.
-----

**Comment by moewew** [comment]
Depending on what is in "what i want at end", maybe the `postnote` option to `printbibliography` is enough?

**Comment by maieul** [comment]
it is not enough, because it is for a particular bibliography, and not for all bibliographies


Le 28 ao�t 2015 � 06:48, moewew <notifications@github.com> a �crit :

**Comment by moewew** [comment]
OK, I guess we will see what the powers that be think about this issue. But just out of interest, which placement of ` \csuse{blx@hook@bibend}` and ` \csuse{blx@hook@bibend@next}` in `def\blx@endbibliography` fits your use case best?

**Comment by maieul** [comment]
I think it should be coherent with AtBeginBibliography:
- inside the \bgroup if AtBeginBibliography is inside, outside in other case
- with a concentric structure. For example if the begin have this structure:
-* AtEvery
-* AtNext
-* Optional argument
The end should have the reverse : 
-* Optional
-* AtNext
-* AtEvery

(maybe this order should also be documented)

**Comment by maieul** [comment]
ps : example of use  : print the total entry in a bibliography. See http://geekographie.maieul.net/184

**Comment by moewew** [comment]
I thought about having the AtNext - AtEvery structure, but then I thought it much more logical for an `\AtNextEnd*` to override an `\AtEnd*` (which is what currently happens with the `\AtBegin` and `\AtNext`), so the order AtEvery - AtNext is more natural.

For your use case it is also not beneficial to place the hooks in exact analogy to the begin hooks inside the bibliography environment, as this will make the text appear directly in the last item.
There

```
\def\blx@endbibliography{%
  \csuse{blx@endenv@\blx@theenv}%
  \blx@noitem
  \endgroup
  \csuse{blx@hook@bibend}%
  \csuse{blx@hook@bibend@next}%
  \blx@bibnote\blx@thepostnote
  \endgroup}
```

might be more useful.

(BTW: I'm pretty sure in your link you miss a `{` in the second line of the definition of `\biblioavectotal`: it says `Il y a \therefs} entrées dans cette bibliographie.` prematurely closing the `\newcommand{`. Also shouldn't `\newcommand[1][1]{\biblioavectotal}` be `\newcommand{\biblioavectotal}[1]`?)

**Comment by maieul** [comment]
Le 28 ao�t 2015 � 12:40, moewew <notifications@github.com> a �crit :

> I thought about having the AtNext - AtEvery structure, but then I thought it much more logical for an \AtNextEnd* to override an \AtEnd* (which is what currently happens with the \AtBegin and \AtNext), so the order AtEvery - AtNext is more natural.
> 

You are right

> For your use case it is also not beneficial to place the hooks in exact analogy to the begin hooks inside the bibliography environment, as this will make the text appear directly in the last item.
> There
> 
> \def\blx@endbibliography{%
>   \csuse{blx@endenv@\blx@theenv}%
>   \blx@noitem
>   \endgroup
>   \csuse{blx@hook@bibend}%
>   \csuse{blx@hook@bibend@next}%
>   \blx@bibnote\blx@thepostnote
>   \endgroup}
> 
> might be more useful.
> 

also right ;-)
> (BTW: I'm pretty sure in your link you miss a { in the second line of the definition of \biblioavectotal: it says Il y a \therefs} entr�es dans cette bibliographie. prematurely closing the \newcommand{. Also shouldn't \newcommand[1][1]{\biblioavectotal} be \newcommand{\biblioavectotal}[1]?)
> 

} was a mistak. But [1][1] is good. It's enable the first argument be optional.

**Comment by moewew** [comment]
Yes, but it will make the optional argument read "1" to TeX if it wasn't specified. Which at my end rightly gives `Package keyval Error: 1 undefined.` from `bIblatex`. So you really want `\newcommand{\biblioavectotal}[1][]{...}`.


Anyway, I feel that the whole *in which group does the command belong* question is not fully resolved. With what we have above the new command is essentially just a permanent `postnote`. I feel the the `\AtBeginBibliography` is most often used to modify the bibliography layout (renew some punctuation commands, change the name format etc.) and since it is kept local, there is no real demand for a corresponding `\AtEndBibliography`.

But again, it is for the maintainers to decide whether the feature is worthwhile, the implementation seems easy enough if you get past the design issues of where exactly to put the hooks.

**Comment by maieul** [comment]
oh, you are right again. I have made confusion with the newcommandx syntaxis ;-)

**Comment by aboruvka** [comment]
The "end" here isn't clear - the last item or outside the list? Moreover you already have `\defbibenvironment`.
