### ISSUE TITLE
Reduce code redundancies

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#375]
With the recent change in name formats it was necessary to split the `.def` files for the BibTeX and Biber backends. 

Of the 2800 lines that `biblatex_.def` contains, however, the difference to `biblatex_legacy.def` is ~200 lines in name macros (that was to be expected) and another ~500 lines in Biber-only Declare... commands.

I think it would be beneficial to reduce the amount of duplicated code by having a `biblatex.def` that contains backend-agnostic stuff and say `biblatex_bibtex.def` and `biblatex_biber.def` for the backend-dependent code.

Ultimately, it would be nice to have this for the `.sty` files as well, I believe, though the fragmentation there is much greater.

**Comment by plk** [comment]
This is already being taken up by @josephwright. I did this to make the codepaths clearer and to avoid breaking bibtex during major biber related changes.

**Comment by josephwright** [comment]
As noted, I'm already on this: see https://github.com/josephwright/biblatex/commits/backend (currently in a fork as this is tricky work and is best handled at one remove).

@plk  and I split the BibTeX and Biber code entirely some time ago, with the idea being that this allowed continued development of Biber whilst keeping the BibTeX version stable. However, that was based on the idea that the Biber changes would be largely 'additions' with no divergence of existing behaviours. That looked sensible at the time but less so now, so a rethink is in order.

My current plan is to take the Biber-specific code and to re-add the BibTeX parts, generalising the BibTeX stuff where possible and adding no-ops or similar where not. This should result in easier switching between back ends with useful warnings in the log rather than undefined control sequences where BibTeX simply doesn't support stuff (or where Biber offers a better way than BibTeX).

I need a little while to work on this. Current estimate is roughly 1 month to do the initial merge, then testing _etc._ @plk  can then liaise about release: I suspect this might count as a 'major' version change!

**Comment by moewew** [comment]
That is great news! I just ran a diff between the `.sty` files and found that many differences I saw were related to line breaks and typos, newer syntax - could one introduce the optional argument to `\DeclareBibliographyOption` for BibTeX as well? -  as well as some macros that exist for Biber, but not in BibTeX (I'm not sure if that is intentional in all cases).

**Comment by josephwright** [comment]
@moewew Indeed: several of the divergences are not _required_ as they can be handled by BibTeX. I just need to work through them all carefully.

**Comment by josephwright** [comment]
Note for self. There will need to be some work on the `.bst` file as well as the LaTeX code: doesn't look like it's been updated since PL vanished. In particular, the current `.bst` gives for example
```
  \name{author}{3}{}{%
    {{}%
     {Arduengo}{A.}%
     {Anthony~J.}{A.~J.}%
     {}{}%
     {III}{I.}}%
    {{}%
     {Harlow}{H.}%
     {Richard~L.}{R.~L.}%
     {}{}%
     {}{}}%
    {{}%
     {Kline}{K.}%
     {Michael}{M.}%
     {}{}%
     {}{}}%
  }
```
whereas for the same input Biber generates
```
      \name{author}{3}{}{%
        {{hash=af291d5167ed86a92583be000896058d}{%
           family={Allen},
           family_i={A\bibinitperiod},
           given={R.\bibnamedelimi A.},
           given_i={R\bibinitperiod\bibinitdelim A\bibinitperiod}}}%
        {{hash=ea942b005b5f82e7ba7d90978b8555f1}{%
           family={Smith},
           family_i={S\bibinitperiod},
           given={D.\bibnamedelimi B.},
           given_i={D\bibinitperiod\bibinitdelim B\bibinitperiod}}}%
        {{hash=ddf0fed863f62684f7b9a73d05904950}{%
           family={Hiscott},
           family_i={H\bibinitperiod},
           given={J.\bibnamedelimi E.},
           given_i={J\bibinitperiod\bibinitdelim E\bibinitperiod}}}%
      }
```
With the exception that the hashes have to be different for the two backends, this should all be doable (just a bit tedious for me).


@plk Is there a list somewhere for (current) format differences between the `.bbl` files?

**Comment by plk** [comment]
Not really, I bump the .bbl version number when the .bbl format changes but I've been loathe to touch bibtex .bst etc. as this was supposed to be "frozen" but clearly this isn't really working.

**Comment by josephwright** [comment]
@pl

**Comment by josephwright** [comment]
@plk  The 'frozen' plan was based around all Biber changes being strictly additive, but that's not worked out. (I have to say I'd not realised you'd not added in such features as could be handled by BibTeX, but I guess that's not surprising now I think about it as I guess you don't have  much knowledge of the stack language used.)

**Comment by josephwright** [comment]
This is now completed
