### ISSUE TITLE
`\printbibliography` does not honor `resetnumbers=false`

### ISSUE THREAD

**Issue by DigNative** [plk/biblatex#443]
I am using biblatex in version 3.4. As the `prefixnumbers` option has been removed, I had to rework my documents in order to restore a correct labeling of entries within the multiple bibliographies inside my document. An issue I am facing now is that the numbers of the entries of each bibliography are reset every time I call the `\printbibliography` macro with the option `resetnumbers` set to `false`. MWE:

    \documentclass{article}
    \usepackage{filecontents}
    \usepackage[
        defernumbers=true
    ]{biblatex}

    \begin{filecontents}{\jobname.bib}
        @article{article,
            title = {Article Title}
        }
        @book{book,
            title = {Book Tile}
        }
        @misc{misc,
            title = {Misc Title}
        }
    \end{filecontents}
    \addbibresource{\jobname.bib}

    \begin{document}

        \cite{article} \cite{book} \cite{misc}

        \printbibliography[type=book]

        \newrefcontext[labelprefix=A]
        \printbibliography[type=article, resetnumbers=false]
        \printbibliography[type=misc, resetnumbers=false]

    \end{document}

In my interpretation of the `biblatex` documentation, the entry in the last bibliography should be labeled with `[A2]`, not with `[A1]`. I faced the same issue before with the `prefixnumbers` option of `\printbibliography`, but had the following workaround available (which is also not working anymore, of course):

    % The `prefixnumbers = {}' argument in `\printbibliography' is implemented in such a way
    % that `resetnumbers' is always called. That makes it impossible to continue numbering
    % with the same prefix across multiple sections. The following code simply sets the prefix
    % in BibLaTeX internally, without calling `resetnumbers'.
    \makeatletter
        \def\blx@prefixnumbers{A}
    \makeatother

Which chance do I have to get my desired functionality of a continuous numbering across bibliographies with the same prefix back?

**Comment by plk** [comment]
I think this is really a bug. I have addressed it in the DEV release. To use the 3.5 DEV version, you'll need biber 2.6 DEV version too. In your example, the last bibliography should be `[A3]` since you print three bib items and don't reset at all. I suppose you intend to reset only once, after the first bib - this works nicely for me with the latest 3.5 version, getting `[A2]` for the last bibliography. A `resetnumbers=false` on the second `\printbibliography` gets `[A3]`. So now you can get any result you need without hacking internals.

```
\cite{article} \cite{book} \cite{misc}
\printbibliography[type=book]
\newrefcontext[labelprefix=A]
\printbibliography[type=article]
\printbibliography[type=misc, resetnumbers=false]
```
I have changed the documentation to mention that the "reset when labelprefix exists" behaviour is overridden by explicit use of the option. This historical behaviour is just a convenience I think, in that people expect that if/when they change labelprefix, the numbers reset but the problem was that labelprefix definitions can now scope over multiple `\printbibliography` macros and so it has to be possible to block this behaviour ... now you can.

**Comment by DigNative** [comment]
Thank you really much for your fast answer and your modifications in the development version! Please excuse the mistake in my MWE --- you are right: `resetnumbers` should have been set to `true` in the second `\printbibliography` command. As a consequence of this mistake, the numeric part in the labels in the bibliographies should simply be continued. Anyway, the slightly incorrect MWE demonstrated the issue.

I had the chance now to try your `biblatex` 3.5 development version (together with the 2.6 developer version of `biber`) and I can confirm that the issue has been solved with these changes. Thank you very much for your fast action!

**Comment by plk** [comment]
Thanks for reporting this - it really was an annoying bug for people I think.
