### ISSUE TITLE
incomplete math support

### ISSUE THREAD

**Issue by aueelis** [plk/biblatex#458]
I was testing biblatex 3.5 with biber 2.6-dev (downloaded 2016-08-08) and noticed that some references were improperly formatted: A title defined as `title = {{The molecule A${}_{2}$B${}_{3}$}}` gets printed as

> The molecule A_2B_3.

instead of

> The molecule A₂B₃.

Compiling the document with biblatex 3.4 reverts to the old expected behavior. Please note that in both cases the numbers are printed in the selected math font (i.e., math mode is not completely disabled).

Is this a bug/regression or are we now forced to use `\textsubscript`?

**Comment by plk** [comment]
Hmm, that's odd, the .bbl looks fine with both pdflatex and lualatex for me but you are right that it doesn't work properly. @josephwright - do you have a clue where we might start looking? Seems to be a biblatex rather than biber issue.

**Comment by moewew** [comment]
I'm just guessing here, so feel free to ignore me.

Wasn't there something about the character codes in `.bbl` files because of the name parts having an `_i` appended for initials? (This also caused slight problems with another package, I seem to remember, see [TeX.SX: Capacity exceeded error](http://tex.stackexchange.com/q/321119/35864).)

**Comment by plk** [comment]
Yes, that was the issue @moewew, thanks for reminding me. I have changed the .bbl format in DEV now to remove the underscore and so there is now no need to change the _ catcode and this issue is fixed.

**Comment by aueelis** [comment]
Fix confirmed. Thanks!
