### ISSUE TITLE
Dot missing after year in @periodical entry using authoryear style

### ISSUE THREAD

**Issue by ivalb** [plk/biblatex#554]
Consider the following MWE:
```
\begin{filecontents*}{\jobname.bib}
@Periodical{jcg-2,
  Title                    = {BIS-Computers and Graphics},
  Subtitle                 = {A subtitle},
  Year                     = {2011},
  Number                   = {4},
  Volume                   = {35},
  ISSN                     = {0097-8493},
  Issuetitle               = {Semantic {3D} Media and Content}
}
\end{filecontents*}

\documentclass{article}

\usepackage[style=authoryear]{biblatex}
\addbibresource{biblatex-examples.bib}
\addbibresource{\jobname.bib}

\begin{document}

\cite{jcg} (from biblatex-examples.bib).

\cite{jcg-2} (from this file)

Missing dot after (2011) in the bibliography.

Subtitle missing for \textcite{jcg-2} in the bibliography.

\printbibliography

\end{document}
```

The dot after the year label is missing in both the entries inside the bibliography. And in the second entry the subtitle is missing too.

Ivan

**Comment by moewew** [comment]
Mhhh this is more or less expected since we have `\setunit{\printdelim{nametitledelim}}\newblock`. So that delimiter can be overwritten by subsequent `\setunit`s. In this particular case it is overwritten by the first `\setunit*{\addspace}%` from `title+issuetitle`. I'm not sure if it is a good idea to use `\printunit` here.

The `subtitle` is not printed since the title was already printed and then cleared (to avoid repetition), but `periodical` reads
```
\newbibmacro*{periodical}{%
  \iffieldundef{title}
    {}
    {\printtext[title]{%
       \printfield[titlecase]{title}%
       \setunit{\subtitlepunct}%
       \printfield[titlecase]{subtitle}}}}
```

So far the analysis of the problem. I'm not sure yet if there is a good solution for any of these. I would welcome comments.

**Comment by ivalb** [comment]
Considering that the problem occurs only for periodical entries and and only when the title is missing, a test could solve the issue. In fact, the title is not missing but it is cleared, so it is missing for the date+extrayear macro... The test prints a \newunitpunct and the subtitle (if defined).
```
\usepackage{xpatch}
\xapptobibmacro{date+extrayear}{%
\ifboolexpr
   {
    test     {\ifentrytype{periodical}}
    and test {\iffieldundef{title}} 
   }
   {\newunitpunct%
    \iffieldundef{subtitle}
    {}
    {\printtext[title]{%
       \printfield[titlecase]{subtitle}}}
   }
   {}}{}{}

```

**Comment by moewew** [comment]
This is not a problem that is specific to `@periodical`, though. It can appear with all entry types if (1) `author`, `editor`, `translator` are all missing, and (2) the entry has a subtitle. In that case the `title` is taken as the 'label' before the year, it is then `\clearfield{title}`'d, since most title printing macros later on in the driver check for missing `title`s, we don't get to see the subtitle.

Do I take it from your code that you would prefer to see the `subtitle` directly after the title even in this situation?

**Comment by moewew** [comment]
One solution I could offer is to bring the relevant macro (and some other ones) in line with other titling macros so that the subtitle is printed after the year. Cf https://github.com/moewew/biblatex/commit/dbead55cffe67924590a2f88f7a363ba31316486

**Comment by moewew** [comment]
The `\printunit` change is at https://github.com/moewew/biblatex/commit/895af551aad3eefce09d77bd536ebd90c2898bf2, but it would need very thorough testing before I would merge this (if at all).

@plk any comments on the `\setunit`/`\printunit` thing (https://github.com/moewew/biblatex/commit/895af551aad3eefce09d77bd536ebd90c2898bf2)? And what do you think about https://github.com/moewew/biblatex/commit/dbead55cffe67924590a2f88f7a363ba31316486?

**Comment by plk** [comment]
Both look ok to me ... but the `\printunit` change would need testing, yes.

**Comment by moewew** [comment]
OK, I seem to remember asking myself why `\printunit` wasn't used there in the first place after it was introduced, but I can't remember if anyone had a reason for that or if it just wasn't done.

Unfortunately, I won't have time over the weekend. But I can submit pull requests you can have a look at.

**Comment by plk** [comment]
@moewew  - I am thinking of a new release shortly - can we close off what we can in the next week?

**Comment by moewew** [comment]
Sorry, I was away over the weekend. I'm not so sure about `\printdelim`. It is better in some situations and worse in others. At the moment, I don't want to rush things and would vote not to merge #557, so things stay as they are in that regard and we can think about it a little more.

**Comment by moewew** [comment]
Closing this for now. I think the `\printunit` change here is a bit too dangerous and the use case here is obscure enough that it doesn't matter too much. If a more pressing case pops up we may have to reconsider.
