### ISSUE TITLE
Bib extras and bib strings for all languages 

### ISSUE THREAD

**Issue by odomanov** [plk/biblatex#560]
I'd like to have some bib extras and/or bib strings the same for all languages. What is the appropriate hook for that? Does it exist?

**Comment by moewew** [comment]
Would those blanket definitions overwrite the settings of the `.lbx` files? Should they overwrite explicit settings done with `\DefineBibliographyStrings` from the document preamble?

Would you like a command for the `.lbx` file, or one for the document preamble?

**Comment by moewew** [comment]
@odomanov Can you give a few more details about your use case here, please?

**Comment by moewew** [comment]
@odomanov I came across this again because of a question on TeX.SX. And I agree that it could be nice to have something like this. but to be sure that it makes sense and that we are talking about the same, thing it would be really appreciated if you could explain what exactly you had in mind. Would this be a macro for `.lbx` files? (probably not) Should this be user accessible in the preamble? (yes, I'd say) In what order do overrides work? ( `.lbx`>all language > specific language?)

**Comment by plk** [comment]
I did look at this briefly as I remember - it's not trivial due to the way that the language interface macros are defined.

**Comment by moewew** [comment]
I had a look at this again and it is indeed far more complicated than I had initially hoped. I'll close this for now since the request is lacking details. We can reopen this if a use case for this emerges and the details are decided upon.
