### ISSUE TITLE
Unexpected output of \textcite with shorthand

### ISSUE THREAD

**Issue by ivalb** [plk/biblatex#569]
As shown in [https://tex.stackexchange.com/questions/249205/unexpected-output-of-textcite-with-shorthand](url) the \textcite command produces an unexpected output when a shorthand is defined. Briefely, we have
- \cite{kant:kpv} => KpV. This is ok!
- \parencite{kant:kpv} => (KpV). This is ok!
- \textcite{kant:kpv} => **Kant (KpV)**. This is unexpected! I would expect **KpV**.

It would be simple to redefine \textcite to work as \cite when there is only one entry. But \textcite can take multiple keys, each of which can have a shorthand or not. For example: "Knuth (1984) and KpV" or "KpV and KU".

The solution from tex.stackexchange only partially fix this bug (if it is really a bug) as shown in the example below. When \textctite takes two or more keys for which a shorthand is defined, only the first entry is typeset correctly. Briefly we have
- \textcite{kant:kpv,kant:ku} => **KpV and Kant (KU)**. I would expect **KpV and KU**

Moreover it adopts an extra-biblatex approach and it would be better an internal solution.

```
%Example from: https://tex.stackexchange.com/questions/249205/unexpected-output-of-textcite-with-shorthand

\begin{filecontents}{myfile.bib}
@book{goossens93,
    author    = "Michel Goossens and Frank Mittelbach and Alexander Samarin",
    title     = "The LaTeX Companion",
    year      = "1993",
    shorthand = "GMS"
}

@book{else2015,
    author    = "Someone Else",
    title     = "Interesting thing.",
    year      = "2015"
}
\end{filecontents}

\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}

\usepackage[backend=biber,citestyle=authoryear]{biblatex}
\addbibresource{myfile.bib}
\addbibresource{biblatex-examples.bib}%<===Added line

\usepackage{xparse}
\let\oldtextcite\textcite

\DeclareDocumentCommand{\textcite}{ O{} o m }{%
    \AtNextCitekey{\iffieldundef{shorthand}{}{\clearname{labelname}}}%
    \IfNoValueTF{#2}%
        {\oldtextcite[#1]{#3}}%
        {\oldtextcite[#1][#2]{#3}}}
\DeclareDocumentCommand{\textciteLong}{ O{} o m}{%
    \AtNextCitekey{\clearfield{shorthand}}%
    \IfNoValueTF{#2}%
        {\oldtextcite[#1]{#3}}%
        {\oldtextcite[#1][#2]{#3}}}

\begin{document}

\begin{itemize}
    \item Entry without shorthand: \textcite{else2015}
    \item Entry with shorthand: \textcite{goossens93}
    \item Ignore the shorthand: \textciteLong{goossens93}
\end{itemize} 

%
% Added lines
%
\section*{Counterexample}

If \verb|\textcite| takes two or more keys only the first entry is typeset in the expected form:
\begin{itemize}
    \item Two entries with a shorthand: \textcite{kant:kpv,kant:ku}
\end{itemize} 

\end{document}
```

Cheers
Ivan

**Comment by moewew** [comment]
Mhhh, this behaviour has been there since as long as I use `biblatex` (and I think it is safe to assume it has been like this from the very beginning). So even though the output might be counterintuitive for some (for me as well), I'm very wary of changing it.

Maybe the reasoning went as follows (of course I'm speculating). When `\textcite` is used, it gives an output of the form 'Name <label>' where the name and the label together uniquely identify the reference. In some styles <label> on it is own is enough to determine the reference. Here Name is meant to play the role of subject (maybe object) in a sentence and <label> should give a non-intrusive way to refer to the reference.
That's why we write `\textcite{sigfridsson} found that ...` to obtain 'Sigfridsson and Ryde (1998) found out that ...'. Because the author is the subject, we can't just leave her out when there is a shorthand. 'KpV found that ...' vs. 'Kant (KpV) found that ...'.

**Comment by ivalb** [comment]
Ok, you convinced me. Actually \textcite has been created for such cases. Anyway I would prefer "For further details see KpV" to "For further details see Kant  (KpV)" and in these cases I have to remember if the entry has a shorthand or not. In the first case I will use \cite, otherwise I will use \textcite. In fact this is not a big problem but it would be helpful to have a command, suppose \textcite, which gives the shorthand if defined (just like \cite, \parencite), and a command, suppose \puretextcite, for the form "Name (label)"

**Comment by moewew** [comment]
It should not be too complicated to write a command like this. So I'm not sure if it warrants inclusion in the `biblatex` kernel.
