### ISSUE TITLE
Handling of Norwegian languages

### ISSUE THREAD

**Issue by hansfn** [plk/biblatex#615]
The two written languages in Norway is Bokmål (Norwegian Bokmål - code **nb**) and Nynorsk (Norwegian Nynorsk - code **nn**). They are not similar so there should be separate translations. 

Since Bokmål is the most common language it is ok that "norsk" / "norwegian" is an alias for "Bokmål". (The code **no** is actually deprecated.)

So, the answer to the question inside norsk.lbx, 

> 'norsk' and 'nynorsk' use the same translations, correct?

is no.

**Comment by plk** [comment]
I'm happy to have separate .lbx for nynorsk if you would like to submit one?

**Comment by moewew** [comment]
We already have a `nynorsk.lbx` where some entries differ from `norwegian.lbx` (and `norsk.lbx` which inherits `norwegian.lbx`).  `babel` uses the language identifiers `norsk` (for Bokmål, I assume) and `nynorsk` (for Nynorsk). I'm not sure how `norwegian` as identifier came into play, as far as I can see `polyglossia` doesn't use it either.

We can certainly remove the obviously incorrect status comment.

In any case feel free to submit changes also to `nynorsk.lbx`.

Not sure if we should drop `norwegian.lbx` in favour of `norsk.lbx`.

**Comment by plk** [comment]
@moewew - this is a good point - I can't see how `norwegian.lbx` is useful as a file name. Thereis a long standing feature request to switch to standard BCP47 language identifiers and I did some work in this direction a couple of years ago and biber is able to map the polyglossia/babel identifiers to BCP47 but really implementing this requires changes in babel/polyglossia to use standard codes rather than their own names ...

**Comment by hansfn** [comment]
Yes, babel uses `norsk` for `Bokmål` so I recommend that babelbib uses it too (in stead of `norwegian`). The language option is normally a global/class option in LaTeX documents so the different packages should agree.

I didn't notice that `nynorsk` existed as a separate file/translation because of the incorrect status comment. In some sense that makes this issue obsolete.

I can update the `nynorsk` translation when/if I get time. It's not my preferred Norwegian language ;-)

**Comment by moewew** [comment]
I have now removed the misleading status comment.

So are we all agreed that `norwegian.lbx` should be dropped? I noticed that it has been there since v1.7, but I can see no good reason for it seeing that neither `babel` nor `polyglossia` use it.

**Comment by plk** [comment]
Agreed.

**Comment by moewew** [comment]
OK, I have packed up a pull request. Testing would of course be appreciated.

**Comment by hansfn** [comment]
Since I have your attention and this might be a problem just for `nynorsk.lbx`: 

I notice that the "organizer" strings haven't been inserted. I assume it's an automatic/build process to update all languages with new/missing strings? If so, maybe nynorsk has been left out from the process? Or it's just a manual error.

I'm of course happy to create a separate issue if you want.

**Comment by moewew** [comment]
Normally we insert new bibstrings manually. There is no automatic build process. The only upside to adding empty strings to the `.lbx` is that translators see immediately that the strings are not translated yet, there is no technical reason to add the strings. Especially with other files it is entirely possible that some strings were left out. Translators should check completeness of their files against https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex Missing keys will cause a warning and will appear in bold.

**Comment by moewew** [comment]
Also note that `nynorsk.lbx` is special since it inherits from `norsk.lbx`. So it should only contain changes from `norsk.lbx`. The working assumption (that may well be wrong) is that it is not a bad idea to assume that the inheritance of strings makes sense. If you think that it is too much of an assumption, we may have to split the files explicitly. 

I noticed that the `organizer` bibstrings were not commented. This might cause them not to be bold in the output, so I changed that. https://github.com/plk/biblatex/commit/2b7af4cf9e1432aba3a0d828f987f792289fc9b2

**Comment by hansfn** [comment]
Yes, I noticed the inheritance. Having Bokmål as fallback is better than English of course, but I would guess that more than 80 % of the translation will be different. I'll leave the decision too you.

Sorry to ask in stead of just testing: Will missing keys in `nynorsk.lbx` be detected (ref your comment above) when it inherits from `norsk.lbx`?

**Comment by moewew** [comment]
Well, if we now split up the files and drop the inheritance without anybody having a look at `nynorsk.lbx` we might render `nynorsk.lbx` virtually unusable. So no matter how bad the status quo is, I'm afraid things will be worse if we split without competent help.

No, since missing strings are inherited from `norsk.lbx` only those strings that are missing in both `nynorsk.lbx` and `norsk.lbx` will be reported as missing. For testing you could probably comment out the inheritance instruction in the `.lbx`.

**Comment by hansfn** [comment]
I'm competent - just busy (as you probably are as well). 

I suggested that if/when I or somebody else submits an up to date, complete nynorsk translation, you remove the inheritance. Nynorsk users don't like to see Bokmål in their writings :-)

**Comment by perstar** [comment]
But a complete translation won't stay complete automatically. Especially the set of languages (langX and fromX) can be expected to be further extended many more times. Won't most (almost all?) languages have the same name in nb and nn?

**Comment by hansfn** [comment]
It's a matter of opinion, I guess. Using English as fallback (no inheritance) makes it very clear that an updated translation is needed motivating someone to fix it. Some Bokmål mixed with Nynorsk can go undetected ... Which can be used as an argument for keeping the inheritance. I don't have a strong opinion about this.

PS! Yes, most/all language names are the same, but all fromX strings will be different ("fra" => "frå").

**Comment by plk** [comment]
@hansfn - is there a chance you could provide the two relatively complete `.lbx` files in the next couple of weeks?

**Comment by hansfn** [comment]
@plk Yes, I can do nynorsk.lbx later this week. Is norsk.lbx also incomplete?

**Comment by moewew** [comment]
You can use https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex to check all localisation keys. A quick run showed that a few language names are missing in `norsk.lbx`: `langjapanese`, `langslovak`, `langukrainian`, as well as their `from...` versions.

**Comment by hansfn** [comment]
Thx. I hadn't forgotten about 03-localization-keys.tex. I'm just lazy and was hoping to just edit directly here on GitHub.

**Comment by hansfn** [comment]
@plk I have just created a pull request - see #624 

PS! I noticed that nynorsk.lbx has both `\InheritBibliographyStrings{norsk}` and 

```
\DeclareBibliographyStrings{%
  inherit          = {norsk},
```
That seems redundant.

**Comment by moewew** [comment]
Yes, I think that line can be dropped. See https://github.com/plk/biblatex/commit/9564a0991d08cb79474f1726ada45dd1292bd5c5.

Can we close this issue or is there something left to address or discuss?

**Comment by hansfn** [comment]
I'm fine with closing it - done! (If some one disagrees, just reopen.)
