### ISSUE TITLE
@set still gives odd results for authoryear, authortitle, and verbose styles

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#619]
Set behaviour is improved for non-numeric styles following the recent round of patches, but the following MWE fails to print any citations for `authoryear` and `authortitle` citation style, and only prints the first citation for `verbose` style.

```TeX
\documentclass{article}
\usepackage[style=verbose]{biblatex}% also check style=authortitle and style=authoryear
\addbibresource{biblatex-examples.bib}
\begin{document}
\cite{set}

\cite{set}
\printbibliography
\end{document}
```

**Comment by moewew** [comment]
That is because there is currently no `labelname`, `labeltitle`, `labelyear` etc. assigned to a (parent) `@set` entry. We didn't have any intuition as to how those fields should be populated.

In my head `@set`s really only make sense for numeric citations, and if the user assigns a fixed label for the `@set` manually, also for alphabetic styles.

**Comment by plk** [comment]
Yes, this is still "pending" really. It is a departure from the previous behaviour since before, set parents were a data copy of the first set child for precisely this reason. I'd like some input on how this should be handled. As is stands, in non-numeric styles, nothing is printed unless there is a label/labeltitle (`authoryear`) or a shorthand (`authortitle`/`verbose`).

**Comment by moewew** [comment]
Here is what we could do

1. Concatenate (in a nice way) the labels of all children to obtain the `@set`'s label
   - In the example that could give 'Herrmann et al. 2006, Aksın et al. 2006 and Yoon et al. 2006'
2. 'Collect' the `labelname`, `labelyear`
    - 'Herrmann et al., Aksın et al., Yoon et al. 2006, 2006, 2006'
3. Force the user to supply a `shorthand`.

**Comment by plk** [comment]
Sounds fine but quite complex if done in `biblatex` itself. I wonder if we might recommend that a `biber` sourcemap is used to construct a `label` field in such cases? I think the `bibtex` case is as it always was as it processes sets in different ways.

**Comment by moewew** [comment]
Actually, I think 1) could be done in `biblatex` by detecting a `@set` and looping over all `entryset`/child entries in an `\entrydata` (that is assuming that all child entries actually get processed by Biber for `labelname` and all that is involved). But - and that is a big but - this would need significant changes in macros that have been stable for a very long time.

At first glance I don't think 2) could be easily implemented.

For `authoryear`/`authortitle` there is good reasons to take the `label...` data from the first child (i.e. the behaviour with version 3.7). After all, the set will be sorted there and the label is 'just' a pointer to the bibliography. But that causes the problem that a `@set` cannot be distinguished from its first member.
It would also have negative effects for `\textcite` in numeric styles.

Frankly I think sets are just not fit to be used with `authoryear`/`authortitle`-like styles. If a user wants to stuff several entries into one, the `related` feature might be more appropriate.

@dcpurton Do you happen to have a real-world use case for `@set` in an `authoryear`/`authortitle`/`verbose`-like style?

**Comment by plk** [comment]
Yes, I started to look at (1) in exactly the way you mention but it's fiddly and requires adding a macro call to every cite command in several styles.

**Comment by plk** [comment]
One thing I can do for sets in biber is, unless they have their own explicit label, make a label from the member labels automatically by concating them? This will make the set label different from the first member label at least and will also guarantee a label. I can also make a default label somehow as a fallback.

**Comment by moewew** [comment]
Mhhh, in principle I like the idea. Especially for `alphabetic` that could make sense.

But for `authoryear`/`authortitle` it will probably make finding then right item in the bibliography harder.

**Comment by plk** [comment]
I'm inclined, since it's not even obvious that many people would need sets in non-numeric styles anyway (otherwise we would have had more questions about it), to put something in the doc about the necessity of ensuring labels/shorthands manually or via sourcemaps for such cases.

**Comment by dcpurton** [comment]
I quite like how `@set` entries are working in the dev version of `biblatex-sbl` now (not in CTAN yet). It's similar to the `verbose` style. I don't have the problem where subsequent citations don't show up (although I'm not sure why at the moment).

I'll see if I can modify the above MWE to implement things in the same way and you can have a look.

**Comment by dcpurton** [comment]
Having said that, I wouldn't actually use a `@set` with `biblatex-sbl`. I agree it doesn't make sense. I'm really just trying to make sure it gives sensible results in case someone does.

**Comment by dcpurton** [comment]
This is essentially what I've done in `biblatex-sbl` (although in a different way). But @moewew is right. I can't think why you'd actually want to do this in the real world. The only reason I implemented it was to try and support all the standard entry types from the `biblatex` manual.

```TeX
\documentclass{article}
\usepackage[style=verbose]{biblatex}
\usepackage{hyperref}
\addbibresource{biblatex-examples.bib}
\makeatletter
% new \blx@imc@labelentryset macro
\let\blx@imc@labelentryset\blx@imc@entryset
\patchcmd{\blx@imc@labelentryset}
  {\begingroup}
  {\let\abx@field@setkey\abx@field@entrykey
   \begingroup}
  {}
  {}
\patchcmd{\blx@imc@labelentryset}
  {\blx@entryset}
  {\blx@labelentryset}
  {}
  {}
% new \blx@labelentryset macro
\let\blx@labelentryset\blx@entryset
\patchcmd{\blx@labelentryset}
  {\blx@driver{\blx@imc@thefield{entrytype}}}
  {\usebibmacro{cite:short}%
   \blx@setunit\entrysetpunct}
  {}
  {}
\patchcmd{\blx@labelentryset}
  {\blx@entryset@i}
  {\blx@labelentryset@i}
  {}
  {}
% new blx@labelentryset@i macro
\let\blx@labelentryset@i\blx@entryset@i
\patchcmd{\blx@labelentryset@i}
  {\blx@driver{\blx@imc@thefield{entrytype}}}
  {\usebibmacro{cite:short}%
   \blx@setunit\entrysetpunct}
  {}
  {}
% define \labelentryset macro
\blx@regimcs{\labelentryset}
% define bibhyperlink field format to deal with entry sets
\DeclareFieldFormat{bibhyperlink}{%
  \bibhyperlink{\iffootnote{f}{t}:\cbx@resetcount:%
    \ifbool{bbx@inset}
      {\thefield{setkey}}
      {\thefield{entrykey}}%
    }{#1}}
% redefine cite:short
\renewbibmacro*{cite:short}{%
  \ifentrytype{set}
    {\booltrue{bbx@inset}%
     \labelentryset{}{}}
    {\printnames{labelname}%
     \setunit*{\printdelim{nametitledelim}}%
     \printtext[bibhyperlink]{%
          \printfield[citetitle]{labeltitle}}}}
\makeatother
\begin{document}
\cite{herrmann}

\cite{aksin}

\cite{yoon}

\cite{set}

\cite{herrmann}

\cite{aksin}

\cite{yoon}

\cite{set}

\printbibliography
\end{document}
```

**Comment by plk** [comment]
This would be really messy to implement nicely for a generally suspicious use-case. Looking into it, we would need to, as @moewew says, inject a set test into the relevant cite commands in those styles and then loop over all labelnames constructing something to print. Ideally, we'd just construct a labelname and let the normal code print it but this is really messy to do. A simple solution would be to just copy the labelname/labelyear etc. from the first set member, which is essentially what happened before. Since this solution is basically not very useable and no-one has ever really complained, I doubt anyone really ever does this so I'd rather document it and mention that adding labels/shorthands to set parents is the thing to do if you really want to do this.

**Comment by maieul** [comment]
Personnaly, I use `@set`:
- to cite `Bibliotheca Hagiographica Latina`, `Bibliotheca Hagiographica Latina`, `Novum auctarium bibliothecae hagiographicae graecae` as individual title in the main body of the text
- but to merge them in "one entry" in the bibliography, and especially in the list of claves (biblbatex-clave package)

So `@set` with verbose typesetting would be very useful.

**Comment by moewew** [comment]
@maieul OK, but would be the output you expect from David's MWE? I.e. what should a second citation to a `@set` in `verbose` style look like. What should it look like in `authortitle` and `authoryear`. What would you expect for the specific use case in your documents?

**Comment by maieul** [comment]
I never cite the `@set` entry directly. I only use main entry. The `@set` is cited only in the final bibliography.

**Comment by plk** [comment]
So, is it agreed we can document this and then close?

**Comment by moewew** [comment]
From my point of view, yes. Just mention that things work 'as expected' for `numeric`-like styles and that users need to supply label/shorthand information for the `@set`  in all other styles. We should probably mention that the otherwise things might fail in such a way that there is no output from a citation command at all. (This is really unfortunate, but I can't think of a way to avoid that without further side-effects.)
