### ISSUE TITLE
Uppercased marks with the standard classes

### ISSUE THREAD

**Issue by johannesbottcher** [plk/biblatex#627]
Right now, the marks are `\MakeUppercase`d for the standard classes, whereas there are the right macros for KOMA classes (and memoir).

```
\documentclass{article}
\usepackage{biblatex}
\usepackage[markcase=used,automark]{scrlayer-scrpage}
\addbibresource{biblatex-examples.bib}
\begin{document}
\section{WomBat}\clearpage
\nocite{*}
\printbibliography
\end{document}
```

In the MWE above, the marks should be `used`, but biblatex sets them uppercased. 

Is there any chance to branch of a few more lines of code, or should that be better patched by the user?

Thanks

**Comment by moewew** [comment]
What would you suggest here? Do we need to detect `scrlayer-scrpage`'s settings and act accorfingly or is there an easier way out?

**Comment by johannesbottcher** [comment]
I fear it would be detecting the package. But `noupper` might just be what i did overlook. 

But then again, this is *template business* :-(

**Comment by moewew** [comment]
Maybe someone who knows KOMA could have a look at our KOMA defaults https://github.com/plk/biblatex/blob/d0e866e1ee99027bbad5d530f8bd5b14f593fb6e/tex/latex/biblatex/biblatex.def#L1803-L1871 and tell us if things could be done in a better way.

**Comment by moewew** [comment]
I never really got the hang of the KOMA packages - aside from happily using their defaults and the occasional high-level option.

Should our headings behave as they do for KOMA classes once `scrlayer-scrpage` is loaded or is there more to it?

**Comment by johannesbottcher** [comment]
Hard week, i would need to look at it closer tomorrow. 

```
\documentclass{article}
\usepackage{biblatex}
\usepackage{scrlayer-scrpage}
\addbibresource{biblatex-examples.bib}
\begin{document}
\section{WomBat}\clearpage
\nocite{*}
\printbibliography
\end{document}
```
This MWE gives a header for the Refs, whereas none for the WomBat section, because headers weren't yet *demanded*. 
Unnumbered sections/chapters do not apply any `\mark*` commands by default (KOMA or standard), which is what most users do not expect. But if a mark should be set or not is a matter of opinion. 

`scrlayer-scrpage` is a package from the KOMA bundle, but can be used with the standard classes, which makes this a bit more tricky.

**Comment by moewew** [comment]
A slight tangent, but while we are at it.

> In addition to the commands of the standard classes, KOMA-Script offers the new commands \addsec and \addchap. They are similar to the standard commands \chapter and \section, except that they are unnumbered. They thus produce both a running heading and an entry in the table of contents.

as well as a short test indicate that `\markboth` can probably be dropped in most KOMA definitions.

**Comment by johannesbottcher** [comment]
Yes, probably. But there are also the starred version `\addchap*` and `\addsec*`which are unumbered and clear the marks not to have the marks of the previous chapter or section in the header.

**Comment by moewew** [comment]
Yes, I noticed that as well. And and I don't think it solves our problems, just makes the code shorter.

**Comment by johannesbottcher** [comment]
I'll take a closer look tomorrow, or maybe on sunday.

**Comment by moewew** [comment]
OK, brilliant. I will leave this for the time being. I lack the insight into KOMA and the subtleties of chapter headings, running heads and headers.

**Comment by johannesbottcher** [comment]
`markboth` can be dropped from almost all KOMA definition. Especially the ones with `\chaptermarkformat` look fishy. KOMA-script takes care of the proper heading with the proper formatting.  

```
\documentclass{report}
\usepackage{blindtext}
\usepackage{fancyhdr}
\pagestyle{fancy}
\usepackage{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\chapter{WomBat}\clearpage
\blindtext[10]
\nocite{*}
\printbibliography
\end{document}
```
I am not a big fan of `fancyhdr` but it shows something: biblatex always uses  `markboth`  to set left *and* right marks. The usual classes (standard, KOMA, memoir) only set the left mark with every new chapter (clearing the right mark at the same time) while sections only set the right mark.

Reference link for a recent problem: [Page header with references at end of each chapter](https://tex.stackexchange.com/a/394181/37907)

The question is, should we have a meta command for a mark mechanism which is used in the different definitions of bibheadings? Or is it enough to use `\defbibheading` to define the heading along with the marks? It wouldn't be too much code for a user.

**Comment by moewew** [comment]
For KOMA classes we should probably follow `\bib@heading` as closely as possible. Unfortunately for us, that command features some 'internal' tricks from time to time.

The standard classes (`article.cls`, `report.cls`, `book.cls`) all use `\@mkboth` for the heading in `thebibliography`.
```
\documentclass{report}
\usepackage{blindtext}
\usepackage{fancyhdr}
\pagestyle{fancy}
\begin{document}
\chapter{WomBat}\clearpage
\blindtext[10]
\nocite{*}
\begin{thebibliography}{22}
\bibitem{foo01}foo and bar
\bibitem{foo02}foo and bar
\bibitem{foo03}foo and bar
\bibitem{foo04}foo and bar
\bibitem{foo05}foo and bar
\bibitem{foo06}foo and bar
\bibitem{foo07}foo and bar
\bibitem{foo08}foo and bar
\bibitem{foo09}foo and bar
\bibitem{foo10}foo and bar
\bibitem{foo11}foo and bar
\bibitem{foo12}foo and bar
\bibitem{foo13}foo and bar
\bibitem{foo14}foo and bar
\bibitem{foo15}foo and bar
\bibitem{foo16}foo and bar
\bibitem{foo17}foo and bar
\bibitem{foo18}foo and bar
\bibitem{foo19}foo and bar
\bibitem{foo20}foo and bar
\bibitem{foo21}foo and bar
\bibitem{foo22}foo and bar
\bibitem{foo23}foo and bar
\bibitem{foo24}foo and bar
\end{thebibliography}
\end{document}
```
gives similar output. So even though this does not give ideal output, at least we do what the standard classes do as well.

At the moment I'm not sure what kind of meta-command you have in mind.
Seeing that the standard classes give sub-par results as well, I think we don't need to introduce a new command/option, the user will just have to redefine the heading (which is much easier than in standard `thebibliography` already) if they need something else. But I'm prepared to be persuaded, if you think it would be useful.

**Comment by komascript** [comment]
IMHO you never should use `\markboth` but `\@mkboth`, because even with the standard classes using `\markboth` would result in unexpected results:

    \documentclass{article}
    \usepackage{biblatex}
    \pagestyle{myheadings}
    \begin{document}
    \markboth{Documenttitle}{Written by me}
    \section{WomBat}\clearpage
    \nocite{*}
    \printbibliography
    \end{document}

Pagestyle `myheadings` per specification is a page style without automatic but manual heading. But biblatex does not respect the manually set headings but forces its own (REFERENCES). But if biblatex would use `\@mkboth` instead of `\markboth` it would respect the settings:

    \documentclass{article}
    \usepackage{biblatex}
    \makeatletter
    \defbibheading{bibliography}[\refname]{%
      \section*{#1}%
      \@mkboth{\MakeUppercase{#1}}{\MakeUppercase{#1}}}
    \makeatother
    \pagestyle{myheadings}
    \begin{document}
    \markboth{Documenttitle}{Written by me}
    \section{WomBat}\clearpage
    \nocite{*}
    \printbibliography
    \end{document}

So I think, the main problem is using `\markboth` instead of `\@mkboth`.

Back to KOMA-Script: In the early days of KOMA-Script support in biblatex I've send a bug report that suggested to use something like

    \defbibheading{bibliography}[\refname]{%
      \begingroup
        \def\bibname{#1}\let\refname\bibname
        \bib@heading
      \endgroup
    }

for the KOMA-Script default setting. This would automatically respect KOMA-Script options like `bibliography=numbered` or `toc=bibliography` or … and in our days also `bibliography=leveldown`. So biblatex wouldn't need to recognize and react on all these options on its own. I don't know whether or not this would be a good idea in our days, because inspecting the cooperation of KOMA-Script and biblatex is on the TODO list of KOMA-Script for many years but unfortunately never has been done.

**Comment by moewew** [comment]
Thank you very much for taking time to look into this.

The `\markboth` -> `\@mkboth` change sounds sensible and is the right thing to do if we want to be in line with the standard classes anyway.

A dedicated `\bib@MakeUppercase` looks tempting, especially since we use `\memUChead` for memoir already. We could unify the approach.

I can't say why your suggestion about
```
\defbibheading{bibliography}[\refname]{%
  \begingroup
    \def\bibname{#1}\let\refname\bibname
    \bib@heading
  \endgroup
}
```
wasn't taken up. It looks like it would be far less work for `biblatex`, but maybe there were technical reasons against it. I will investigate that.

Currently `biblatex`'s standard headings do a fairly decent job at guessing what should be done to comply with the KOMA settings, while the other headings can be used to override KOMA-decisions explicitly.

If there is anything that `biblatex` could do to ease the cooperation between `biblatex` and KOMA, don't hesitate to give us a shout here.

**Comment by komascript** [comment]
@moewew 
> I can't say why your suggestion about
>
>     \defbibheading{bibliography}[\refname]{%
>       \begingroup
>         \def\bibname{#1}\let\refname\bibname
>         \bib@heading
>       \endgroup
>     }
>
> wasn't taken up.

Maybe because it would result in a recusion (if `#1` is `\refname` → `\def\bibname{\refname}\let\refname\bibname` → `\def\refname{\refname}`.) So you need some more code to do it.

If it helps, I can add a command `\bibliography@heading` that accepts an argument. Internally I would change `\bib@heading` to use `\bibliography@heading` in this case. So the change would be compatible to the current implementation and you could use

    \defbibheading{bibliography}[\refname]{\bibliography@heading{#1}}

But in this case a new biblatex would need a new KOMA-Script class too. So I do not know, whether or not this is a good suggestion.

**Comment by moewew** [comment]
A new command is tempting, but will land us in compatibility hell.

I'll wait for @PLK to have a say.

**Comment by plk** [comment]
I really don't want to create compat tracking issues but I will go with what @moewew decides as he's better informed about this issue than I am.

**Comment by moewew** [comment]
Since we could check if the new command is defined that would mean the least work for us. So if you, @komascript, think that is an appropriate solution and would implement that for us that would be really appreciated. Especially since we would not have to worry about future changes in KOMA definitions of the headings.

In the meantime I think we should nevertheless make our definitions mirror KOMA's as closely as possible.
I had a look at `scrartcl.cls`, but I didn't quite understand why the initial definition of `\bib@heading` in `\newcommand` did `\scr@ifundefinedorrelax`-testing while the later `\renewcommand`s seem to use the code from the true branch (i.e., command undefined) directly. What is the preferred way to do this for us? From `scrguide` I would have guessed we should go with the false branch (i.e., command defined) directly

**Comment by komascript** [comment]
The `\scr@undefinedorrelax` is for `\@mkright`, because this is a command of `scrlayer` not the classes and not the LaTeX kernel. The classes use it, if available. It seems in the classes I've forgotten to change one usage of `\markright` to use `\@mkright` if available. I will have a look into this.

However, you can make thing easier, if you'd copy the initial `\@mkright` definition of `scrlayer.sty`:

    \providecommand*{\@mkright}{%
      \begingroup
        \ifx\@mkboth\markboth \aftergroup\markright
        \else
          \ifx\@mkboth\@gobbletwo \aftergroup\@gobble
          \else \def\@gobbletwo##1##2{}%
            \ifx \@mkboth\@gobbletwo \aftergroup\@gobble
            \else
              \PackageWarning{biblatex}{% changed for biblatex
                package incompatibility detected!\MessageBreak
                \string\@mkboth it neither \string\markboth nor any\MessageBreak
                kind of two arguments gobbling,\MessageBreak
                e.g., \string\@gobbletwo.\MessageBreak
                So I don't known, what to do\MessageBreak
                with \string\@mkright.\MessageBreak
                Nevertheless, \string\markright\space will be\MessageBreak
                used%
              }%
              \aftergroup\markright
            \fi
          \fi
        \fi
      \endgroup
    }%

With this `\@mkright{…}` would be enough, no need for `\scr@ifundefinedorrelax`, no need for `\ifx\@mkboth…`. I think, I'll add a similar definition (with `\newcommand` instead of `\providecommand`) to the classes too. It will reduce the code size and the complexity of the code.

**Comment by moewew** [comment]
OK, thanks for the explanation. There is also one `\scr@undefinedorrelax` for `\mk@double`, is it safe for us to do `\providecommand*{\@mkdouble}[1]{\@mkboth{#1}{#1}}` as in `scrlayer`?

**Comment by komascript** [comment]
Yes.

**Comment by moewew** [comment]
Brilliant!

Further modifications - subject to change - are at https://github.com/plk/biblatex/compare/dev...moewew:fixheadings?expand=1

**Comment by komascript** [comment]
A version of KOMA-Script with `\bibliography@heading` is available at the [KOMA-Script package repository](http://www.komascript.de/current). Additional simplifications like the (unconditional) usage of `\@mkright`, `\@mkdouble` and `\addsubsectiontocentry` are also implemented in this version.

BTW: Thank you for the cooperation.

**Comment by moewew** [comment]
Brilliant! Thank you for your quick help and your amazing work in general.
If anything `biblatex`-related comes up that needs to be implemented on the `biblatex`-side, we'll be happy to help.

One thing we need to get back on track is the detection of KOMA options for the bibliography. That only seems to work for value-less options at the moment. https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/blx-compat.def#L44

@johannesbottcher Testing (at the moment you'd have to pull https://github.com/moewew/biblatex/tree/fixheadings) and further comments are of course appreciated.

**Comment by moewew** [comment]
The pull request has been merged. Most suggestions should have been addressed. If there is anything left to do, just add a comment here.

I'll just quote the two remaining issues from the pull request
> A few questions remain
>- Should `\abx@MakeMarkcase` be a user-facing macro? (Should it get a name without `@`?) Does it need to be documented?
>- Are `\@mkdouble` and `\@mkright` defined in the right place (`blx-compat.def` seemed like a good idea back then, but I'm not so sure any more)? Should they be documented?

**Comment by plk** [comment]
`\MakeMarkcase` seems like a reasonable user-facing macro to me. The other two, hmm, I'd be inclined to move them to the compatibility section in `biblatex.sty`. I'm happy to go with what you think about them being user-facing macros - I don't have a good enough sense of this issue to know.

**Comment by moewew** [comment]
The thing is that I don't want to define commands that are really outside of `biblatex`'s scope. We should have nothing to do with people's headers and footers. So in a way I would even prefer `\MakeMarkcase` to remain private like the other two. I won't change their status now, but if more people speak out in favour of making it public or you convince me, I'll look into it again.

**Comment by plk** [comment]
Ok, fair enough - I hadn't followed this closely enough to realise what these commands were.

**Comment by moewew** [comment]
OK, pushed the change https://github.com/plk/biblatex/commit/8bcd50c783623e22323dba159a8d1d43de04b94e

**Comment by moewew** [comment]
I'm closing this since I hope that everything is resolved. If anything comes up (especially after a new release), we can reopen this. Thank you for all your help.

**Comment by moewew** [comment]
Reopening this to look at https://tex.stackexchange.com/q/405461/35864

**Comment by moewew** [comment]
Since `memoir.cls` uses `\markboth` instead of `\@mkboth` for bibliography headings, I reluctantly switched back to `\markboth` for memoir. This gives less than ideal results for manual headers, but since the state in 3.8/3.9 deviates from the way memoir does things and people complained (https://tex.stackexchange.com/q/405461/35864) this is probably the best way.

Code is at https://github.com/moewew/biblatex/commits/memoirheadings

Comments and thoughts are of course appreciated.

**Comment by moewew** [comment]
#671 Has been sent off with the changes mentioned above. Comments and testing would still be appreciated.

**Comment by gusbrs** [comment]
@moewew , I just redid the tests mentioned in [https://tex.stackexchange.com/q/405461/105447](https://tex.stackexchange.com/q/405461/105447) and can report that behavior, as far as I can tell, seems fine with the proposed commit. (Disclaimer: I'm very limited regarding headers, but as supposedly I'm the one who "complained", I thought the feedback was due. It should be taken with a "spoon of salt" though.)

**Comment by moewew** [comment]
Thank you very much for reporting back.

The solution is not ideal, but at least it more or less restores the behaviour of pre-3.8 and comes close to the standard settings of `memoir.cls`. So it is probably the best we can do. The standard settings can't be good for all situations, but they should certainly give good results with the defaults of the document class.

**Comment by moewew** [comment]
https://tex.stackexchange.com/q/406199/35864 seems to suggest we should in general not set `\@mkboth` when we use `\section` or `\chapter`. Is that right or am I missing something?

**Comment by moewew** [comment]
There is https://github.com/moewew/biblatex/commit/f2fd886e319cfe6cb976fa94cf96218f643ed768 now with changes for unstarred sectioning. If the unstarred sectioning commands are used, the headings are not set manually.

**Comment by moewew** [comment]
#672 has the changes for unstarred sectioning commands. If there are no comments or complaints I will merge this together with #671 after the weekend.

**Comment by moewew** [comment]
Both #671 and #672 have been merged to `dev`. Testing and comments are as always appreciated.

@plk What do you think about a release before Christmas?

**Comment by plk** [comment]
@moewew - yes, I was going to suggest the same - are we ready from your point of view?

**Comment by moewew** [comment]
Maybe you can upload a dev version to sourceforge now, so we can ask people to test.

**Comment by plk** [comment]
Ok, just let me know and I'll initiate the release. "BA thesis" is fine. Mysterious in England, this title 
covers science subjects too.

**Comment by plk** [comment]
DEV upload is done.

**Comment by moewew** [comment]
Thanks.

**Comment by moewew** [comment]
3.10 has been released. Memoir should be back to normal now. I'm closing this for now.
