### ISSUE TITLE
Bug in 3.8 with bookpagination and totalpage

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#653]
Please consider the following MWE ex.

```
\documentclass{book}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
  @book{a,
    title={toto},
    author={titre},
    bookpagination={column}, 
    pages={22},
    pagetotal={222}
  }


\end{filecontents}
\usepackage[style=verbose]{biblatex}
\bibliography{\jobname.bib}
\begin{document}
\cite{a}
\end{document}
```

With version 3.7, the totalpage is exprimex in columns, with the version 3.8, it is in page

[38.pdf](https://github.com/plk/biblatex/files/1485710/38.pdf)

I get an 
```

Package biblatex Warning: Unknown pagination type ''
(biblatex)                at entry 'a' on input line 15.

```

**Comment by moewew** [comment]
This has already been brought to our attention in https://github.com/abntex/biblatex-abnt/issues/24. Commits https://github.com/plk/biblatex/commit/d7b354cd1b6fa9b59d395b1db178094dbd75e557 and https://github.com/plk/biblatex/commit/34f68d1e54452e1642c12276d2e0981419ebb3a5 should fix this. Please get the dev branch and check the output you get. (You won't need a new version of Biber)

**Comment by maieul** [comment]
I got 

```
<to be read again> 
                   D
l.14 \bibliography
                  {\jobname.bib}

```

**Comment by moewew** [comment]
Yes, that is the 'classic' problem when trying to run `biblatex` directly from dev. `biblatex.sty` has two variables set to dummy values instead of real ones. https://github.com/plk/biblatex/blob/e707a19c5b9a75ae5724c8e4c1fe0a41e9dd937a/tex/latex/biblatex/biblatex.sty#L14-L15
Either run the makefile with the correct options (I can't tell you exactly how that works), or supply sensible values instead of the dummy values.

**Comment by maieul** [comment]
Yes, it's work. 
I think it would be imperative to release soon for this problem, as it
is a breaking compatibility.

**Comment by moewew** [comment]
I had hoped that not enough people would use `pagetotal` with custom values so that this would largely go unnoticed. It really annoys me that I didn't catch the obvious mistake earlier or during testing. Not sure how soon a fix is going to be released.

@plk What do you think? Do we release a new `biblatex` 3.9 alongside Biber 2.9 to fix this (and keep version numbers in sync)? If so, what do be do about ISO/EDTF?

**Comment by plk** [comment]
Yes, we can do 3.9/2.9. The ISO thing is a pain as I had already merged those changes into DEV. I suggest we bite the bullet and do the ISO changes now.

**Comment by moewew** [comment]
We could revert the ISO/EDTF changes for the moment and defer them until the next release and more is clear. It would be a bit unfortunate if we have to change things again of the draft is changed later on, but the subset of users impacted by those decisions should be minute enough, hopefully (I could be wrong again here).

**Comment by plk** [comment]
It would be a pain to revert them now and I really doubt it will change that much. I would be more worried if this was an often used feature but I don't think it is.

**Comment by maieul** [comment]
Personaly, my politic for reledmac is to send fix release as quickly as
possible.

I have this schema for numbering x.y.z(letter)

- x is +1 only for major compatibility breaking
- y is +1 only for new features
- z is +1 for bugfix
- letter is modified only for handbook correction

Typically, 3,8 break major feature of biblatex-manuscripts-philology

**Comment by moewew** [comment]
Absolutely.

**Comment by moewew** [comment]
`biblatex` 3.9 has been released and the MWE works for me again. Can you confirm that?

**Comment by maieul** [comment]
yes, its work.

**Comment by moewew** [comment]
Brilliant! Thanks!
