### ISSUE TITLE
Verbose disambiguation

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#654]
Is it expected that the following MCE gives:

>Baez, John C. and Aaron D. Lauda (Oct. 27, 2004a). Higher-Dimensional Algebra V: 2-Groups. Version 3. arXiv: math/0307200v3.
— (2004b). “Higher-Dimensional Algebra V: 2-Groups”. Version 3. In: Theory and Applications of Categories 12, pp. 423–491. arXiv: math/0307200v3.

instead of:

>Baez, John C. and Aaron D. Lauda (2004a). Higher-Dimensional Algebra V: 2-Groups. Version 3. arXiv: math/0307200v3.
— (2004b). “Higher-Dimensional Algebra V: 2-Groups”. Version 3. In: Theory and Applications of Categories 12, pp. 423–491. arXiv: math/0307200v3.

```latex
\documentclass{article}
\usepackage[style=authoryear]{biblatex}
%
\addbibresource{biblatex-examples.bib}
\nocite{*}
%
\begin{document}
\printbibliography
\end{document}

```

**Comment by moewew** [comment]
I get
![statusverhoging](https://user-images.githubusercontent.com/6755835/33008564-da7c5492-cdd3-11e7-8afe-65b9decc37fe.png)
as I expected. Are you sure you are running `biblatex` 3.8a? What does `\listfiles` give?

**Comment by moewew** [comment]
I did some more digging in older versions of the documentation.

- The behaviour in `biblatex` 3.8a is consistent with the description in the documentation of the `mergedate` option.
- A similar behaviour to what you get now can be found in versions 1.0 up to 2.8a.
- In 2.9a the output changed to year only, but I'm not sure why. I don't think it was intentional. `authoryear.bbx` had not been changed for 2.9, so I think some other changes might have influenced this.

**Comment by dbitouze** [comment]
Sigh... In order to keep the same behavior with first issues of some journals, the classes of which I created, I'd like to retrieve the (IMHO more than enough and much more better) disambiguation '2004a', '2004b', etc. Could you tell me how to achieve this?

**Comment by dbitouze** [comment]
Well, a deeper look at the `biblatex-examples.bib` file lets me realize that the verbosity of '(Oct. 27, 2004a)' versus '(2004a)' doesn't come from disambiguation, but from the fact the 1st Baez entry does contain a complete date (`date = {2004-10-27}`) whereas the 2nd one contains only the year (`date = 2004`, BTW without braces).

So the previous behavior came from the fact that, at least with the `authoryear` style, the output date contained only the year even if the input one specified the month and the day. As a conclusion, the current issue isn't a real one and, as said by @moewew, only the previous behavior was wrong (BTW, strange enough nobody, included me, complained).

**Comment by moewew** [comment]
Yes, it is really strange that no one noticed. When I worked on the `mergedate` issue I thought this was a problem introduced by relative recent changes to date handling in version 3.5. I didn't think that the behaviour had been diverging from the documented one for essentially three years (since early 2014). I really hope that this does not cause too many backwards compatibility issues.
