### ISSUE TITLE
ibidpage documentation is ambiguous

### ISSUE THREAD

**Issue by wujastyk** [plk/biblatex#667]
The ibidpage documentation is found in the files at ../texmf-dist/doc/latex/biblatex/examples .  Looking at 53-style-authoryear-icomp-biber.pdf, for example, the doc says

> The scholarly abbreviation ibidem is sometimes taken to mean both ‘same au-
thor + same title’ and ‘same author + same title + same page’ in traditional
citation schemes. By default, this is not the case with this style because it
may lead to ambiguous citations.

It isn't clear what "this is not the case" refers to, since the first sentence gives two equal alternatives.  Which is not the case?

Further, the whole thing is unclear to me.  My understanding is that Ibidem is used when the citation is identical (author, title, page all the same).  Idem is used when the reference is to a different page of the same source (author and title are the same, page different).  This distinction does not emerge from the Biblatex documentation.  However, there are varying interpretations of idem and ibid and recent editions of the standard style guides (Oxford, Chicago) are tending to deprecate the use of either.  Whatever update is made to the documentation and code, it should adopt a clear position on ibid/idem.

**Comment by moewew** [comment]
Thank you for your comment. I agree that the current state of the docs doesn't make it entirely clear what the option is about. I had to run a test document to fully understand what is going on.

Please have look at https://github.com/plk/biblatex/commit/615569e1556ebd6e5a92071c0836e5952741ae57 
I did not delete the 'this is not the case' passage, because I think if you consider the 'both' in the previous sentence the passage just means that by default 'ibidem' does not have both of these meanings (but only one). I'm not a native English speaker, though, and if you have a suggestion to rephrase the paragraph I will gladly take it.

`biblatex`'s use of 'idem' and 'ibidem' follows the 'academic' use described in https://en.wikipedia.org/wiki/Idem and https://en.wikipedia.org/wiki/Ibid. (not the 'legal' use).
So 'ibidem' means *the previous citation* and 'idem' means *the previous author/editor/name*.
Philipp Lehman was a German speaker and I assume his interpretation was influenced by German usage customs where 'ibidem' is 'ebenda' and 'idem' is 'derselbe/dieselbe/dieselben'. There is no ambiguity for 'derselbe' between legal and 'academic' use in German.

I'm not sure what you mean by 'it should adopt a clear position on ibid/idem'.

**Comment by moewew** [comment]
@wujastyk If there is anything technical that could be addressed here I would be open for that as well. Do you think another third `ibidpage` behaviour could be useful? If so, what should it do?

Comments on https://github.com/plk/biblatex/commit/615569e1556ebd6e5a92071c0836e5952741ae57 are of course still appreciated.

**Comment by moewew** [comment]
@wujastyk We are thinking about releasing a new version shortly. Comments about the current state and helpfulness of the docs would be appreciated.

**Comment by moewew** [comment]
Is there anything that needs to be done here?

I'll close this for now. In case something needs to be discussed, feel free to comment and re-open or open a new issue.
