### ISSUE TITLE
british gives different (and wrong) short date format compared with UKenglish with polyglossia

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#677]
The following MWE example gives a URL date of 10/01/2006 (mm/dd/yyyy). But if I substitute `UKenglish` for `british` in the language mapping, it correctly gives 01/10/2006 (dd/mm/yyyy). This appears to only be a problem with `polyglossia`. Both `[british]{babel}` and `[UKenglish]{babel}` give the same output.

```TeX
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage[variant=british]{english}
\usepackage[urldate=short]{biblatex}
\DeclareLanguageMapping{english}{british}
\addbibresource{biblatex-examples.bib}
\pagestyle{empty}
\begin{document}
\nocite{ctan}
\printbibliography
\end{document}
```

**Comment by moewew** [comment]
`polyglossia` support is shaky at best at the moment. Especially language variant detection does not work as expected at all times (or at all?). I can have a look at that later, but I don't think I'll be able to come up with a good fix quickly. The whole `polyglossia` interface needs overhaul on our side and probably changes in the `polyglossia` kernel as well. I remember PLK submitting a pull request for `polyghlossia`, but it apparently didn't go through.

**Comment by moewew** [comment]
I don't know if `\DeclareLanguageMapping{english}{british}` is supposed to work at all. But really the whole language mapping business goes over my head.

One problem here is that `polyglossia` does not detect language variants. That is why things work with `babel`, there the variant is used directly and not only the generic `english`.

Another problem is the load order of `.lbx` files. The fact that `inherit` in `\DeclareBibliographyStrings` loads the entire `.lbx` again is also problematic. The loading sequence resets `bx@extras@#1`. And later `\DeclareBibliographyExtras` is a simple `\csgappto`. All the aliasing causes name clashes here so that the correct definitions are overwritten.

If you use `UKenglish` the loading order of the `.lbx` files is different from `british`, and in that case things go through smoothly.

**Comment by dcpurton** [comment]
Hmmm. I haven't looked at the code for language handling at all. I had thought that using DeclareLanguageMapping was the proper way to work around lack of variant detection in polyglossia.

I might take a look at this. Polyglossia is essential for Hebrew which I need for `biblatex-sbl`.

Can you give me any pointers in where to start poking around?

**Comment by dcpurton** [comment]
BTW, I don't see a difference in loading order for the `lbx` files. For `\DeclareLanguageMapping{english}{british}` I get `british.lbx` then `english.lbx`. For `\DeclareLanguageMapping{english}{UKenglish}`, I get `UKenglish.lbx` then `british.lbx` then `english.lbx`. This seems expected to me.

**Comment by dcpurton** [comment]
Oooo. I discover `babel` is much further along with it's support for Hebrew than I thought. Perhaps I don't care so much after all!

For the problem at hand, I notice that adding `\InheritBibliographyExtras{english}` at the top of `british.lbx` seems to work OK for both `babel` and `polyglossia`. But I have not checked for any other side effects that this might have.

**Comment by moewew** [comment]
You are right. It's not really the loading order, it must be some kind of grouping, aliasing or `\let` vs. `\def` thing. But as I say I don't fully understand what is going on.

If you want to investigate, my best guess would be `\blx@lbxinput` and the following macros up to and including `\blx@langsetup`.

At the moment `polyglossia` support is not really mature. `babel` on the other hand normally works fine. `polyglossia` development seems to have stalled recently, whereas `babel` just got a new version.

**Comment by moewew** [comment]
Related https://tex.stackexchange.com/q/357983/35864

**Comment by moewew** [comment]
@plk I would like to get an overhaul of the `.lbx` loading into `biblatex` 3.11. I'm still struggling with how to deal with this best and will definitely need a bit to test that nothing breaks. But after the changes are committed I would like to release fairly soon with an option to push out critical bug fixes shortly after should something break. Ideally we would manage to get 3.11 and the necessary bug fixes out before 12. March when TeX live is frozen for TeX live 2018.

**Comment by plk** [comment]
That is fine. There has been an open case for years about overhauling this but it was more to do with autogeneration of .lbx files from a DB. It also needed `babel` to switch to standard BCP47 language identifiers for the languages and files (not a bad idea) but this was never followed up.

**Comment by moewew** [comment]
There is https://github.com/plk/biblatex/compare/dev...moewew:lbxstuffthird now. Your MWE gives the expected output with the changes there. But since this is a change to critical infrastructure I would be interested in more thorough testing.

**Comment by moewew** [comment]
@plk The changes from pass all tests, but that is not too surprising, since most test files use `english`.

There is AFAICT only one change to documented behaviour. At the moment, mappings are not followed recursively

>Note that the suffix will not be applied to language files loaded recursively by the loading of a language file. For example, given the suffix defined above, when loading ‘ngerman’, `biblatex` will look
for the file `ngerman-apa.lbx` and if this recursively loads ‘german’, then `biblatex` will look for
`german.lbx` and not `german-apa.lbx`.

With the proposed changes, only infinite recursion is avoided. In the above example `german-apa.lbx` would be loaded. This seems to be not undesirable to me. But it changes documented behaviour. I'm not sure if anybody relied on that.

**Comment by moewew** [comment]
Please have a look at #702.

**Comment by moewew** [comment]
#702 has been merged now. So you can test the new version by pulling from dev or by getting the development version from SourceForge.

**Comment by moewew** [comment]
`biblatex` 3.11 and Biber 2.11 have been released now. Unfortunately, we didn't make it in time for the TeX live freeze, so the versions are only available on TeX live 2018 pretest and MikTeX at the moment.

The introductory MWE gives the expected output now.
