### ISSUE TITLE
REST interface for biber?

### ISSUE THREAD

**Issue by plk** [plk/biblatex#678]
@moewew, @josephwright 

I am wondering about, given the overhead of building biber for so many platforms, about looking into a cloud/REST interface. This would basically be a thin client distributed with TL as normal which would make REST calls to a biber cloud service. It would send the .bcf and datasources (since biber can fetch remote datasources, sending datasources would not always be necessary) and return a .bbl.

This has some advantages, for example, updates would be far easer to "distribute" as the REST client stub (called something like "biberR") would rarely need updating when stable and all updates would be done on the backend service. Another advantage is that it could be called from any programming language capable of making REST calls, which is basically all languages these days. I can see quite some interest, for example, in making biber's tool mode available via a REST interface.

I have experience creating such services and so it wouldn't be daunting but would be quite some work. Hosting would generate costs and it might have to be provided for a nominal, say annual fee but I don't know how that coheres with TeX licensing.

Thoughts?

**Comment by moewew** [comment]
I'm sceptical for two reasons.

1. I am not very fond of cloud computing.
2. I am very wary of involving a commercial provider with additional costs.

Re 1. 
- I prefer to have the software on my machine so I have control over it. I'm not sure how many TeX users feel like this and I'm sure there are many users that would not mind giving up control or would actively benefit from doing so. ShareLaTeX and Overleaf seem to be doing OK.
- The problem here is that the `.bib` files and `.bcf`s would have to be uploaded for every compilation (there could probably be some caching and hashing to avoid sending too much too often, but that needs work).
  - I'm not sure how often the average user compiles and about the average number of bytes that would have to be sent around, but I had to realise that uploading can be a real pain on an otherwise fairly stable internet connection.
  - `.bib` files will probably not constitute secret information for most people, but sending them off to a server might still not be what people want. (I realise this is a relatively weak point, people seem fine using Mendeley, Zotero, ... People share `.bib` files in repositories.)

Re 2
- The whole payment business would create additional overhead and would require bookkeeping.
- If BiberR is optional I don't know how many people would really want to pay for it.
- As soon as payment for software is involved I feel that the expectation of users might change with regards to support, bug fixes and feature request. Even if the payment is not for Biber itself, but for the server infrastructure.
- Would probably be OK TeX-license-wise (IANAL), but I'm not sure about inclusion in Linux distributions, CTAN and TeX live.

At the moment Biber and `biblatex` are both managed by the TeX distribution and their versions should match (if people don't do partial updates and don't install stuff manually). If Biber lives in the cloud, the server would have to be able to run all previous Biber versions and would have to determine which to run. I assume this is possible without too much effort.

Since `biblatex` does not live in the cloud and is updated like normal, I don't really see a huge advantage in BiberR not needing updates. If Biber and `biblatex` are sent off to CTAN at the same time and users use the update facilities of their TeX distributions properly, the difference between the outcome of that approach and `biblatex` being updated locally and Biber on the server are minute.

I have no idea how much interest there is to make Biber's other features available to other programming languages. And how extensively this would be used.

The massive advantage that I see is that building Biber will not be needed any more. But maybe we should simply think about a way to make that easier?

Just my 2 cents I would be interested what other people have to say? Maybe you can ask on `comp.text.tex` for input.

**Comment by josephwright** [comment]
I'm mindful that I don't have to do the work of building Biber, but like @moewew I'm not keen on an 'online' plan. It's fine for end users with complete control of their PC, but that is a subset of users. For me, I suspect the above would block Biber on my work PC, and I do have a reasonable amount of freedom. For publishers or similar (say the AMS), having a locked-down 'known' system is a must. Now, those users may already stick to BibTeX-only.

**Comment by plk** [comment]
I am coming round on cloud things. I instinctively don't like it very much but have been forced to be involved with it in some capacity and I think it is inevitable in many areas because the cost benefits are inarguable and this will (and is) driving it. It would be optional, of course, I can't see stopping the usual biber distribution. This would be a parallel offering for the forseeable future, probably at first as a way of making the development version immediately available to people, without installation. It would, for example, be relatively easy to make multiple versions of biber available this way with little overhead.

I can't see any issues with uploading (apart from firewalls, of course) as we are talking about relatively small text files which would be compressed for transfer - even old internet connections are not going to have a problem with this. It would be over standard http/https and so probably fine in most companies too. The "always up to date" argument isn't so good as long as biber and biblatex versions are closely tied since biblatex would need an on-premise update anyway.

One thing that attracts me about this is a potential lua wrapper embedded in biblatex itself which calls the REST interface. That way, one replaces an entire complex package (biber) with a cloud REST API accessed directly from biblatex. I can see that being attractive in the future.

**Comment by perstar** [comment]
I will not upload my bibliography files to Someone Else's Computer. If this is the way Biber goes I will continue to run an old version as long as it works and wait for someone to fork Biber. I don't mean to put anyone down by this, it's just an honest answer about my view and what I would do.
