### ISSUE TITLE
Loading both English and American

### ISSUE THREAD

**Issue by odomanov** [plk/biblatex#696]
I try to use `\DeclareLanguageMappingSuffix`, but I have a problem with languages like English and American. I created files `english-gost.lbx` and `american-gost.lbx`, but if the latter is loaded first, it loads `english.lbx` at some point and assigns its strings to American language. But when the former is then loaded it skips loading `english.lbx` for the second time and fails to assign these strings to English. As a result, English misses a lot of strings. Is it a bug or do I miss something?

I attached files to demonstrate this.

If I have English and American entries in the database, I need to load both languages.

[english-american.zip](https://github.com/plk/biblatex/files/1668478/english-american.zip)

**Comment by moewew** [comment]
Thank you for reporting this issue.

The whole language mapping business is a bit tricky and in a bit of state right. I happen to think what you try should actually work. But I'm not too sure.

As luck would have it, I recently looked into #677 and found that the entire thing probably needs an overhaul. I'm currently trying to figure out a way to do that without breaking stuff. Hopefully that should solve your issue here as well. I'm beginning to think that a lot of things at the moment work more by accident than by design.

**Comment by odomanov** [comment]
Well, finally I used `\DeclareLanguageMapping` instead of `\DeclareLanguageMappingSuffix` and it works. Although I don't completely understand why. Luck, probably :)   At least this seems to solve my particular problem.

The thread may be closed, unless you want it to be open as a reminder.

Thank you.

**Comment by moewew** [comment]
`\DeclareLanguageMappingSuffix` should work as well. I'll keep this open to be sure the issue is really solved if I finally manage to come up with a working solution for `.lbx` file loading.

**Comment by moewew** [comment]
Please have a look at https://github.com/plk/biblatex/compare/dev...moewew:lbxstuffthird.
Your MWE should work as expected now.

The changes to `.lbx` loading are critical so I would really appreciate thorough testing.

**Comment by moewew** [comment]
Please have a look at #702.

**Comment by moewew** [comment]
`biblatex` 3.11 and Biber 2.11 have been released now. Unfortunately, we didn't make it in time for the TeX live freeze, so the versions are only available on TeX live 2018 pretest and MikTeX at the moment.

The zipped MWE shows the expected behaviour now.
