### ISSUE TITLE
How to follow renaming of bibmacros 

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#700]
I just got bitten by this commit: https://github.com/plk/biblatex/commit/189d90db9dbe94dd08f47261e79df09e2a37c66a

In a style I had the equivalent of this code:
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[style=authoryear]{biblatex}
\renewbibmacro*{date+extrayear}{\quad something silly}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{doody}

\printbibliography
    
\end{document}
```

which with an older biblatex did the expected:

![renewbib](https://user-images.githubusercontent.com/4047173/35526960-7e9ef58e-0529-11e8-8ed0-94b9706bf527.PNG)

But with a current biblatex the \renewbibmacro simply fails silently. There is no warning that the bibmacro is undefined (as it is defined to give a deprecation message). 

I don't see a way to avoid the problem (unless by never renaming any macro), so imho a test system for a biblatex style is needed (perhaps based on l3build).

**Comment by u-fischer** [comment]
Addition: I also think that a list of such renamed bibmacros is needed (with the replacement) to make it easier to update local styles.

**Comment by moewew** [comment]
Mhh, what would this test system involve? What should `biblatex` do exactly? Wouldn't this 'just' involve the style developer setting up their own l3build system?

A list of renamed things/bibmacros sounds good though. We already have CHANGES.md, but it would definitely be nice to have that in a more digestible format.

**Comment by plk** [comment]
I started on an l3build test suite a while ago but it needed changes in l3buold itself. @josephwright was looking into this as I recall.

**Comment by moewew** [comment]
`l3build` has progressed quite a bit since then. I managed to set up a simple system for a `biblatex` style I'm working on. But I didn't really manage to get `l3build` running for the setup we have here.

Another thing is that `l3build` seems to work better with `.log` files. It supports PDF comparison as well, but the `.log` comparison is slightly more helpful in case there are failing tests it seems to me. And `biblatex` doesn't really lend itself to `.log` output checking, except when shipping out entire pages. I managed to get something going by shipping single boxes, but that was not really satisfying and required modification of a few macros.

**Comment by u-fischer** [comment]
> Mhh, what would this test system involve? What should biblatex do exactly? Wouldn't this 'just' involve the style developer setting up their own l3build system?

Imho testing biblatex styles involves for all styles more or less the same or at least similar tests. So it would be quite useful if a set of standard tests would exist that users can reuse or adapt.

**Comment by moewew** [comment]
I'm really interested in a `l3build` test system, but at the moment I don't have enough experience with `l3build` so this would be not very high on my list of priorities.

**Comment by moewew** [comment]
There is now https://github.com/plk/biblatex/wiki/Name-Changes for name changes. Ideally, that page would be kept in sync with CHANGES.md. CHANGES.md is still the primary source of information about technical changes in `biblatex`.

**Comment by moewew** [comment]
Since @maieul brought this up over on comp.text.tex. Maybe we should think about a mailing list or similar to announce changes. The Wiki is good if people come looking for it, but maybe we should make it easier for people to come here´shortly before a new release by sending out some sort of announcements.

@plk In https://github.com/plk/biblatex/issues/372 amongst other things the idea of a mailing list was discussed. A mailing list would mean additional overhead. Maybe there is something simpler that can be integrated into GitHub or what we have at the moment, so we don't need to start something new.

**Comment by u-fischer** [comment]
Perhaps you could simply create an issue "Change announcements" and people interested could subscribe the issue.

**Comment by moewew** [comment]
Because I liked the number and it was brought up again I reserved #842 for change announcements. We'll probably have to discuss if this is going to be done at all and how. But at least we have a placeholder now.

Suggestions are very welcome.

**Comment by gusbrs** [comment]
@moewew thank you very much. I subscribed to get notifications from #842 . It seems a good workaround within github's boundaries. Also, take a look github.com/plk/biblatex/releases.atom (the releases Atom feed). I assume the tagging can be made somewhat more informative. So this may be another alternative without extra burden.

**Comment by moewew** [comment]
We are using 'lightweight' tags for releases and not 'annotated' tags (see https://git-scm.com/book/en/v2/Git-Basics-Tagging), which means that the tag just points to the last commit in the release and the feed shows its commit message.

**Comment by gusbrs** [comment]
@moewew I suppose you have seen this news:
![selection_001](https://user-images.githubusercontent.com/19410606/49147002-9cb24d00-f2ea-11e8-8922-e7711bcaba2a.png)
If it works properly, it should solve the problem and render #842 obsolete, I guess.

**Comment by moewew** [comment]
I have updated https://github.com/plk/biblatex/wiki/Changes-to-the-standard-styles with some more details and plan to do so for in the future.

People who are interested in these sorts of things should definitely consider subscribing to #842 where I hope to give advance warning (and/or ask for feedback) when big and likely problematic changes are in the making. (Like #1000 at the moments: Comments are still welcome.)

Automatic testing is tracked in https://github.com/plk/biblatex/issues/374 (though there hasn't been a lot of progress there lately; my own experience with `biblatex-ext` is that automatic testing with `l3build` is still a bit painful because we mostly have to rely on `\showoutput` or boxed output, so test logs get very long, additionally the required number of LaTeX, Biber, LaTeX, LaTeX runs take their time - especially on my local virtual machines, Travis is alright, but even there many tests will take a while).

Closing this for now: If there is something else, I suggest to open a new issue.
