### ISSUE TITLE
Biblatex is unable to load

### ISSUE THREAD

**Issue by juhaszp95** [plk/biblatex#706]
Biblatex is unable to load and gives error `Math formula deleted: Insufficient symbol fonts. australian,newzealand}` which occurs in line 3776 of `biblatex.sty`. It also says `Missing \begin{document}. australian,newzealand}` for the same line. I usually use packages `newtxtext` and `newtxmath` but it occurs even in the example below.

The minimal working example:
```
\documentclass{article}
\usepackage{biblatex}

\begin{document}	
  Minimal working example.
\end{document}
```

**Comment by moewew** [comment]
This is a problem in `etoolbox` v2.5b that should be fixed in v2.5c, see https://github.com/josephwright/etoolbox/issues/19. v2.5c should already be available on CTAN and TeX live, but it will take at least another day until it lands in MikTeX.

See https://tex.stackexchange.com/q/413898/35864 for a workaround.
