### ISSUE TITLE
biblatex's punctuation macros in DeclareSourcemap

### ISSUE THREAD

**Issue by gusbrs** [plk/biblatex#740]
I bring an issue to your consideration, raised at https://tex.stackexchange.com/q/428535/105447 (particularly, the discussion in the comments to moewe's answer).

The issue is that `\DeclareSourcemap`'s `fieldvalue` does not seem to deal well with some of biblatex's punctuation macros. In the case there, the OP requested to have " (...), " at the end of shorttitles, so I suggested to include this with a Sourcemap. But the use of `\isdot` in the `fieldvalue` results in an "Undefined control sequence" error. I'm aware punctuation macros are not necessarily available outside a biblatex context, but the value of the field, resulting from the Sourcemap, would eventually meet the appropriate context in which the macro would be recognized. As moewe explained in the discussion there, it seems the problem emerges when biblatex writes the bcf file and the macro gets then expanded outside the proper context, thus the error.

A mwe that allows you to reproduce the issue is:

```
\documentclass{article}

\usepackage[style=verbose]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{key1,
author = {A. Uthor},
title = {Regular title},
shorttitle = {Short title},
location = {London},
year = {2017},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map[overwrite]{
      \step[fieldsource=shorttitle, match=\regexp{\A.+\Z}, final]
      \step[fieldset=shorttitle, fieldvalue={\addspace(\ldots)\isdot}, append]
    }
  }
}

\begin{document}
Text\autocite{key1}.
\clearpage
Text\autocite{key1}.
\end{document}
```

I'm aware the use of field formatting would be better left to styles than to the data itself. But sometimes, this sort of use may be necessary or convenient. Anyway, I would expect `\DeclareSourcemap` to be able to handle biblatex's punctuation macros. The behavior is something I noticed, that I though worth to bring to your attention.

**Comment by moewew** [comment]
A simple workaround here would be
```latex
      \step[fieldset=shorttitle, fieldvalue=\regexp{\addspace(\ldots)\isdot}, append]
```
The thing is that the contents of these instructions are expanded when they get written to the `.bcf` file. This is not desirable in this case, because it will leave you with partially expanded definitions that don't do the right thing. This expansion needs to be suppressed here and `\regexp` does that.

In theory, `\regexp` could be applied automatically in some places. But then we could run into trouble if people actually want the expansion (not sure if that is ever desirable, I haven't looked up exactly at what point the commands get expanded).

@plk What do you think?

**Comment by moewew** [comment]
On a related note (also related to #738) filenames with non-ASCII chars in `\addbibresource` are a problem with pdfLaTeX because of `\scantokens` in `\blx@xmlsanitizeafter` to replace `"`,`<` and friends. But I don't think there is an easy way to retain the replacement of the XML-critical characters and not expand the non-ASCII characters...

**Comment by moewew** [comment]
Given that people may want to expand commands they pass to `fieldvalue` and that we should not break backwards compatibility, I'm tempted to say that this works as intended.

The recommended work-around in case you have code that should not be expanded at definition time is to wrap it in `\detokenize`, this is pretty much I recommend for #738 as well. I added a short note about that https://github.com/plk/biblatex/commit/ca3c200068d57560e8d7beb81d44a59374133984.
