### ISSUE TITLE
The build script does not really allow to install older versions

### ISSUE THREAD

**Issue by mschauer** [plk/biblatex#741]
(and pretends to do so)

See https://lpetrov.cc/2017/12/tex-distributions-again/

The bbl version is frozen to version 3.0. Just reporting in case this is something.

**Comment by moewew** [comment]
The build script does indeed not allow you to install a specific version of `biblatex`. It installs the sources currently checked out *as* the version you supply to it in the argument (that is, it installs the files and changes a few lines of code that are only concerned with what version `biblatex` reports). Unfortunately, there is no documentation for `build.sh` and I assume it is mainly intended for developers and not for your average end user. Essentially the build script just copies a few files around and changes a few version and date lines. It can't do more, it does not obtain the sources corresponding to the version you give in the build argument.

If you need a specific version of `biblatex` it is a much better idea to get the official releases from SourceForge: https://sourceforge.net/projects/biblatex/files/. If you insist on GitHub you need to [check out the correct tag or download the correct release](https://github.com/plk/biblatex/releases) and then run the build script on that with the corresponding version argument.

I assume the problem alluded to in https://lpetrov.cc/2017/12/tex-distributions-again/ is actually that one does not only need the same version of `biblatex` as the arXiv one also needs the corresponding Biber version. Bibliographies are a two-pass system in LaTeX one needs a package on the LaTeX side and an external program (the 'backend') to read, sort and parse the `.bib` files into a structure understandable for TeX (read more about that in https://tex.stackexchange.com/q/63852/35864). The default backend for `biblatex` is Biber and its version must be compatible with the used `biblatex` version (compatible versions are listed in the 'compatibility' matrix in both the `biblatex` and the Biber documentation). In fact it is Biber who produces the `.bbl` file. `biblatex` only reads the `.bbl` file (it will reject the file if the version is wrong). This explains the "Note that cloning the full `biblatex` github repo and running their install script (turns out I needed version 3.5 of `biblatex`) for some reason does not give the needed version 2.8 of the `.bbl` file" - the correct version of Biber is also needed.

So you will also get the right version of Biber. Again, SourceForge is the right place for the official releases https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/. No pre-built binaries are hosted on GitHub.
 
The current `.bbl` version is indeed 3.0. That version does not need to coincide with the `biblatex` version or the Biber version, see https://tex.stackexchange.com/q/415703/35864

**Comment by mschauer** [comment]
Oh, that is a helpful detailed answer. One remark: I suspect that having the correct version of Biber might not be the full story: https://tex.stackexchange.com/questions/358831/biblatex-and-arxiv-error type of problems persist when "backend=bibtex" is given.

**Comment by moewew** [comment]
BibTeX can be used as an alternative backend for `biblatex`. It is actively discouraged to do that now, some features might now work and Biber is preferred, but for compatibility-sensitive areas it might be an option. If you use BibTeX instead of Biber you don't have to worry about the corresponding Biber version, but you must still run the version of `biblatex` that arXive uses and you must upload the `.bbl` file created by BibTeX.

Not knowing the details I can't comment further, but normally things should work if everything you use (`biblatex` and if applicable Biber) is at the same version as the arXiv. Make sure to delete the temporary files and compile from scratch.

**Comment by mschauer** [comment]
That makes it clear!

**Comment by moewew** [comment]
Thank you for the quick feedback. Closing this now. If there is anything else, please let us know.
