### ISSUE TITLE
Merge \citename, \citelist, \citefield

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#75]
Wouldn't it be possible to merge the low level commands `\citename`, `\citelist` and `\citefield` in a single one, say `\citeelement`? Indeed, biblatex is more aware than the user of the type (name list, literal list, field) of a given entry field.

For instance, if I write `\citeelement{institution}`, I would expect biblatex to know better than me that 'institution' entry field is of list (literal) type and then change it silently in `\citelist{institution}`.

**Comment by dbitouze** [comment]
As @aboruvka closed this issue but didn't strongly close the door on it ("the commands should probably remain data-type specific"), could this issue be reopen for discussion?

**Comment by moewew** [comment]
At some point you will have to know the type of the 'field' you are printing. (When you want to redefine the format: `\DeclareFieldFormat`, `\DeclareListFormat`, `\DeclareNameFormat`.) Given that it would be a bit of a hassle to implement the automatic choice of the correct function (`biblatex` does not know the type for each field, it only has a list of fields for each type at the moment) and that in general users should not have to use `\citefield` and friends explicitly very often (if they find using themselves `\citefield` or a combination of those commands more than a few times, they should consider defining a new `\...cite` command with `\DeclareCiteCommand`), I think a change here is not really worth it.

**Comment by dbitouze** [comment]
>At some point you will have to know the type of the 'field' you are printing. (When you want to redefine the format: \DeclareFieldFormat, \DeclareListFormat, \DeclareNameFormat.)

But not if you don't want to redefine the format. As in my first post, suppose I just want to print the institution of a PhD thesis identified by a given `⟨key⟩`: it would be easier to just say `\citeelement{institution}{⟨key⟩}`.

>biblatex does not know the type for each field, it only has a list of fields for each type at the moment

I don't see what are the fields `biblatex` doesn't know the type: in § 2.2.2 "Data Fields", all the fields are followed by their type or did I miss something?

> in general users should not have to use \citefield and friends explicitly very often

Indeed but, in order to keep redundancy as low as possible, I would prefer to be able to (easily) print an element of a reference by extracting it from the `.bib` instead of having to rewrite or copy-paste it.
 Moreover, it is currently easy to print the author, the title and the year or date of a reference (okay I see the point) but also its URL and this one seems a bit strange to me: why this field more than others?

>if they find using themselves \citefield or a combination of those commands more than a few times, they should consider defining a new \...cite command with \DeclareCiteCommand

Isn't it taking a sledgehammer to crack a nut if, as my first post, I just want to print institutions of some references?

**Comment by moewew** [comment]
The separation between the three field types is deeply rooted in all parts of `biblatex`, so breaking it up for `\citeelement` would leave an obvious inconsistency. Given that the command is not used that often, *I* think that the benefits of such a unified command do not outweigh the downsides of breaking consistency.

While you might not want to format the fields differently, some people might and if the distinction between the field types only becomes apparent at that point when it has been kept under wraps before it might be even more confusing (why do I have to say `\DeclareFieldFormat` but `\DeclareListFormat` when I can say `\citeelement` for all fields?).

> I don't see what are the fields `biblatex` doesn't know the type: in § 2.2.2 "Data Fields", all the fields are followed by their type or did I miss something?

Internally, `biblatex` has no simple way of telling the type of a given field (that is to say there is map from field to its type). There is a list of fields of a given type. That means that `biblatex` would have to loop through the list of a given type to verify that something is of that type. Sure, that is no *big* obstacle, but it shows that implementation-wise `biblatex` relies on the author to specify the field type.

I think this is also what Audrey hinted at, *theoretically* `biblatex` could even have a field and a list of the same name internally and things would go smoothly (of course that would be useless in reality because for the input via `.bib` files the field must have one type). 

> [I]n order to keep redundancy as low as possible, I would prefer to be able to (easily) print an element of a reference by extracting it from the .bib instead of having to rewrite or copy-paste it.

Sure, that is what this command is for. It is definitely not useless, but as far as usage goes it will not be used all that often. You probably need to have read the documentation to know the command and then you can also quickly look up the field type. And when we analyse the pros and cons of this command I think it is fair to point out that the command is not among the big, relevant commands.

> Moreover, it is currently easy to print the author, the title and the year or date of a reference (okay I see the point) but also its URL and this one seems a bit strange to me: why this field more than others?

Mhhh, yes. It is simply not economical to define a dedicated `\cite...` command for every field. Author, title and year are obvious candidates (and at least author and year have precedent in `natbib`). I don't know why there is a `\citeurl`. It doesn't seem to be used all that much if you search around on the web, but apparently it was thought it could be useful (according to the changelog it was added in v0.7 in December 2007). Anyway, I don't quite see where this part of the argument leads with respect to `\citefield`.

> Isn't it taking a sledgehammer to crack a nut if, as my first post, I just want to print institutions of some references?

Maybe, I guess that is a matter of taste. The `\citefield` commands are also a bit weird in their default field format output, so I personally would probably prefer a dedicated `\DeclareCiteCommand` quite quickly even if it seems like a sledgehammer. If you only want to print the institution of a couple of entries, it does not matter a great deal, but if you use it much more often or want an interface for users the sledgehammer becomes more attractive.

**Comment by dbitouze** [comment]
Many thanks for this detailed answer! Okay, you won: I give up :)
