### ISSUE TITLE
`\DeclareAutoCiteCommand`: problem with `\autocites`

### ISSUE THREAD

**Issue by brian-ammon** [plk/biblatex#758]
`\DeclareAutoCiteCommand` does not seem to set the definition for the `\autocites` command correctly. (Perhaps related to #202.)

For the single `\autocite`, it is apparently no problem:

```TeX
$ latexdef -p [autocite=footnote]{biblatex} -b \DeclareAutoCiteCommand{footnote}[f]{\footcite}{\footcites} autocite

\autocite:
\protected macro:->\blx@citecmdinit \@ifstar {\blx@citepunct {\blx@acitei@footnote *}} {\blx@citepunct {\blx@acitei@footnote {}}}
```

However:

```TeX
$ latexdef -p [autocite=footnote]{biblatex} -b \DeclareAutoCiteCommand{footnote}[f]{\footcite}{\footcites} autocites

\autocites:
\protected macro:->\blx@citecmdinit \@ifstar {\blx@mcite@smartcites *\blx@macitei@footnote } {\blx@mcite@smartcites {}\blx@macitei@footnote }

```
which I think should rather be something in the direction of:

```TeX
$ latexdef -p biblatex footcites

\footcites:
\protected macro:->\blx@citecmdinit \@ifstar {\blx@mcite@footcites *\blx@mcitei@footcites } {\blx@mcite@footcites {}\blx@mcitei@footcites }
```

The problem is that the redefined `\autocites` still contains `\smartcites`, which will throw an error, because they were never defined depending on the style used.

**Comment by moewew** [comment]
Thank you for reporting this. That is indeed curious behaviour. I'll have a look.

**Comment by moewew** [comment]
For now note that `\ExecuteBibliographyOptions{autocite=footnote}` after the `\DeclareAutoCiteCommand` fixes the problem as explained in #202 and mentioned in the docs. So if it turns out that this is difficult to fix I will probably just adjust the wording in the docs to be even more insistent that setting the `autocite` option anew is required after changes to `\DeclareAutoCiteCommand`.

**Comment by moewew** [comment]
The internals are a bit tricky, but I think the code in https://github.com/plk/biblatex/compare/dev...moewew:autocite should work now.

Normally I would have been fine with insisting that `\ExecuteBibliographyOptions{autocite=<name>}` be called even if only the currently active `<name>` was redefined with `\DeclareAutoCiteCommand` and I would have left it at that. But the difference in behaviour between `\autocite` and `\autocites` is *very* unfortunate because it means that users might not realise that an additional step is required. So it seemed a good idea to look into a solution that does not require `\ExecuteBibliographyOptions{autocite=<name>}`.

Testing would be appreciated.

**Comment by moewew** [comment]
`biblatex` 3.12 has been released and is available in TeX live 2018 and MikTeX now.

`\DeclareAutoCiteCommand` should now work for the currently active `autocite` command without the need to execute the option again.
