### ISSUE TITLE
An equivalent of biblistfilter for \printbibliography

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#804]
biblistfilter filters directly in the .bbl file.

Should it be possible to add simiilar option also for bibliography? it would be useful for biblatex-shortfields package, which creates a custom bibliography which print content only in one of these followings conditions:
- shortjournal
- shortseries
- claves

many thanks in advance

**Comment by plk** [comment]
Well, this is what biblists are for ...?

**Comment by maieul** [comment]
no, biblist can work only with one field as label (shortjournal, shortseries). The shortfields packages is to print a list which mix the fields. And to do that, I can't use biblist, but need to create special bibliography, with custom formatting and custom check.

**Comment by dcpurton** [comment]
@maieul , do you mean having a list of abbreviations with (say) both `shortjournals` and `shortseries` in it? You can do this with biblists. I did it for `biblatex-sbl` (with three fields actually, `shortjournal`, `shortseries`, and `shorthand`). It was a bit of a pain though. Have a look at my list of abbreviations code in `biblatex-sbl.def`. It might benefit from a lower level implementation to support this.

**Comment by moewew** [comment]
Indeed as @dcpurton shows in https://github.com/dcpurton/biblatex-sbl/blob/bccd0c5dc25af0132ea416acdc9198f80d87b5b1/latex/biblatex-sbl.def#L688-L774 `\DeclareBiblistFilter` already supports multiple fields.

For example `biblatex-sbl.def` has
```
\DeclareBiblistFilter{abbreviations}{
  \filteror{
    \filter[type=field,filter=shorthand]
    \filter[type=field,filter=shortjournal]
    \filter[type=field,filter=shortseries]
  }
}
```

I guess you want to use such an extended biblistfilter  and `\printbiblist` instead of `\printbibliography`.

@dcpurton  Any particular lower-level stuff you have in mind? Looking at your code I get the feeling that most of this is already there.

**Comment by maieul** [comment]
Indeed, it seems that biblist system is more efficient than few years ago. 

I think we can close that issues
thank all...

**Comment by dcpurton** [comment]
@moewew , there are several issues that make doing what I did a pain:

- Finding the maximum label width of the `shorthand`/`shortjournal`/`shortseries`. The is not too bad to do, but does require calculating the maximum at the beginning of the list environment. Having an interface to set up a set of fields to use in abbreviations would be a nice feature.
- Typically, a `shorthand` will only appear once. But a `shortjournal` and `shortseries` can appear in many entries, but should only appear once in the list of abbreviations. This required an ugly set of checks in `\defbibcheck` to make sure things were only included once. An interface to do this would also be nice.
- Finally (this caused me the most grief), some entries will potentially have both (say) a `shorthand` and a `shortseries`. Without special handling, you only get one appearing in the list of abbreviations. I ended up using a source map to duplicate entries in this case and adjust them so that one skips the `shorthand` and one the `shortseries`. It worked, but isn't pretty. I might just be wishful thinking to want a better interface for this feature...

See also my related questions on tex.stackexchange:

- https://tex.stackexchange.com/questions/267425/biblatex-and-filteror-to-produce-a-combined-list-of-abbreviations
- https://tex.stackexchange.com/questions/304881/how-to-put-an-entry-with-both-a-shortseries-and-shorthand-in-list-of-shorthands

**Comment by moewew** [comment]
@dcpurton  Ah I see.

Your point 1 is solved quite elegantly with the maximum already, I think. We could in principle set up a specific `...width` with more possible fields at once. But I'm not sure if that would really bring a huge improvement for the general public. There is a first attempt at https://github.com/plk/biblatex/compare/dev...moewew:labelfieldwidthcomb let me know what you think.

The series of conditionals in `\defbibcheck` is what the documentation suggests as well. I mean we could *probably* wrap this up in some sort of command, but I'm not sure if that would really be useful for a wide audience. It is straightforward (if not very pretty) to set things up in its current form.

Point 3 sound interesting. Given the fundamental workings of `\printbiblist` and friends I'd say that this is something that would need to be tackled on the Biber end pretty much in the way you did already: the entry would have to be copied, one can't really reliably process one entry twice in the same `\printbiblist` if it does not appear twice in the `.bbl`. I have no idea what exactly would have to be done to support this better, but if you have concrete ideas for an interface, I'd love to hear about them.

**Comment by plk** [comment]
If you could say functionally what you would require for point 3, I can look at it. You mean a biblist where the keys are drawn from more than one field?
