### ISSUE TITLE
Package inputenc Error: in the bibliography but not in the .tex file

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#819]
The `biblatex`'s documentation says p. 44:

> However, keep in mind that it will not magically make traditional TeX or
pdfTeX support Unicode. It may help if the occasional odd character is not supported
by inputenc, but may still be processed by TeX when using an accent command
(e. g., \d{S} instead of Ṣ).

Okay but I still don't understand why, in the following MCE, `Mo{\u{\i}}{\v s}ezon`:

- works nicely in the `.tex` file,
- fails in the bibliography (if `\citeauthor{moishezon}` is uncommented).

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[safeinputenc]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@misc{moishezon,
    author = {Mo{\u{\i}}{\v s}ezon, B. G.},
     title = {The Title},
      date = {2018},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
Mo{\u{\i}}{\v s}ezon%
% \citeauthor{moishezon}
\end{document}

```

**Comment by dbitouze** [comment]
Okay, it works if `biber` is run with the option `--output-safechars` option, but why the latter seems to be necessary?

**Comment by moewew** [comment]
The MWE works for me as posted (of course with `\citeauthor{moishezon}` uncommented, so the issue can show) without setting additional flags for Biber at compile time. If I remove the `safeinputenc` option the MWE fails as discussed amply on TeX.SX (https://tex.stackexchange.com/q/251261/35864, have a look at the linked questions as well) and the Biber bugtracker (https://github.com/plk/biber/issues/65, https://github.com/plk/biber/issues/94).

As far as I know this issue is specific to combinations with a *dotless i* since LaTeX (against Unicode recommendations: http://unicode.org/faq/char_combmark.html#22, which it probably predates ...) usually wants accented *i*s to be based on *dotless i* and not *i* (or at least that is common practice), Biber reads these combinations at face value and turns them into *dotless i*+*combining breve* (and not into *ĭ*) which LaTeX then dies on because it can't handle Unicode's combining accents.

Nowadays I strongly recommend using (single-point) Unicode which not only works directly and looks nicer in the source, but also avoids the braces that could destroy kerning
```
Moĭšezon
```

**Comment by dbitouze** [comment]
>Nowadays I strongly recommend using (single-point) Unicode

Indeed, works nicely: thanks!

**Comment by dbitouze** [comment]
But, would it be possible to deliver a message more meaningful than the current one?

**Comment by moewew** [comment]
The message comes from LaTeX, so there is not a lot we can do about that. FWIW I think it is fairly clear and makes sense, but it can be confusing if you don't know that Biber actually processes and recodes your field values to Unicode even if you type them in ASCII-only.

**Comment by dbitouze** [comment]
>FWIW I think it is fairly clear and makes sense

Indeed, for insiders but, even for them, it may not be clear how to fix such a error in case of `biblatex`/`biber`.

**Comment by moewew** [comment]
But I don't see how 'we' (`biblatex`) could give a better error message here. It is ultimately LaTeX that chokes on the Unicode sequence and it is LaTeX that throws the error message. `biblatex` doesn't really have any say in that.

The `biblatex` documentation already has a passage explaining that Biber re-encodes the data (p. 44 two paragraphs up from the one you quoted, emphasis mine).
> Some workarounds may be required when using traditional TeX or pdfTeX with UTF-8 encoding because `inputenc`'s `utf8` module does not cover all of Unicode. Roughly speaking, it only covers the Western European Unicode range. **When loading `inputenc` with the `utf8` option, `biblatex` will normally instruct Biber to reencode the bib data to UTF-8 .** This may lead to `inputenc` errors if some of the characters in the `bib` file are outside the limited Unicode range supported by `inputenc`.

If you know that and check the `.bbl` file, you see what is going on. Admittedly, that is quite advanced knowledge (and you probably need to know that you are looking for the passage to find it), hence the many linked questions about this subject.

That all said, I am of course open for suggestions what should be done here.

**Comment by moewew** [comment]
I'm closing this as 'won't fix' for now since this works as expected. If there are suggestions to make the error handling better I'd be happy to re-open this and discuss this further, but at the moment there is not a lot that can be done here.
