### ISSUE TITLE
Publisher as optional field for articles

### ISSUE THREAD

**Issue by tobiasdiez** [plk/biblatex#837]
A lot of databases (e.g. MathSciNet) happen to export a publisher even for articles (the publisher of the journal). I'm unsure about the "correct" behavior but you might want to add "publisher" as an optional field.

**Comment by moewew** [comment]
I don't think you are asking for that, but to be absolutely clear (and for the benefit of other people who might be interested in that): I don't think it would be a good idea to add `publisher` to the `@article` driver, i.e. to the fields actually used by the standard styles. That is for two reasons.

1. Backwards compatibility. At present the `publisher` field is ignored for `@article`s, but there are some data providers that fill export to that field, so we have to assume some people have the field populated, if it were printed all of a sudden, those people would see drastic changes in their document.
2. I know of no prescriptive style guide (well, OK except for ISO 690, which seems to be a bit on the fence on that one, https://tex.stackexchange.com/q/438515/35864, but frankly I think ISO 690 is not great) that wants the `publisher` printed for `@article`s. There is also no (great) precedent in existing and well-loved  `.bst` styles. Hence, there is no compelling reason to show the `publisher`. In fact it will go against established practices.

On balance then I would certainly vote not to include `publisher` in the actual output of the `@article` driver.

---

But I assume you are actually talking about the abstract data model with its mandatory and optional fields as laid out in the `biblatex` documentation. I don't feel as strongly about that as I feel about including `publisher` in the driver, but I'm leaning towards not adding `publisher` to the list of optional fields.

The main purpose of §2.1.1 *Regular Types* with its required and optional fields is described as
> The lists below indicate the fields supported by each entry type. Note that the mapping of fields to an entry type is ultimately at the discretion of the bibliography style. The lists below therefore serve two purposes. They indicate the fields supported by the standard styles which come with this package and they also serve as a model for custom styles.

Note that there is no further technical definition of what 'required' and 'optional' exactly means. By §2.3.2 *Missing and Omissible Data* you are allowed to leave out 'required' data to some extent if not available. In practice the fields listed as 'optional' are usually supported in the sense that they are printed in the output (for the standard styles) when they are supplied in the input. So it would make little sense to add a field to the 'optional' list if it not used at all. As far as the standard data model is concerned, `publisher` is not a field that is considered for `@article` at all - it is neither a required nor an optional field.

I might be pushing the analogy, because `publisher` is a field you might conceivably appear in the bibliographic output of and `@article` (at least semantically it makes sense), but `booktitle` is not an 'optional' field for `@article` either (even though it receives the same treatment as `publisher` for `@article` - it is ignored by the standard styles) and neither is `author` for `@collection`. The fields listed as 'optional' are really fields that the standard styles would print if they are given, they are not fields that would 'make sense' for an entry or fields that could conceivably be printed by custom styles.

To reiterate: First and foremost the lists in §2.1.1 *Regular Types* are descriptive of the behaviour of the standard styles. They are not (and are not supposed to be) prescriptive as an absolute norm for your `.bib` files. However, since the list "serve[s] as a model for custom styles" (p. 8 `biblatex` docs) and for the most part all `biblatex` styles have a fairly homogeneous data model, the list acts as a *de facto* guideline for many people.

---

I know (or at least I think) that this is probably not a useful answer for you, because I imagine you are mainly looking for guidance as to whether or not `publisher` should be listed in your (JabRef's) editor interface for `@article` entries. And at least for you I can see merit in both options:

- If you don't list the field, you strongly suggest to people that the field is non-standard for `@article`s and indicate that is is very likely to get ignored by most styles (just as it was ignored by your editor).
- On the other hand it makes sense for people to be able to modify a field that is exported by some (many?) data providers and it would be useful for people who use custom styles that *do* print the `publisher` for `@article`s (I'm not actively aware of any `biblatex` style doing that, but I haven't checked). Plus it is not absurd and completely far-fetched that the `publisher` field would apply to `@article`.

But I for one am not prepared to legitimise or sanction the practices of the data providers by adding `publisher` to the standard styles or by turning the status quo of a descriptive documentation of the data model for the standard styles into a description of a data model of all possible fields that 'make sense' for a particular entry type.

**Comment by moewew** [comment]
@tobiasdiez Does the above address your request or is there something else we need to discuss? I'm happy to re-think some of my positions here if I'm challenged.

**Comment by tobiasdiez** [comment]
Thanks a lot @moewew for your very detailed answer. Personally, I don't have a strong opinion on these mattes. My question was just triggered by the observation that many metadata providers apparently think that `publisher` is an important field for articles as well. 

You are right that my question also had the purpose to clarify the correct handling of the publisher field in JabRef. Right now it it neither displayed in the `Required fields` nor the `Optional fields` tab but under `Other fields`. If I follow your reasoning, then this looks like the correct handling: suggest that this field is non-standard while still offering the ability to edit it in case a user uses a custom reference style.

Again, thanks a lot for your time!
