### ISSUE TITLE
\relateddelim<relatedtype> does not work.

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#856]
`\relateddelim<relatedtype>` does not seem to have any effect.

`\begrelateddelim<relatedtype>` works as expected.

# MWE

In this MWE, "***" is printed at the beginning of the related entries, but "+++" is not printed between related entries as expected.

```TeX
\documentclass{article}
\usepackage[style=verbose]{biblatex}
\addbibresource{biblatex-examples.bib}
\newcommand*{\relateddelimmultivolume}{\addperiod\par +++\space\bibsentence}
\renewcommand*{\begrelateddelimmultivolume}{\addperiod\par ***\space\bibsentence}
\begin{document}
\null\vfill
Filler text \autocite{knuth:ct:related}.
\printbibliography
\end{document}
```

![output](https://user-images.githubusercontent.com/6268044/51252230-39d85a80-19eb-11e9-96ce-f6c63a6612c5.png)

**Comment by moewew** [comment]
My comment in https://github.com/dcpurton/biblatex-sbl/issues/92#issuecomment-454777964 must have come in just a tad too late.

This should be fixed with https://github.com/plk/biblatex/commit/5b0bb276e9677d941b30e16df5f486cdcf3597ff in `dev` (not released yet). If you'd like to test the fix, you can just get `standard.bbx`.

Since the `\expandafter` explosion isn't pretty suggestions for something more sensible would also be appreciated.
