### ISSUE TITLE
Improve ability to customise \volcite(s) postnotes

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#868]
In light of [this question](https://tex.stackexchange.com/questions/472242/removing-comma-after-shorthands-in-biblatex-chicago) on tex.stackexchange, I have some suggestions on how customising the printing of the `postnote` for `\volcite` and `\volcites` could be made easier.

This issue provides a starting point for discussion.

The question on tex.stackexchange was for `biblatex-chicago`, but even for the standard styles customising the `\volcite` postnote requires modifying back end macros. Getting things working with `\volcites` proved to be especially opaque (to me).

The requirements for the `\volcite` `postnote` in the tex.stackexchange question were:

1. Output `, volume:page` (e.g., Author, *title*, 2:5).
2. If there is no `postnote`, output `, vol. volume` (i.e., Author, *title*, vol. 2).
3. If there is a `shorthand`, output ` volume:page` (i.e., SHORTHAND 2:5).
4. If there is a `shorthand` but no `postnote`, output `, vol. volume` (i.e., SHORTHAND, vol. 2). 

There are a few thing that would help make this easier:

1. Make `\postnotedelim` context sensitive.
2. Provide an `\ifvolcite` test.
3. Provide a `volcitevolume` field and a `volcitepages` field (formats already exist for these).

# MWE

Caveat: I'm not at all sure if my usage of `\eappto` to provide `volcitevolume` and `volcitepages` in `\volcites` is the right way of doing things.

Also note that `\mkvolcitecmd` no longer uses its arguments.

The back end changes below also make things substantially easier for the original `biblatex-chicago` question.

```TeX
\documentclass{article}
\usepackage[style=verbose]{biblatex}
\addbibresource{biblatex-examples.bib}

% Back end changes

\makeatletter

\newtoggle{blx@volcite}

\protected\def\ifvolcite{%
  \iftoggle{blx@volcite}}

\DeclareDelimFormat{postnotedelim}{\addcomma\space}

\renewbibmacro*{postnote}{%
  \iffieldundef{postnote}
    {}
    {\setunit{\printdelim{postnotedelim}}%
     \printfield{postnote}}}

\renewrobustcmd*{\volcitecmd}{%
  \AtNextCite{%
    \DeclareFieldAlias{postnote}{volcitenote}%
    \toggletrue{blx@volcite}}%
  \begingroup\let\blx@citeargs\blx@volciteargs}

\long\def\blx@volciteargs@i#1[#2]#3{%
  \def\abx@field@volcitevolume{#3}%
  \undef\abx@field@volcitepages
  \eappto\blx@tempe{%
    \def\noexpand\abx@field@volcitevolume{#3}%
    \undef\noexpand\abx@field@volcitepages}%
  \@ifnextchar[%]
    {\blx@volciteargs@ii{#1}{#2}{#3}}
    {\blx@citeargs@iii{#1{#2}{{#3}{}}}}}

\long\def\blx@volciteargs@ii#1#2#3[#4]{%
  \def\abx@field@volcitepages{#4}%
  \eappto\blx@tempe{\def\noexpand\abx@field@volcitepages{#4}}%
  \blx@citeargs@iii{#1{#2}{{#3}{#4}}}}

\renewrobustcmd*{\multivolcitecmd}{%
  \AtNextCite{%
    \DeclareFieldAlias{postnote}{volcitenote}%
    \toggletrue{blx@volcite}}%
  \def\blx@hook@mcite@before{%
    \global\undef\blx@hook@mcite@before
    \let\blx@citeargs\blx@volmciteargs}}

\renewrobustcmd*{\mkvolcitenote}[2]{%
  \printfield{volcitevolume}%
  \setunit{\printdelim{volcitedelim}}%
  \printfield{volcitepages}}

\makeatother

% Example user level usage

\DeclareDelimFormat{volcitedelim}{\addcolon}
\DeclareDelimFormat[shorthandvolcite]{postnotedelim}{\addspace}

\DeclareFieldFormat{volcitevolume}{%
  \iffieldundef{volcitepages}
    {\bibstring{volume}\ppspace#1}
    {#1}}
\DeclareFieldFormat{volcitepages}{\mknormrange{#1}}

\renewbibmacro*{cite:shorthand}{%
  \ifvolcite
    {\iffieldundef{volcitepages}
       {}
       {\delimcontext{shorthandvolcite}}}
    {}%
  \printtext[bibhyperlink]{\printfield{shorthand}}}

\begin{document}
\volcite{5}[50]{kant:kpv}

\volcite{5}[50]{kant:kpv}

\volcite{5}{kant:kpv}

\cite[50]{kant:kpv}

\citereset

\volcites{5}[50]{kant:kpv}{5}[200]{kant:ku}

\volcites{5}[50]{kant:kpv}{5}{kant:ku}

\volcites{5}{kant:kpv}{5}[200]{kant:ku}

\citereset

\cite[50]{kant:kpv}

\cite[200]{kant:ku}

\cites[50]{kant:kpv}[200]{kant:ku}
\end{document}
```

## Output

![output image](https://user-images.githubusercontent.com/6268044/52021293-73a97500-2544-11e9-8388-46869b3501dd.png)

**Comment by moewew** [comment]
I really like the idea of a context-sensitive `postnotedelim`. The `\ifvolcite` toggle also seems like a good idea, since it is otherwise hard do detect a `\volcite` situation (after all `\volcite` is just an extension of existing cite commands, who are going to keep their delimiter context and all).

I can also see why it would be useful to have `volcitevolume` and `volcitepages` fields. But injecting the definitions at the right time seems quite tricky. The `\blx@tempe` approach works fine as far as I can tell, but of course it would be preferable if we could avoid messing with things that are clearly internal. Unfortunately, `\AtNextCite` and friends did not work for multi-cite and I could find no other clever way to inject additional pre-code for single citations.

**Comment by dcpurton** [comment]
Yes, the way `biblatex` constructs the multicite commands really confused me. I think you have to hook into the building of `\blx@tempe` somewhere. I'm just not sure if I've done it in the right place.

I tried various `\blx@multi…` macros before finally getting it to work in the `\blx@volciteargs…` macros. One question is that since these latter macros are called by the single and multi cite commands, `\blx@tempe` is appended to even for single cite cases. I guess this could be catered for though if it proves to be an issue.

**Comment by moewew** [comment]
As far as I can tell the `\blx@tempe` is the best place we have at the moment and I'm quite happy (and impressed) that you found it, I doubt I would have managed the journey into the multi-cite argument collector and made it out alive with the right macro to tweak.

`biblatex` collects all multi-cite arguments in `\blx@multiparse` and related macros so that `\blx@tempe` holds a list of collected citations and might look like
```
> \blx@tempe=macro:
->\blxmciteicmd {1}{cite}{}{{4}{54}}{kant:kpv}{} \multicitedelim
\blxmciteicmd {2}{cite}{}{{5}{201}}{kant:ku}{}.
```
with your patch we insert the `volcitepages` and `volcitevolume` definitions in between the `\blxmciteicmd`s:
```
> \blx@tempe=macro:
->\def \abx@field@volcitevolume {4}\undef \abx@field@volcitepages \def \abx@fie
ld@volcitepages {54}\blxmciteicmd {1}{cite}{}{{4}{54}}{kant:kpv}{}\def \abx@fie
ld@volcitevolume {5}\undef \abx@field@volcitepages \def \abx@field@volcitepages
 {201}\multicitedelim \blxmciteicmd {2}{cite}{}{{5}{201}}{kant:ku}{}.
```
It would be more convenient if there was a way to get the information 'directly' into the cite command, but I couldn't find in interface for that. Then we could avoid resetting/`\undef`ing the `volcitepages` field because grouping would do that for us.

In the implementation I'm currently working on I split the definitions of `\blx@volciteargs@i` and `\blx@volciteargs@ii` for `\volcite` and `\volcites`. The one for `\volcite` uses `\AtNextCite`, the one for `\volcites` adds to `\blx@tempe`, that seemed the safest to me.

I'm still working on a few details, but hopefully I'll have something for you to look at in the next few days.

**Comment by dcpurton** [comment]
Actually, maybe we can do it better.

I originally discarded this method, because I was patching things and you have to redefine all the `\*cite` commands. But surely the right place to set `volcitevolume` and `volcitepages` is at the same time as we set `postnote`, which is (I think) in `\blx@defcitecmd@v`.

Something like this works:

```TeX
\long\def\blx@defcitecmd@v#1#2#3#4#5{%
  \protected\long\csdef{blx@citei@#1}##1##2##3##4{%
    \ifblank{##1}
      {}
      {\def\abx@field@prenote{##1}}%
    \ifblank{##2}
      {\let\blx@thenotecheck\relax}
      {\def\abx@field@postnote{##2}%
       \ifvolcite
         {\blx@defvolcitepostnote##2}
         {}}%
    \def\blx@precode{\delimcontext{#1}#2}%
    \def\blx@loopcode{#3}%
    \def\blx@dlimcode{#4}%
    \def\blx@postcode{#5}%
    \def\blx@postpunct@saved{##4}%
    \blx@citeloop{##3}%
    \endgroup}}

\long\def\blx@defvolcitepostnote#1#2{%
  \def\abx@field@volcitevolume{#1}%
  \ifblank{#2}
    {}
    {\def\abx@field@volcitepages{#2}}}
```

**Comment by moewew** [comment]
Ooohhh, that is so much nicer. Thank you very much for that idea.

I'll push the necessary changes to a public branch for you to comment on when #866 is sorted and merged (I want to avoid multiple merge commits or having to rebase a public branch).

**Comment by moewew** [comment]
Thanks for the feedback. PR #869 has been merged. Thank you also for the suggestion and the implementation.

**Comment by moewew** [comment]
`biblatex` 3.13 with the necessary changes has just been released, it would be great if you could update your answer on TeX.SX to showcase the new features.
