### ISSUE TITLE
Document \mkbibquote interaction with \MakeSentenceCase

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex#871]
In styles that use `\MakeSentenceCase`, content of macros such as `\mkbibquote` and `\enquote` is not lower-cased unless it is embraced in an extra pair of brackets: `{\mkbibquote{Foo}}` This seems to be due to the way biber (or, for that matter, `btparse`'s `bt_change_case()` is designed; see https://github.com/jgm/pandoc-citeproc/issues/189).

IIUC the behavior is biber-specific and thus probably differs from the `bibtex` backend.

Note also that the extra embracing does not work in some cases at all:

1. Beginning of titles: This gives all-caps output (e.g., `title = {{\mkbibquote{Quote Me!}}`)
2. Protection of enquoted stuff from lowercasing (e.g., `title = {A \mkbibquote{Quoted {Name}}}`, where Name gets lowercase despite the extra brackets)

In these cases, I see no way how these macros would work.

I think all this should be documented at least.

(see also https://tex.stackexchange.com/questions/16467/)

**Comment by jspitz** [comment]
Same of course for `\emph `and other non-quoting macros. See #357. I understand that the ticket was marked WONTFIX since the `biber` behavior won't be changed. Still I think this needs to be documented clearly.

**Comment by moewew** [comment]
See also https://github.com/plk/biblatex/issues/459

The case changing macro on the LaTeX side is mighty complicated and I for one won't touch it with a barge pole (and if I did, pole or otherwise, I would probably break it completely). So unless someone else steps in to save us here, I guess we will just have to document the weirdness. See also https://retorque.re/zotero-better-bibtex/faq/

**Comment by jspitz** [comment]
Yes, this ticket is only aiming for documentation.

**Comment by moewew** [comment]
Which is tricky enough, because we need to find out how stuff behaves and document that...

**Comment by jspitz** [comment]
Some issues seem clear to me:
* Whenever something is embraced in the first position, it is handled as a single token and thus all-cased by the mechanism that assures the first token in the title is upper-cased.
* double brackets undo case protection, but triple brackets cause no further undo

So I would write something along this line:

Note that if you use `\mkbibquote` in a style which uses sentence case transformation, you need to embrace it by an extra pair of brackets. Alas, this does not work if `\mkbibquote` is the first element in the title. In this case, you need to resort to quotation mark macros rather than quote macros (e.g., `\textooquote` if you use csquotes, otherwise `\textquotedblleft` etc.). The same applies if you want to protect something inside a group that is un-protected for sentence casing.

**Comment by moewew** [comment]
I have tried to document most of `\MakeSentenceCase`'s behaviour and contrast it to BibTeX's `change.case$` in  in https://github.com/plk/biblatex/commit/863fea969a9f1d37d7f944265cb276cf18293334. I may well have missed something or made the entire thing more complicated than it is, so comments would be appreciated.

Since `\mkbibquote` is no different from other robust commands in its behaviour in `\MakeSentenceCase` I have not added anything to *its* documentation. I realise that this might not be ideal for the average user who sees `\mkbibquote` falling apart and looks up its documentation oblivious of the fact that `\MakeSentenceCase` (which may very well be hidden behind the style) is the culprit here, but we simply can't document the shortcomings of `\MakeSentenceCase` for every robust command that takes arguments.

If anybody with an idea for a more robust implementation of `\MakeSentenceCase` and the will to do it reads this: Your help would be very extremely welcome.

**Comment by jspitz** [comment]
Thanks for that. I fear, though, that ordinary users won't be able to make much sense of that. I.e., they will still not understand why `\enquote{stuff} `or `\emph{stuff}` will not work as they probably think it should

**Comment by moewew** [comment]
I'm open for suggestions, but this is the best I can do. Sorry.

**Comment by jspitz** [comment]
I suggested something above. This might need to be formulated more generally, but I still think something like this would help:

Note that if you use commands such as `\mkbibquote` or `\emph` in a style which uses sentence case transformation, you need to embrace it by an extra pair of brackets, i.e. `{\mkbibquote{foo}}` rather than `\mkbibquote{foo}`. Alas, this does not work if this macro is the first element in the title. In this case, you need to resort to workarounds (in case of quotation, you can use quotation mark macros rather than quote macros, e.g., `\textooquote` if you use csquotes, otherwise `\textquotedblleft` etc.). The same applies if you want to protect something inside a group that is un-protected for sentence casing.

**Comment by moewew** [comment]
Very well, give https://github.com/plk/biblatex/commit/a291e72a6c8ba2b896eb3f53ada6cc938c2cfa86 a spin and tell me what you think.

**Comment by josephwright** [comment]
I can (probably) fix the code with a lot of effort using some ideas from `expl3`, though there we've concluded that BibTeX's brac-based approach for skipping case changing is sub-optimal ...

**Comment by moewew** [comment]
@josephwright If you have the time and ideas to make things work better that would be appreciated. For myself I have come to the conclusion that the fact that braces are completely overloaded with meaning here makes things just too messy. Maybe we need to overhaul the entire thing with a different way to mark up the case protection.

**Comment by jspitz** [comment]
> Very well, give [a291e72](https://github.com/plk/biblatex/commit/a291e72a6c8ba2b896eb3f53ada6cc938c2cfa86) a spin and tell me what you think.

Excellent. Thanks.

**Comment by jspitz** [comment]
As to the braces, I for one would be very much in favor of some semantically clear solution, i.e. a dedicated macro `\pCase{}` or somesuch. And let the braces be ignored.
But of course compatibility will be an issue for many users.

**Comment by moewew** [comment]
See also https://tex.stackexchange.com/q/476546/35864
