### ISSUE TITLE
Recognise `@dataset` as entry type

### ISSUE THREAD

**Issue by alex-ball** [plk/biblatex#880]
After much campaigning, the practice of directly citing datasets is becoming mainstream. It would therefore be good if biblatex would explicitly recognise `@dataset` as an entry type, if only among the list of 'non-standard' entry types.

A quick check shows support for it here:

- RevTeX (bst)
- thuthesis (bst)
- cquthesis (bst)
- gbt7714 (bst)
- biblatex-gb7714-2015
- bath-bst (bst)
- biblatex-bath
- oxref

Some literature and resources on data citation:

- CODATA/ITSCI Task Force on Data Citation. (2013). Out of cite, out of mind: The current state of practice, policy and technology for data citation. _Data Science Journal,_ 12, CIDCR1–CIDCR75. DOI: [10.2481/dsj.OSOM13-043](https://doi.org/10.2481/dsj.OSOM13-043).
- _Data Citation Synthesis Group: Joint Declaration of Data Citation Principles._ (2014). Martone M. (ed.) San Diego CA: FORCE11. DOI: [10.25490/a97f-egyk](https://doi.org/10.25490/a97f-egyk)
- Ball, A. & Duke, M. (2015). _How to Cite Datasets and Link to Publications._ DCC How-to Guides. Edinburgh: Digital Curation Centre. Available online: <http://www.dcc.ac.uk/resources/how-guides>
- Rauber, A., Asmi, A., Uytvanck, D. van, & Pröll, S. (2015). Data citation of evolving data: Recommendations of the Working Group on Data Citation (WGDC). DOI: [10.15497/RDA00016](https://doi.org/10.15497/RDA00016)
- Lammey, R., & Cousijn, H. (2018). _Data citation: Let's do this._ Available from the Crossref blog: <https://www.crossref.org/blog/data-citation-lets-do-this/>
- _DataCite – Cite Your Data._ (n.d.) Available from the DataCite website: <https://datacite.org/cite-your-data.html>
- [Elsevier on its adoption of the above Joint Declaration of Data Citation Principles](https://www.elsevier.com/about/open-science/research-data/data-citation)
- [Data Citation Index](https://clarivate.com/products/web-of-science/web-science-form/data-citation-index/)

**Comment by plk** [comment]
I am certainly amenable to this since biblatex is often used in academia. @moewew - what are your thought?

**Comment by moewew** [comment]
I don't think there should be any backwards compatibility issues to worry about here (if done right) and it seems like a sensible addition, so I'm in favour of adding `@dataset`.

I think that the output from the `@misc` driver would be good enough, so I'm leaning towards including `@dataset` in the non-standard types and alias its driver to `@misc`. But if you think that something important would be missing if we did that we can also discuss a dedicated driver.

On a similar note: We may want to think about adding explicit maps for all non-standard types to avoid the warning that the current catch-all alias produces. (It seems to me that warning may hold people back, cf. also the `@software` discussion in https://github.com/plk/biblatex/issues/753).

**Comment by moewew** [comment]
On second thoughts, there are some types in the *non-standard* subsection that very likely need special treatment and it definitely makes sense to warn about those if there is no driver for them (I'm thinking `@jurisdiction`, `@legislation`, `@legal`, `@standard`, but also `@bibnote` and to a lesser degree `@audio`, `@video` and the `@performance` types).

So either we say that some of the *non-standard types* don't issue a warning (because `@misc` is good enough) and all others do and document which type does what, or we "upgrade" those for which `@misc` is good enough to *regular types* and explain the alias there (like `@suppbook`). Haven't thought through the implications of that, though.

**Comment by alex-ball** [comment]
Looking at it, I think `@misc` is good enough for `@dataset`.

In my line of work we tend to think of datasets having publishers, but the more generic `organization` is probably better to encompass domains and situations where `publisher` might seem odd.

The only peculiarity I've come across is the [Dataverse recommendation](https://dataverse.org/best-practices/data-citation) to include a universal numerical fingerprint (UNF), but it's rarely used by anyone else and can be handled by `note` or `addendum`.

**Comment by moewew** [comment]
Is the UFN a common thing? At first I'd have thought it could be an `eprint`, but that does not seem to be appropriate, so we would need a new field if we wanted to handle it properly.

I'm always a bit cautious about introducing new fields because I worry about precedent, but if there is real demand for it... Adding a new field to a new driver is less dangerous than adding something to existing drivers, so a new field would quite probably also mean a new driver. (And the UNF seem to make no sense for things other than a `@dataset`.) If we add a new driver we can of course add more stuff, so if there is anything where `@misc` could be better, we could address that.

**Comment by plk** [comment]
I'm in favour of a new driver for this - it is increasingly the case that datasets are becoming first-class, archived assets. The reason for this is, I think, that they are always digital assets these days and that makes referencing them actually useful. In the past, referencing a book of data was more of a curio because there was no easy way to use the contents of the reference without starting a new, expensive research project. Today, data analysis is almost trivial and so digital datasets are the equivalent of reaching for a book on a shelf and actually checking a quote or reference.

**Comment by alex-ball** [comment]
I've not seen UNF used outside Dataverse-powered repositories, and even within them, UNFs are not generated for every dataset (far from it). I would say it is a niche thing.

But on a different tangent, thinking about it, there are some places (e.g. [UK Data Service](http://data-archive.ac.uk/conditions/citing-data)) that release editions rather than versions of datasets.

**Comment by moewew** [comment]
Mhh, does it make sense to distinguish `edition` and `version`? Or would it be reasonable to say that both would mean the same thing and that we arbitrarily choose the more generic `version`?

Re the UNF: I'd like to keep the fields in `biblatex` relevant and useful, so I'm a bit sceptical. On the other hand I certainly don't know if the UNF will catch on and from a compatibility standpoint it would be better to have everything w.r.t. the new `@dataset` done at once rather than having to revisit this field in the future should it turn out that it (or a competitor) makes it. We can of course add a more generic field like `fingerprint` or `uniqueid`, ... if the general idea is here to stay.

**Comment by alex-ball** [comment]
Semantically, no, there's no great difference between `edition` and `version`, but syntactically one would be written "11th ed." and the other "v. 11" (say). Presuming people want to cite accurately according to the practice of the given archive, if you knock them into one field you're then looking at having to provide an option for which way to render the number, which is comparatively messy.

Re UNF, I'm sceptical too, but identifiers based on cryptographic hashes do get suggested from time to time. I recently saw something similar suggested for software source code, the [Software Heritage ID](http://bit.ly/swhpids), though in that case they are also resolvable and thus a bit more like `eprint`.

**Comment by moewew** [comment]
Sorry, I kind of lost track of this issue here.

I'm a bit unsure about the `edition`/`version` thingy. On the one hand I understand the desire to stay as close to the official wording and 'please cite as' instructions as possible, which makes it attractive to have both `edition` and `version`. On the other hand I think there is merit in having a streamlined data model without too many redundancies and possible points of confusion (should I take `version` or `edition`?).

**Comment by alex-ball** [comment]
If you are choosing between the two, take `version`, as I believe it is the more common of the two.

**Comment by moewew** [comment]
That would have been my preference as well. I guess the more interesting question then is whether we should have both `version` *and* `edition` or if `edition` is good enough. I tend to think the latter, but I guess I could be convinced otherwise if there are good examples or arguments out there.

**Comment by moewew** [comment]
See https://github.com/plk/biblatex/commit/95ca156e116e5d2c4b76b93b5e325367113fb166

@alex-ball Does that look OK for you? Do you think we need the UNF? Could you find more examples that show that we need `edition` in addition to `version`?

**Comment by alex-ball** [comment]
Well, [here is an example](https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=6846) of the example I gave:

Office for National Statistics, Social Survey Division. (2012). *International Passenger Survey, 2011.* [data collection]. *6th Edition.* UK Data Service. SN: 6846, http://doi.org/10.5255/UKDA-SN-6846-6

With this bib entry I can get near enough:

```tex
@misc{ons2012ips,
author = {{Office for National Statistics, Social Survey Division}},
date = {2012},
title = {International Passenger Survey, 2011},
type = {Data collection},
note = {6th Edition},
organization = {UK Data Service},
eprinttype = {SN},
eprint = {6846},
doi = {http://doi.org/10.5255/UKDA-SN-6846-6}}
```

Output with `authoryear`:

> Office for National Statistics, Social Survey Division (2012). *International Passenger Survey, 2011.* Data collection. 6th Edition. UK Data Service. doi: `http://doi.org/10.5255/UKDA-SN-6846-6`. SN: `6846`.

Of course that means the edition string is hard coded and won't respond to language, abbreviation settings or individual style conventions. The question is whether enough people will be affected by it to justify the additional effort.

Though looking at it, a fairly easy resolution to this would be to alias it to `manual` instead.

Regarding the UNF, again this can be handled by a `note` field and is only really seen in the wild for some datasets of a particular system, but unlike edition is not really affected by language, abbreviation, or the need to harmonise with a particular style manual's convention since none (as far as I know) include it at all.

I am speaking at a conference session on data citation next week. It will be mainly Earth sciences there, so not representative of all domains, but if I raise the question it might help to get a sense of these issues.

**Comment by moewew** [comment]
At the moment I think of the `edition`/`version` thing like I think of `issue`/`number`. Some journals may call the subdivision of a volume *issue*, some may just say *nr.* (or *number*), but in any case the number belongs into `biblatex`'s `number` field, `issue` contains other identifiers that should go with the date. I'd be inclined to say the same here: Fundamentally (semantically), `version` and `edition` mean the same thing and the words the data providers use should be secondary. I can see that with the advent of *please cite* notices people are more inclined to follow those and would be more interested to stay closer to the terminology of the data provider. If there is a strong feeling that this is desired or there are examples where both `version` and `edition` are needed, then that would be quite relevant. If both fields are needed, an alias to `manual` seems like a good idea to get around having to define yet another full driver.

It would be great if you could test the waters at the conference and report back what the feelings are.

**Comment by alex-ball** [comment]
I asked the UK Data Service directly about this, and this is what they said:

> The UK Data Service follows international archival/library standards, meaning that an 'edition' is different to a 'version'. 
>
> A version is generally a low-impact change, for example a small change to the catalogue record, variable or documentation metadata (fixing a typo, a slight variable labelling change, etc.). It results in a new release of said metadata, but does not involve a new edition statement or an increment in the DOI number.
>
> A new edition is released after a significant change to data (such as a new or replaced data file or documentation, the addition of a new wave to a longitudinal study, etc.). At this point, a new edition statement is added to the citation and the DOI is incremented by one. See for example the edition history for the sixth Millennium Cohort Study at <https://beta.ukdataservice.ac.uk/datacatalogue/doi?id=8156>.

So you could have a situation of wanting to cite a particular version within a particular edition.

**Comment by moewew** [comment]
Thank you very much for following up on this. I can't say I'm completely happy with the outcome, but I guess this settles it and we need both `version` and `edition`.

If we want to use an alias, our only option is to alias `@dataset` to `@manual`. The outcome would be OK, but the map might be semantically questionable.

**Comment by moewew** [comment]
A suggestion to alias `@dataset` to `@manual` is at https://github.com/plk/biblatex/compare/dev...moewew:datasetmanual

I'm not entirely happy with the apparently arbitrary decision to alias this one type to `@manual` instead of the usual catch-all `@misc`, but duplicating the entire driver without any change seems even more useless.

@plk and @alex-ball What do you think? Should this be merged?

**Comment by plk** [comment]
I would, thinking forward, propose that we have a real, new driver for `@dataset`. It might be the same as manual now but I would expect this to evolve as things like UNF become standardised. I would also expect standard for data format to stabilise at some point and will likely result in a common field because this would be an obviously very useful piece of information, especially with URLs to the data as this would mean code could fetch and process the data from just the citation. `@dataset` -> `@manual` seems a bit arbitrary to me as it's not a semantic connection, it's just that `@manual` currently has a congruent set of fields.

**Comment by moewew** [comment]
OK, I absolutely agree that the `@dataset`->`@manual` thing looked very arbitrary. https://github.com/plk/biblatex/compare/dev...moewew:datasetown has a dedicated driver for `@dataset`.

**Comment by moewew** [comment]
Merged the dedicated `@dataset` driver. @alex-ball Testing would be very much appreciated.

**Comment by moewew** [comment]
`biblatex` 3.13 with support for `@dataset` is on CTAN now. I didn't have an extensive set of tests for `@dataset` entries, so testing would be extremely appreciated so we can iron out some issues while the driver is young.
