### ISSUE TITLE
manual clarification: firstinits

### ISSUE THREAD

**Issue by skramm** [plk/biblatex#892]
Manual:
The package option `firstinits` (referenced [here](https://tex.stackexchange.com/a/98589/11083)) is not documented in the manual. (I have version 3.9 from November 21, 2017, also checked current CTAN version:  3.12 from October 30, 2018)
It is cited in "F - Revision History" as having being renamed:
> 3.3 2016-03-01
> Renamed firstinits and sortfirstinits

But:
1. I just can't find the new name of this option... searching on "first name" fails. I feel how to do this could be clarified in the manual.
2. FWIW, it still works with the 3.9 release.

**Comment by skramm** [comment]
According to my log file, it was renamed to `giveninits`. But this option seems to be also undocumented.

**Comment by moewew** [comment]
The option has been generalised to a family of options that can apply to all name parts. Hence it is documented as `<namepart>inits`. Of course you sort of need to know that to find the documentation, so it might make sense to add a short word in the docs.

**Comment by moewew** [comment]
See https://github.com/moewew/biblatex/commit/0643560751956f2cf103691eeafad733b541fa96

**Comment by moewew** [comment]
`<namepart>` should be seen as a variable here that can take as value the name of a valid namepart. In your case the relevant namepart is called `given`, so you would write
```latex
\usepackage[giveninits=true]{biblatex}
```
just as the `.log` message told you when you used the outdated name `firstinits`:
```
Package biblatex Warning: 'firstinits' option is deprecated.
(biblatex)                Please use 'giveninits' instead.
```

You could also say `familyinits=true`, since formally `familyinits` is implemented, but the standard styles don't act on the option, so setting it is pretty much pointless.

The problem with examples in the documentation is that the manual is quite long already. Adding examples for every single thing will only make it even longer and have even more people saying: The documentation is too long, I don't want to read 300-odd pages just to ... Plus, there is always the question of where to put stuff so that people can actually find it easily.

I'll see what I can do, but suggestions would be extremely welcome.

**Comment by skramm** [comment]
> The problem with examples in the documentation is that the manual is quite long already. Adding examples for every single thing will only make it even longer and have even more people saying: The documentation is too long,

I understand your point, of course. But the commit you attached seems fine to me, it doesn't add too much stuff. I'll close this issue, thanks to you (and other contributors) for the hard and valuable work on this package!
