### ISSUE TITLE
\abx@extras@<language> is added to \extra<language> without defining \abx@extras@<lanugage>

### ISSUE THREAD

**Issue by komascript** [plk/biblatex#894]
If `\extras`*language* is defined, biblatex adds `\abx@extras@`*language* to it without making sure, that `\abx@extras@`*language* is really defined. This results in an error message if `\extras`*language* is executed but `\abx@extras@english` is not defined, e.g.

```
\documentclass{article}
\usepackage[british]{babel}
\def\extrasenglish{\def\testname{Test}}
\addto\extrasbritish{\extrasenglish}
\usepackage{biblatex}

\begin{document}
Test
\end{document}
```

results in an error message:

```
./test.aux:6: Undefined control sequence.
\extrasenglish ...@resetpunct \abx@extras@english 
                                                  \abx@strings@english 
l.6 \babel@aux{british}{}
```

Note, this is a simplified example. In reality the problem occurs, while testing whether or not a term definition is part of either `\captionsenglish` or `\extrasenglish`.

To solve the problem you could e.g., add `\csname abx@extras@english\endcsname` or `\@namese{abx@extras@english}` instead of `\abx@extras@english`.

**Comment by moewew** [comment]
Thanks for reporting this. A first fix is at https://github.com/plk/biblatex/commit/26c2072829d78447a9bb1931bd22662b34a19e18. Since we have `etoolbox` available I went for `\csuse` and not `\@nameuse` or an unexpanded `\csname ...\endcsname`, but the effect should be the same.

That said, we should probably not add the macros at all if we don't load the language properly.

**Comment by moewew** [comment]
`biblatex` 3.13 with the two fixes discussed here is available on CTAN now.
