### ISSUE TITLE
Refcontext assignment confused by bibliography

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#904]
Inspired by https://tex.stackexchange.com/q/499458/35864, but with a simplified and more problematic MWE.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=numeric, sorting=ynt, backend=biber]{biblatex}


\addbibresource{biblatex-examples.bib}

\nocite{nussbaum}

\begin{document}
\cite{sigfridsson}

\printbibliography

\cite{sigfridsson}

\newrefcontext[sorting=ydnt]
\printbibliography
\end{document}
```
produces "\[1\]" for the first citation and "\[2\]" for the second citation of `sigfridsson`.

!["\[1\]" for the first citation and "\[2\]" for the second citation of `sigfridsson` + bibliographies](https://user-images.githubusercontent.com/6755835/61058911-67311e80-a3f8-11e9-8d96-ccdb06fc0726.png)

The expected output would have been "\[1\]" for both citations, since according to the docs the last bibliography determines the refcontext.

*edit* see also https://tex.stackexchange.com/q/508905/35864

**Comment by plk** [comment]
This is due to the strange workarounds for styles which use `\cite` in biblists. I think that the correct default output should really be `[2]` for both since they both occur in the global refcontext and so does the first `\printbibliography`. The docs are not quite right about this I think.

**Comment by plk** [comment]
On second thoughts, the current output is technically correct - the docs say "last bibliography" but this really means "most recently processed". The second printed bib in the example is the most recently processed list before the first citation is printed and the first bib is the most recently processed list for the second citation, since the bibs are processed before printing the citations. Not sure what to do about this. There are manual macros to assign citations to refcontexts where the defaults don't do what is required. For example, this works:

```
\assignrefcontextentries*[sorting=ydnt]{sigfridsson}
```

**Comment by parvardi** [comment]
Thanks @moewew for posting this here. I think plk's response makes sense and explains why this is happening. Can I use a command similar to`\assignrefcontextentries*[sorting=ydnt]{sigfridsson}` but for **all** my bib entries?

**Comment by plk** [comment]
Yes, there is a variant for all entries:

```
\assignrefcontextentries*[sorting=ydnt]{*}
```

**Comment by moewew** [comment]
I'll think about this a little more tomorrow, but I think I have a simple fix lined up that would produce the output I expected, namely "\[1\]" for both citations. I accept that the *last* bibliography is ambiguous in that it could mean the most recently processed or the last in the document, but I would like to point out that the refcontext is saved in the `.aux`, which means that before any `\printbibliography` we will always get the refcontext of the last bibliography of the previous run. I'd find it quite unfortunate that a citation can change refcontexts within the document without any input by the user.

**Comment by plk** [comment]
The problem is that `\printbibliography` saves a record of the last processed list that a citation entry was referenced in. This is due to some styles that do very complex things with citations in bib lists which don't occur anywhere else and this was, as I remember, quite a problem as it impacts some styles used for some relatively high profile projects. Otherwise, we could more simply say that citation data is pulled from the active refcontext.

**Comment by moewew** [comment]
Oh yes, `biblatex-chicago` could be an issue. I'll see if I can come up with a workaround that can at least work between bibliographies...

**Comment by moewew** [comment]
This must have been resolved at some point. See also https://github.com/plk/biblatex/issues/1217
