### ISSUE TITLE
Thin space in bibliography not working with amsmath loaded (biblatex + IEEE style)

### ISSUE THREAD

**Issue by pdsz** [plk/biblatex#910]
Related to [TeX.SX question #504138][1].

<hr>

```
\documentclass{article}

\usepackage{amsmath}

\usepackage[style=ieee]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
    @Article{A,
        title = {A\,b c},
    }
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
    Text~\cite{A}.
    \printbibliography
\end{document}
```
![Output](https://user-images.githubusercontent.com/54089256/62989973-73225d00-be4a-11e9-9aed-29e131b7d87b.png)
Apart from the incorrect output caused by the usage of the usage of thin space (`\,`), compilation with MikTeX ends with errors: `Missing number, treated as zero. \end`, `Illegal unit of measure (pt inserted). \end`.

[1]: https://tex.stackexchange.com/q/504138

**Comment by moewew** [comment]
If a bug report originated from (or is also posted on) a different site, please include links to the relevant discussions on both sites.

----

I've already answered over at https://tex.stackexchange.com/q/504138/35864, so this is mostly just a short recap.

The issue here is that `\MakeSentenceCase` is very sensitive to macro input and that `amsmath` redefines `\,` in a way to lose its robustness (at least first-expansion). But `\MakeSentenceCase` also has to go through the string character by character and the first-level expansion of `\,` with `amsmath` (`\tmspace+\thinmuskip{.1667em}`) then breaks because reading it in 'character by character' fashion doesn't take the argument structure of `\tmspace` into account.

I'm afraid I can't see any way to fix this in `\MakeSentenceCase` on the `biblatex` side, so I can only offer the workaround from TeX.SX.


1. Make `\,` robust again.

   ```latex
   \renewrobustcmd{\,}{\tmspace+\thinmuskip{.1667em}}
   ```

    After loading `amsmath`. (Note that `\renewrobustcmd` needs `etoolbox`, which in the MWE is loaded by `biblatex`, so this line should come after loading both `amsmath` and `biblatex`.)

2. `\protect` this `\,` in the `.bib` file (as suggested by [Mico](https://tex.stackexchange.com/users/5001/mico) [in the comments to the TeX.SX question](https://tex.stackexchange.com/questions/504138/thin-space-in-bibliography-not-working-with-amsmath-loaded-biblatex-ieee-styl#comment1273427_504138))

   ```latex
   @article{A,
     title = {A\protect\,b c},
   }
   ```

3. Use a different command that is still protected (as suggested by [David Purton](https://tex.stackexchange.com/users/87678/david-purton) [in the comments to the TeX.SX question](https://tex.stackexchange.com/questions/504138/thin-space-in-bibliography-not-working-with-amsmath-loaded-biblatex-ieee-styl#comment1273428_504138)), for example `biblatex`'s `\,` equivalent `\addnbthinspace`.

   ```latex
   @article{A,
     title = {A\addnbthinspace b c},
   }
   ```

4. 'Hide' the problematic parts of the string from `\MakeSentenceCase` with curly braces.

   ```latex
   @article{A,
     title = {A{\,}b c},
   }
   ```

---

Of course you could ask `amsmath` to make `\,` and friends robust directly instead of going via  a helper macro (according to `amsmath.pdf` they used the helper macro to save a few command sequence names, the number of CS names is not really an issue any more nowadays). But I'm not sure if they can (or want to) change their definitions after such a long time.

**Comment by moewew** [comment]
I guess this can be closed as *won't fix*, since I don't see the sentence casing algorithm fixed to deal with this any time soon and similar issues have to be resolved using one of the suggested workarounds.
