### ISSUE TITLE
Biblatex requiring permissions to write in local temp file

### ISSUE THREAD

**Issue by PyTeXJulia** [plk/biblatex#915]
Following the update to Biblatex (version 3.13) on Windows 10 via the MikTex Console writing permissions in the local temp folder are required. Is there a way to bypass this?  Is it possible to do the update other than with the MikTex Console? Which files actually are involved?  Could they also be saved to another directory?

**Comment by plk** [comment]
I doubt this has to do with biblatex - this sounds like a MikTeX issue? Biblatex/biber don't/can't enforce permission for writing any files.

**Comment by moewew** [comment]
I guess this is about Biber writing to the temp files. But I don't think there was a significant change here between 2.12 and 2.13.

According to  https://github.com/plk/biber/issues/70 it is possible to divert Biber's cache location, maybe that also helps with other temporary files. But in the end shouldn't you have full write access to your local temp folder?

**Comment by PyTeXJulia** [comment]
Okay. Thanks. The biber reference looks really helpful. The access is restricted due to Group Policy settings.

**Comment by moewew** [comment]
OK. I'm closing this since it is definitely not a `biblatex` issue. `biblatex` only writes files through LaTeX into the normal working directory and if your systems has issues with that than even very simple LaTeX documents won't compile. If this is a Biber issue (much more likely from what I read so far) and the linked issue does not help it would be better to open an issue at the Biber bugtracker (https://github.com/plk/biber/issues) to have things tracked in the right place.
