### ISSUE TITLE
APA style referencing for Devanagari script

### ISSUE THREAD

**Issue by NiranjanTambe** [plk/biblatex#920]
Hello all.
I have a feature request for the package biblatex.

APA style of referencing has one common feature of showing author-name's initial. Therefore if the author-name is 'Tambe Niranjan' It'll be shown as 'Tambe N.'

I want similar referencing style for Devanagari script. Let's say if the author-name is 'तांबे निरंजन', it should appear as 'तांबे नि.', but as the initial of the author name is composed of two characters i.e. न + ि biblatex eats up the diacritic and shows the author name as 'तांबे न.'

This is wrong as per the referencing conventions of India. 'नि' is considered as a full functioning unit in Devanagari script. Can we code a new feature in biblatex (especially for APA style), which will not eat-up diacritics of the author name?

**Comment by plk** [comment]
Yes, I would like to do this properly. Please can you put here the simplest possible example of the issue so I can look at it?

**Comment by NiranjanTambe** [comment]
Thanks for your prompt reply!

This
<https://tex.stackexchange.com/questions/507093/apa-style-references-in-devanagari-script>
is
a well formed StackExchange question, which describes my issue.

I am attaching both of the files (.tex and .bib files) and the font used.

**Comment by moewew** [comment]
Just to have this logged here as well (https://tex.stackexchange.com/a/507152/35864)

If Biber is better than `btparse` at figuring out the initials when the extended name format is in use, would it maybe possible to have `btparse` only deliver the full name parts and Biber always generate the initials in the more clever way? Is there anything that would make this tricky? Would performance be impacted?

**Comment by plk** [comment]
Unfortunately, this would be messy as `btparse` has a state machine to generate initials from names with macros at the beginning like `AUTHOR = {{\~ Z}elly, Arthur}` and other variants with alternative spaces/braces. The extended name format doesn't have this as it's just not necessary because it's mostly used with Unicode and also there is no need for messy initials auto-detection because they can just be specified explicitly. So, the initials generation in the extended name format is a clean Unicode version. If I hacked in the `btparse` rules, it would be slower too.

**Comment by plk** [comment]
@moewew - I take it back. I have managed to implement this in 2.14 which will now generate initials internally for all names, regardless of format. This means that the extended name format is not needed for cases such as this.

**Comment by moewew** [comment]
`biblatex` 3.14 and Biber 2.14 have been released, the initials issue should be fixed there.
