### ISSUE TITLE
mcite-version of \autocite

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#921]
See https://tex.stackexchange.com/q/507078/35864

There is no `mcite`-version of `\autocite` even though on first glance it seems easy to define one.

---

Secondary question: Can we make `\defbibentryset` and thus `mcite` available for BibTeX? Do we want to?

**Comment by plk** [comment]
Well, dynamic sets are a bit of a pain to implement, at least in `biber` because they essentially introduce virtual citation keys which don't correspond to any `.bib` entry. This needs some special handling and I suspect it would be the same in the `.aux` file, especially if they are used as xref/crossref etc.

**Comment by moewew** [comment]
Added `\mautocite` and `\Mautocite` in https://github.com/plk/biblatex/commit/d4135a0f0dd8580713ca8addeb2df1f380c80f28.

https://github.com/plk/biblatex/commit/0b89a7d8c9f332218f0d8458eef29b95afed9302 makes `\defbibentryset` an error when run with `backend=bibtex` since BibTeX doesn't support dynamic entry sets and I couldn't find a simple way of implementing it (as you say, it is tricky).
