### ISSUE TITLE
Incompatible

### ISSUE THREAD

**Issue by ecsunny** [plk/biblatex#927]
I have both biber (2.13) and biblatex (3.13) downloaded from CTAN (through MikTex), but when I run it in WinEdt, it says biber 2.13 is now working with control system 3.5 but not 3.6. I am confused if it's biblatex 3.13a which I downloaded, rather than either 3.13 or 3.14 (latest), that cause the incompatibility.

**Comment by moewew** [comment]
`biblatex` 3.13(a) and Biber 2.13 communicate via `.bcf` files of version 3.6. `.bcf` version 3.5 was used by 3.12/2.12.

If you have run the MikTeX updated twice in Admin and User mode, you should get matching versions of `biblatex` and Biber.

After upgrading you may have to remove the temporary files (`.aux`, `.bbl`, `.bcf`, ...) because files written by/for old versions of `biblatex`/Biber may cause issues. Those issues should go away once you remove the temporary files and recompile from scratch.

---

`biblatex` 3.14 (dev) has *not* been released yet and is not recommended for productive use.

**Comment by leo-liar** [comment]
I got the same error message as @ecsunny after an TeX Live update done recently.

After searching for a while I found that despite stating in the package manager that both _biber (x32)_ and _(x64)_ are up-to-date at version 2.13, my `texlive\bin\win64\biber.exe` was still at version 2.12 ( checked with `biber --version`).

I resolved this by downloading the most recent _biber (x64)_ binary via [SourceForge][1] and replacing the file manually. I think this may be applicable to MiKTeX as well. Here the local binary should be located at `MiKTeX\biber\bin\windows-x64\biber.exe` (or `\windows-x32\` respectively).

[1]: https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Windows/ "biber - Browse /biblatex-biber/current/binaries/Windows at SourceForge.net"

**Comment by moewew** [comment]
Usually you should not have to download Biber or `biblatex` from Sourceforge and install it manually. If your TeX distribution and your operating system are set up correctly, your TeX distribution should take care of updating things properly.

Problems could arise if you didn't run the MikTeX update in both Admin and User mode (on a shored installation) or if you have installed multiple TeX distributions that now interfere (likely because of bad path settings).

Downloading Biber from Sourceforge only cures the symptoms and not the disease and you will have to manually do that again if your TeX distribution updates `biblatex` in the future. It would be better to try and identify the underlying cause. But before you do that, double check that this is not simply an issue of old temporary files.

**Comment by ecsunny** [comment]
I find the 3.13, 3.13a, and 3.14 confusing, and the readme seems a little bit complicated for me.

Thanks for your reminder. After running MikTex twice, now Biblatex works!

**Comment by leo-liar** [comment]
@ecsunny I just downloaded `biber-MSWIN64.zip` from the link I provided and replaced my local `biber.exe` with the one from the archive. It identifies itself as version 2.13 which is what I needed according to the error message I got (same as you).

But as **moewew** correctly pointed out this is only a workaround and getting it to work with MiKTeX running regularly is definitely the better way.

**Comment by moewew** [comment]
I'm closing this since the problem appears to be solved. Please let me reiterate that downloading Biber (or `biblatex`) from SourceForge should be a last resort and is in general not necessary.
