### ISSUE TITLE
Announcements on CTAN

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#929]
I'm aware of #842 but, IMHO, `biblatex's` announcements on CTAN are missing. At least, in case of significant changes in a release (which is the case most of the time IIRC), an announcement on CTAN with a link to an easy to read `Changelog` would be helpful.

**Comment by moewew** [comment]
@plk Any comment here?

The CTAN upload process for `biblatex`+Biber seems to be a bit tricky to make sure that both packages are updated at the same time. Maybe that's why the announcement is dropped?

I think it would be extremely helpful to have a joint `biblatex`+Biber announcement like https://lists.dante.de/pipermail/ctan-ann/2019-October/012996.html. The announcement text need not be long, it can just point people to CHANGES.md.

**Comment by plk** [comment]
Is this driven by the "announcement" field in the CTAN upload? I never use this. I agree we should do more in this direction.

**Comment by moewew** [comment]
Yes, I think if you leave it empty, CTAN will not post an announcement. From the next release onwards I will post a pre-release message in #842 and then you can just copy the relevant bits of that message for the CTAN announcement.
