### ISSUE TITLE
No biber release compatible with biblatex 3.13a

### ISSUE THREAD

**Issue by cwittern** [plk/biblatex#931]
I got biblatex 3.13a via tlmgr, but there is no compatible biber release.  

Building biber is a PITA (I left perl ca. 20 years ago; managed to do the build, but still can't run the binary ), so keeping them in sync would be highly desirable.  

Since this is a new installation, I can't even downgrade via tlmgr.  And how do I know which biblatex version introduced the incompatible change?

**Comment by moewew** [comment]
Biber 2.13, which was released together with `biblatex` 3.13, is compatible with 3.13a. 3.13a was only a small bugfix release that should not affect anything about the `biblatex`-Biber relation and so there should be no need for a new Biber version. (Since 3.13a is only a *minor* release, the compatibility matrices in the documentations have not been updated.)

Do you experience any particular problem using Biber 2.13 with `biblatex` 3.13a?

**Comment by moewew** [comment]
Does `tlmgr` offer any Biber at all?

What OS are you using? Maybe Biber is simply not built for your platform. Because building Biber is a PITA (as you rightly point out) there are only a few volunteers who help with the most important platforms (at the moment Win 32, Win 64, Linux x86_32, Linux x86_64, Linux-musl, various OS X, Solaris).

**Comment by cwittern** [comment]
tlmgr does seem to offer biber, but on Ubuntu (I am using 19.10) tlmgr switches to user mode, but then refuses to install biber, claiming it is "not relocatable".  
For that reason, I am using the ubuntu package biber, which does only offer biber 2.12.  I downloaded biber 2.13 and symlinked it to my path, but although "which" tells me it is running from that location, the version reported is still 2.12, so I guess that has to do with how the Perl modules are loaded.

**Comment by moewew** [comment]
So is your `tlmgr` from a 'vanilla' TeX live installation from TUG.org (https://tex.stackexchange.com/q/1092/35864) or is it the `tlmgr` that comes from the Ubuntu packages?

If you have a vanilla TeX live from TUG, `tlmgr` should serve you the Biber update. If it does not, that would be something to take up with the TeX live maintainers, who are also in a better position to explain the 'not relocatable' issue (which I have never heard about, sorry): https://tug.org/mailman/listinfo/tex-live. (It only so happens that just yesterday I installed a vanilla TeX live 2019 from TUG.org on Ubuntu 18.04 x86_64 and manager to install `biblatex` 3.13a and Biber 2.13 without any problems, so I am very confident that this *should* work.)

In case you use vanilla TeX live you should under no circumstances install the Biber package from the Ubuntu repositories, that is just a recipe for disaster. In general I also strongly recommend against manually downloading Biber (where did you download it from?) as versions installed manually have the potential to become out of sync with the system-installed `biblatex`.

---

If `tlmgr` is from a Ubuntu-provided non-vanilla TeX live, then I'm lead to believe that `tlmgr` should not be used at all, since LaTeX packages are essentially managed, updated and installed from the Ubuntu repositories. In that case you would install the Ubuntu package that gives you Biber (https://packages.ubuntu.com/eoan/biber) and the one that contains `biblatex` (https://packages.ubuntu.com/eoan/texlive-bibtex-extra) and their versions should match (if they don't match, which has happened before, contact the maintainer of the Ubuntu LaTeX packages).

**Comment by cwittern** [comment]
Dear @moewew ,
Thank you very much for this detailed explanation.  I somehow assumed that the ubuntu package tex-live and its tlmgr and the upstream version from TUG.org would ultimately draw from the same pool.  Now I see that this is not the case, and also how to get a vanilla TexLive.  This seems the best way out of this mess and I will try to take that route.  This resolves this issue and I am closing it now. 
All the best,  Christian
