### ISSUE TITLE
Current documentation: for "3.13 2019-08-17" whereas last release is "3.13a 2019-08-31"

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#935]
The current documentation is for "3.13 2019-08-17" whereas last release is "3.13a 2019-08-31". Not critical but anyway :)

**Comment by moewew** [comment]
Not much we can do now, I'm afraid. If we re-upload to CTAN I think CTAN would want us to increase the version number, so that would hardly be worth it. I guess we can just promise to be more careful in the future?

This is not a big deal though, since 3.13a is only a bugfix release for 3.13 and the documentation does not differ significantly (we added two short passages about case sensitivity, but that should not interest many users). https://github.com/plk/biblatex/compare/v3.13...v3.13a?diff=split&w=1

**Comment by moewew** [comment]
@plk I noticed that the documentation in https://sourceforge.net/projects/biblatex/files/biblatex-3.14/biblatex-3.14.tgz/download says *Version 3.13a* on the title page, but the one in https://sourceforge.net/projects/biblatex/files/biblatex-3.14/biblatex-3.14.tds.tgz/download has the correct *Version 3.14*. I haven't checked for other file mismatches.

**Comment by plk** [comment]
I'll check - that is bizarre.

**Comment by plk** [comment]
I just regenerated and uploaded again - do you still see the issue?

**Comment by moewew** [comment]
The documentation looks good now (at least with the SourceForge mirror, I guess other mirrors should follow soon; as I said, I haven't looked at any other files). Thanks!

**Comment by moewew** [comment]
`biblatex` 3.14 is out now with the correct number on the title page, so I think this can be closed.
