### ISSUE TITLE
which new  features does this repo provide?

### ISSUE THREAD

**Issue by bookug** [plk/biblatex#942]
I can not find new detailed features in the README.

**Comment by moewew** [comment]
I'm not *quite* sure what you are asking about. This repository is mainly for development purposes. People can report issues, suggest improvements and submit pull requests.

* The [`master`](https://github.com/plk/biblatex/tree/master) branch usually coincides with the `biblatex` version that is on CTAN and that you can install in a current version of one of the major TeX systems (TeX live or MikTeX). (Due to the complicated release process involving Biber binary building, the `master` branch may be ahead of CTAN for a few days/weeks before the official CTAN release of the package. This is currently the case.)
* The [`dev`](https://github.com/plk/biblatex/tree/dev) branch contains the current development version/progress. If there are interesting (higher-level) changes, they are usually logged in [`CHANGES.md`](https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.md). 

You can always get a code-level diff between the two branches at https://github.com/plk/biblatex/compare/master...dev?diff=split&w=1.

I can absolutely not recommend to use the `dev` branch for anything other than testing or development. I would also not recommend to get `biblatex` from the `master` branch. Get `biblatex` (and the matching Biber version) from your TeX system.

**Comment by hushidong** [comment]
see the change file:
https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.md

**Comment by moewew** [comment]
Does the above answer your question? If not, can you please reformulate it a bit and explain in more detail what you are asking about?

**Comment by bookug** [comment]
I want to know, compared with traditional bibtex, why should I use this repo?

**Comment by josephwright** [comment]
@bookug That's asking for _the entire `biblatex` manual_ really; bottom line, `biblatex` allows the formatting of bibliographies to be adjusted in the LaTeX document, this then allows a massive range of additional features.

**Comment by moewew** [comment]
If you only want to know what `biblatex` can do compared to classical BibTeX, you may want to have a look at https://tex.stackexchange.com/q/25701/35864 and at https://tex.stackexchange.com/q/13509/35864 as well as the many introductory resources listed there.

The [*Overview* section of the Readme](https://github.com/plk/biblatex#overview) also gives a very rough sketch of the advantages of `biblatex` over classical BibTeX.

---

But let me please reiterate that it is usually better to get `biblatex` from your TeX distribution rather than downloading the code directly from the repository here.

**Comment by moewew** [comment]
There are many ways in which `biblatex` and classical BibTeX differ. Which of these differences matters to people is very different.

For me the most exciting bit about `biblatex` is that all entry data is available to `biblatex` in the LaTeX document in citations and the bibliography. In classical BibTeX the bibliographic data is not accessible systematically in the LaTeX document. BibTeX produces only typesettable bibliographies; packages like `natbib` have very clever ways to pass on additional data for citations, but they don't have full access to all data at all times.

A major consequence of this setup is that with `biblatex` bibliography and citation styles are written in LaTeX from within the document (preamble). There is no need to learn a different language (the `.bst` file language) to write your own style: Most things will look familiar if you are familiar with LaTeX.

Another consequence is that it is possible to do some things dynamically from within the document: It is for example possible to filter bibliographies by certain properties and generate split bibliographies.

`biblatex` is developed together with Biber. And Biber brings more exciting features to the table. The two most exciting things for me are

* Full Unicode support for sorting
* Dynamic data manipulation with sourcemaps

----

Now it has to be said that many people are still happy with BibTeX and have no incentive to switch to `biblatex`. If you are only writing English texts in a STEM field with very simple bibliography/citation conventions (probably STEM minus chemistry) the standard BIbTeX styles or maybe `natbib` might be all you need.

**Comment by moewew** [comment]
I'm closing this now, since this does not appear to be a bug report or feature request. If anything new comes up, please open a new issue.
