### ISSUE TITLE
langserbian and fromserbian are missing in the .lbx files

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#955]
Missing translations in the `.lbx` files used to be highlighted as follows:

```latex
% ...      = {{}{}},% FIXME: missing
```

That's not the case for the new `langserbian` and `fromserbian` strings that were not added to these files.

But compiling `03-localization-keys.tex` warn us about them so maybe it is the new way of warning about missing translations and this issue is irrelevant.

**Comment by moewew** [comment]
Yes, sometimes we used to add empty `FIXME` strings to all `.lbx` files when we add a new string (see for example https://github.com/plk/biblatex/commit/e77381904979f1ed9298740e46b4db1caabc3b98, I don't know how consistent we were, though). But that is cumbersome and since we ask language contributors to compile against `03-localization-keys.tex`, where missing strings are picked up, anyway, I thought I could get away with it.

Do you want me to add `langserbian` and `fromserbian` to all `.lbx` files? Of course I would happily accept a pull request if you want to do it :-)

**Comment by dbitouze** [comment]
>But that is cumbersome and since we ask language contributors to compile against 03-localization-keys.tex, where missing strings are picked up, anyway, I thought I could get away with it.

I agree.

>Do you want me to add langserbian and fromserbian to all .lbx files?

No! ;)

> Of course I would happily accept a pull request if you want to do it :-)

Consider I never asked anything about `langserbian` and `fromserbian` ;)
