### ISSUE TITLE
APA mistake in List of References

### ISSUE THREAD

**Issue by JoWi2** [plk/biblatex#967]
I found a problem with the APA style the other day, and hope this can be fixed easily (and ideally quickly):

When citing the following paper:

```
@article{Abrams2019,
	author = {Laura S. Abrams and Elizabeth S. Barnert and Matthew L. Mizel and Antoinette Bedros and Erica Webster and Isaac Bryan},
	doi = {10.1177/0011128719839356},
	journal = {Crime {\&} Delinquency},
	month = {apr},
	number = {2},
	pages = {219–249},
	publisher = {{SAGE} Publications},
	title = {When Is a Child Too Young for Juvenile Court? A Comparative Case Study of State Law and Implementation in Six Major Metropolitan Areas},
	volume = {66},
	year = {2019}
}
```

The result looks as follows:

> Abrams, L. S., Barnert, E. S., Mizel, M. L., Bedros, A., Webster, E., & Bryan, I. (2019).
When is a child too young for juvenile court? a comparative case study of state law
and implementation in six major metropolitan areas. Crime & Delinquency, 66 (2),
219–249. doi:10.1177/0011128719839356

Note that the letter in the "subtitle" so to speak is not capitalized. I checked with APA and got the response, that this letter needs to be capitalized (i.e. .... for juvenile court? A comparative.... ).

Thank you very much for fixing this!

**Comment by moewew** [comment]
Please note that this is the bugtracker for the `biblatex` core and its standard styles. If you want APA style you are probably using `biblatex-apa` and should be reporting bugs at https://github.com/plk/biblatex-apa/issues.

Anyway, here are two possible workarounds:

1. Make the 'subtitle' into an actual `subtitle`.
2. Protect the `A` with curly braces: `{A}`.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}


\begin{filecontents}[force]{\jobname.bib}
@Article{Abrams2019,
  author    = {Laura S. Abrams and Elizabeth S. Barnert and Matthew L. Mizel
               and Antoinette Bedros and Erica Webster and Isaac Bryan},
  title     = {When Is a Child Too Young for Juvenile Court?},
  subtitle  = {A Comparative Case Study of State Law
               and Implementation in Six Major Metropolitan Areas},
  doi       = {10.1177/0011128719839356},
  journal   = {Crime {\&} Delinquency},
  volume    = {66},
  number    = {2},
  year      = {2019},
  month     = apr,
  pages     = {219–249},
  publisher = {{SAGE} Publications},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
\cite{Abrams2019}
\printbibliography
\end{document}
```

Please note that the `month` must *not* be wrapped in braces if you use the three-letter name abbreviation. Also there should be a ```\``` before the `&` in the journal field, otherwise LaTeX will complain (but this might just be a copy-and-paste+formatting issue).

**Comment by plk** [comment]
Yes, this is a classic use case for the `SUBTITLE` field which you will notice I use extensively in the reference test bibliographies for the package.

**Comment by moewew** [comment]
I guess one *could* try to implement something similar to `\bbx@colon@search` also for question marks, but I'm not sure if that's worth the hassle.

https://github.com/plk/biblatex-apa/blob/b9ed20f69894145aa32c6781f2fe6530b50784e7/tex/latex/biblatex-apa/bbx/apa.bbx#L23-L43

Maybe we can bug @josephwright to add an auto-capitalisation-after-some-punctuation to `l3text`...

**Comment by plk** [comment]
Would be useful in some circumstances but this sort of case is semantically clearly a subtitle. Almost every paper and book in academia has a subtitle these days as everyone tries to be "engaging" to an audience apparently increasingly unable to bear simply learning things ...

**Comment by JoWi2** [comment]
Thank you all for your quick and helpful responses!
It certainly provided a helpful insight into how things work, and where problems might occur. The biblatex-entry was created by JabRef/DOI, so this might be another source of problems. On the other hand, since generating biblatex files via some kind of similar program (Mendeley, JabRef, Citavi,...) is quite common, it might be worth looking into how to this could also be addressed in biblatex, as it would only be one fix, instead of all different programs individually.

Thanks again!

**Comment by plk** [comment]
It's impossible in general to allow for all of the idiosyncrasies of auto-generated .bib files - the best systems allow for some customisation of the output or we provide the "sourcemapping" facility for dynamically changing the data as it is read by `biber` without the need to change the actual `.bib` files.

**Comment by moewew** [comment]
OK. To sum it up. The example posted above is a classical example for `subtitle`
```
@article{Abrams2019,
  author    = {Laura S. Abrams and Elizabeth S. Barnert and Matthew L. Mizel
               and Antoinette Bedros and Erica Webster and Isaac Bryan},
  title     = {When Is a Child Too Young for Juvenile Court?},
  subtitle  = {A Comparative Case Study of State Law
               and Implementation in Six Major Metropolitan Areas},
  doi       = {10.1177/0011128719839356},
  journal   = {Crime {\&} Delinquency},
  volume    = {66},
  number    = {2},
  year      = {2019},
  month     = apr,
  pages     = {219–249},
  publisher = {{SAGE} Publications},
}
```

And even if it weren't, the correct way to deal with it would be via case protection 
```
@article{Abrams2019:alt,
  author    = {Laura S. Abrams and Elizabeth S. Barnert and Matthew L. Mizel
               and Antoinette Bedros and Erica Webster and Isaac Bryan},
  title     = {When Is a Child Too Young for Juvenile Court?
               {A} Comparative Case Study of State Law
               and Implementation in Six Major Metropolitan Areas},
  doi       = {10.1177/0011128719839356},
  journal   = {Crime {\&} Delinquency},
  volume    = {66},
  number    = {2},
  year      = {2019},
  month     = apr,
  pages     = {219–249},
  publisher = {{SAGE} Publications},
}
```
You'll have to deal with case protection anyway if you cite something like
```
title = {Crime and Punishment in {U.S.} law},
```

I don't think `biblatex` should try to work around export tools that don't export correct/good data (there is a whole list of problems with automatically generated `.bib` entries at https://tex.stackexchange.com/q/386053/35864). For the most part there are clear specifications from the `biblatex` side how things should be done (many conventions are inherited from BibTeX) and if tools don't support that and still claim to produce `biblatex` output, the tools need to be fixed. (Note that JabRef is a different case than Mendeley and Citavi, the latter two export `.bib` files from an internal data representation, while JabRef lets you edit the `.bib` file directly and only imports entries from external sources: If those sources provided bad data, there is only so much JabRef can do. Mendeley and Citavi have to deal with source data - bad or otherwise - *and* with conversion from their internal format to `.bib` files.)

**Comment by moewew** [comment]
Closing this for now since this is technically a `biblatex-apa` issue and good solutions/workarounds were discussed.

String manipulation is surprisingly tricky in TeX and `biblatex`'s sentence casing macro is quite complex (we will hopefully be able to delegate most of that complexity to LaTeX3's `l3text` module very soon) and auto-case protection after punctuation seems simply not worth it.
