### ISSUE TITLE
Games entry

### ISSUE THREAD

**Issue by xexeo** [plk/biblatex#969]
I would like to suggest new database entries related to games, to be used in game studies.

They are, possibly:

game: 

And/Or possibly:
videogame: 
tabletopgame:

Videogames are games, but also software. They have publishers, studios, and game designers.
Tabletopgame: are games and some have designer, but usually they don´t have a studio, but have a publisher.

Both industries recognizes game designers in a similar way as of authors.
Most videogames have a publishing company and a different studio that makes them.

**Comment by moewew** [comment]
Thank you for the suggestion.

As you probably know `biblatex`'s underlying data model can be extended by the user: new entry types and fields can be added. See for example https://tex.stackexchange.com/q/175776/35864 and https://tex.stackexchange.com/q/163303/35864 on TeX.SX. So if you wanted to use these types, you could define them yourself.

At the moment I'm not convinced that those new types should be added to the core data model. The core data model is supposed to cover the most important and most used (essential) entry types and fields, but we are well aware that we can't cover everything and we don't want to have to cover everything. For while now the stance we take towards adding new stuff to the data model is that it either needs to be widely applicable (e.g. supported/required by several style guides etc.) and highly requested or require exciting new `biblatex` features that aren't yet implemented. See for example #72, #122, #156, #220, #224, #256, #272, #776, #880, #908.

**Comment by moewew** [comment]
I'm closing this as *won't fix* **for now**. As mentioned above, the standard data model can not fully cover everybody's wishes; it is intended to be a solid basis that works for most uses. Users can &ndash; and are encouraged to &ndash; provide additions to the standard data model for their needs.

If it turns out that this game entries are very important in a variety of fields, we can reconsider adding them to the standard data model at any time. So if you need it, please comment here, in particular if you can find bibliography style guides that require such types or if there is a strong prevalence of such a field in published works (at least if the desired output can not be achieved with `@misc` or `@online`).
