### ISSUE TITLE
Unpublished entries do not print eprint information

### ISSUE THREAD

**Issue by eddieschoute** [plk/biblatex#981]
I'm trying to cite an article that has only been prepublished on ArXiv. The suggestions in https://tex.stackexchange.com/questions/456340/unpublished-arxiv-entries-with-biblatex-biber or https://tex.stackexchange.com/questions/49757/what-should-an-entry-for-arxiv-entries-look-like-for-biblatex to use the `@online` type technically work but print the title in italics instead of in quotes, which is how articles are printed. Moreover, the `unpublished` type with `pubstate=prepublished` seems to apply better here.
An example entry
```
@Unpublished{Author2019,
  author      = {Author},
  title       = {My title},
  date        = {2019-12-12},
  eprint      = {1912.9999v3},
  eprintclass = {quant-ph},
  eprinttype  = {arXiv},
  pubstate    = {prepublished},
}
```
prints
> [6] Author. “Mytitle”. Dec.12,2019. Pre-published.

Note that there is not preprint information. Whereas if I change it to an article, then it outputs 
> [6] Author.“Mytitle”. In:(Dec.12,2019). arXiv:1912.9999v3[quant-ph]. Pre-published.

as expected (note the empty journal field causes an empty "In:" to be printed).

I'm also open to other suggestions.

**Comment by moewew** [comment]
It won't surprise you that my advice is to use `@online` for articles on the arXiv, after all that is what `biblatex-examples.bib` does: https://github.com/plk/biblatex/blob/2ddd2836927d08ac600c8fa3af1897417548ac05/bibtex/bib/biblatex/biblatex-examples.bib#L1392-L1405

If you don't like the way the title is formatted, you can easily adjust that with
```latex
\DeclareFieldFormat[online]{title}{\mkbibquote{#1\isdot}}
```

----

I'm not completely opposed to adding `eprint` information to `@unpublished` since the trio `doi+eprint+url` is so widespread nowadays that it should probably apply to all entry types alike. Indeed only, `@online` and `@unpublished` are picky about DOIs and `eprint`s and don't use the bibmacro `doi+eprint+url`

https://github.com/plk/biblatex/blob/0d37281977171eaf945850ef3363fa94e1d44c9a/tex/latex/biblatex/bbx/standard.bbx#L467-L506

https://github.com/plk/biblatex/blob/0d37281977171eaf945850ef3363fa94e1d44c9a/tex/latex/biblatex/bbx/standard.bbx#L701-L734

But changes here always come with a risk. If we add `eprint` to `@unpublished` entries, eprint info may be popping up in people's bibliographies where it didn't appear before, possibly to the dismay of the user. If we decide to go for the bibmacro `doi+eprint+url` (which I would probably want to do if we shake things up anyway), people patching the drivers and people who redefine `doi+eprint+url` may see undesirable side-effects of those changes.

**Comment by moewew** [comment]
@plk (and anyone else who may have an opinion here) I'd appreciate some thoughts on this. I think it would make sense to unify all drivers here to use `doi+eprint+url`. Since we now allow `url` as a per-type option there is no problem setting `url=true,` for `@online` such that the old behaviour that `url=false,` leaves alone `@online` entries could be retained. Users who don't like `eprint`s in `@unpublished` or `@online` could easily opt out with a per-type `eprint=false`.

I'm hopeful that such a change would not cause that many disruptions for styles. So far I could only identify [`biblatex-bath`](https://www.ctan.org/pkg/biblatex-bath) as affected:

https://github.com/alex-ball/bathbib/blob/e2aad742e1d2a67bf201515b883287990161061d/biblatex/biblatex-bath.dtx#L3157-L3161

in the past the developer adapted his style quickly to changes like this, so this seems doable (if we give him a heads-up well in advance).

I would like to get this done together with the `eid` changes for https://github.com/plk/biblatex/issues/847, so if anyone has some insight for that issue (where exactly do we add the `\printfield{eid}`? what about `pagetotal`?), that would be great as well.

**Comment by moewew** [comment]
To illustrate what I'm thinking about here, see https://github.com/moewew/biblatex/commit/a517f7a8299540039525823871182d8b45ebe10a.

**Comment by plk** [comment]
Unifying on `doi+eprint+url` is a good idea I think. I doubt that there is a good place for `eid` in another meta-macro that would satisfy all drivers - I suspect it might need adding to the top-level of drivers with `\printfield` for at least the edge cases.

**Comment by moewew** [comment]
Suggested changes to the standard styles are at #1000. Comments are welcome.

**Comment by moewew** [comment]
`biblatex` 3.15 with the style changes discussed here has been released and is available in MikTeX and TeX live.

The entry from above now shows eprint details as probably expected.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\begin{filecontents}{\jobname.bib}
@Unpublished{Author2019,
  author      = {Author},
  title       = {My title},
  date        = {2019-12-12},
  eprint      = {1912.9999v3},
  eprintclass = {quant-ph},
  eprinttype  = {arXiv},
  pubstate    = {prepublished},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,Author2019}
\printbibliography
\end{document}
```
In case that change is not desired it can be made undone with
```latex
\ExecuteBibliographyOptions[unpublished]{eprint=false}
```
